### ISSUE TITLE
Should still consider if CreateSnapshot should specify multiple names for the snapshots

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1]
There was the idea of a 1 to many relationship broached at one point. Could we do something smart for this relationship. And, what if the user wants to specify a whole lot of snapshots? Should we actually force them to specify the names of all the snapshots? Do they not care about the names and would they like to specify snapshots in differrent ways?

**Comment by agrover** [comment]
the name is how the user references them once created, so how could they not care?

**Comment by mulkieran** [comment]
I'm wondering if Stratis really needs to make them care. After all, Stratis isn't forcing the user to care about the size of a created volume by making them enter it. The problem is that a user might create 1000 snapshots, maybe, and then just want to do some stuff with _some_ of them. So, is there a better way for them to say thing than making them specify names? I dunno, but now is a better time to think about it than later.

**Comment by agrover** [comment]
any further thoughts on this @mulkieran ?

**Comment by mulkieran** [comment]
Not yet.

**Comment by agrover** [comment]
This is something about atomic snapshots of multiple filesystems, as a "consistency group". We're not sure if DM makes this possible.

**Comment by agrover** [comment]
current API only allows one snapshot to be created in a single go.
