### ISSUE TITLE
Design, document, implement and on-disk metadata format for Stratis 1.0

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1014]
This is important because we will need to support this for a long time.

**Comment by kocoten1992** [comment]
As a user, as long as I could upgrade stratisd without problem, metadata could change however needed I think

**Comment by agrover** [comment]
Yeah. But from a coding perspective, 1.0 is when compatibility is something we need to worry about. Sometimes during development, we have made changes that cause the new version to fail to work against metadata created by the version from the previous day. That doesn't fly after 1.0. If we did make such a change, we would need to be able to read the new AND the old format. And maybe we'd write the metadata only ever using the new format, or maybe not, but it becomes something we need to think about a lot more than currently.

Therefore, we want to nail down the metadata format for 1.0 as much as possible. If we design our 1.0 metadata so that it more easily incorporates additions then it will make future development easier.

**Comment by kocoten1992** [comment]
Hi, there is a trick I've learn when install gitlab, like when user are at 9.x version and want to upgrade to 11.x version (using ```apt-get upgrade gitlab```), they force me to go through 10.x before go to 11.x versions.

We could have apply that technique here, so user stratisd at 1.0 and want to go strange to 3.0, we said no, let them upgrade to 2.0 first, then we migrate the metadata, and then let them upgrade to 3.0

Hope this help :+1:
