### ISSUE TITLE
Stratisd can have multiple instances running at same time (regression)

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1015]
I was able to run 3 instances of stratisd today off of master branch.  I knew we added a lock file to handle this.  I believe the problem is this:

```
...
openat(AT_FDCWD, "/var/run/stratisd.pid", O_RDWR|O_CREAT|O_CLOEXEC, 0666) = 3
ioctl(3, FIOCLEX)                       = 0
flock(3, LOCK_EX|LOCK_NB)               = 0
getpid()                                = 25063
write(3, "25063\n", 6)                  = 6
close(3)
...
```

We need to keep the lock file open if we want to use `man 2 flock`.  I'm not sure when this broke during all the changes to `stratisd.rs`, but we need a unit test added for this in addition to a fix.

**Comment by mulkieran** [comment]
Related: #896.
