### ISSUE TITLE
Check that behavior is correct in all cases in BDA::read()

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1016]
from @mulkieran in #1012:
BDA::read() returns Result<(chunk1, chunk2)>. It returns an error if both fail. (That it more or less arbitrarily picks the first error is odd but not a fundamental problem).

If one succeeds but the other doesn't, one of the chunks it returns will be a buffer with data read from the device, the other will be an all-zero buffer. I believe. Remember that that all-zero buffer represents the fact that there was an error getting the raw bytes off the device.

Now, when StaticHeader::setup() gets an all zero buffer the result is Ok(None), meaning that the data was read, but no static header was on the device. So, if there was an error reading exactly one of the sections, one header will be anything, and the other will be Ok(None). This is the same value as if the region was read succesfully and was found not to have a Stratis magic number.

I think that there are six cases in the match expression in StaticHeader::setup() where Ok(None) is potentially meaning these two very different things: (1), we have no clue, because we couldn't even read the data (2), we're pretty sure this isn't a Stratis header, because there was no magic number.

Is the code simultaneously doing the right thing for both these meanings in all these six cases?

**Comment by mulkieran** [comment]
I tend to think honesty is the best policy on this one. Let ```BDA::read()``` return ```(Result<chunk1>, Result<chunk2>)``` rather than merging two results into one and let ```StaticHeader::setup()``` sort that one out however it needs to. But perhaps the point will become moot.
