### ISSUE TITLE
StaticHeader::sigblock_from_buf  make magic check handle small errors

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1017]
Today `sigblock_from_buf` does:

```rust
 if &buf[4..20] != STRAT_MAGIC {
    return Ok(None);
 }
```
Thus if we have a single bit incorrect in the those magic bytes we return that it's not ours.  Maybe we should consider allowing for some number of bits of error and return an `ErrorEnum::Invalid` instead as it would be better to note that the device is likely one of ours?

**Comment by mulkieran** [comment]
Related: #896.

**Comment by tasleson** [comment]
Agreed
