### ISSUE TITLE
Potential issue with Stratis root fs support

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1031]
At this point Stratis has the needed functionality to use Stratis as the root fs (needs: https://github.com/stratis-storage/stratisd/issues/987).  However, after reflecting on this I've come to the following observations:

1.  We compile dbus out for initrd as there is no dbus support, thus if we get dumped to the dracut emergency shell there is nothing an end user can to do correct the configuration or interrogate it

2. If dbus was available in initrd, we still couldn't utilize the stratis cli as its implemented in python which is not available too

I'm not sure what the ramifications are of this, or how much of a problem this could potentially be.

**Comment by mulkieran** [comment]
Closing as obsolete as we have been addressing this elsewhere, for example in: https://github.com/stratis-storage/stratisd/issues/2134.
