### ISSUE TITLE
Document how to actually try stratis/stratisd

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#104]
Document, either in README.md or somewhere else, how a prospective tester of Stratis would go about trying it. This likely involves cloning repos, installing rust, compiling stratisd, any PYTHONPATH or other things needed to run `stratis`, etc. and what to expect.

We at least need to cover a recent Fedora (24?), but could also go further and cover a Debian version that includes rustc as well.

**Comment by mulkieran** [comment]
@agrover Have we done this?

**Comment by agrover** [comment]
I think so, closing.
