### ISSUE TITLE
Use rustfmt config file

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1053]
Each new version of rustfmt seems to change the default config. We should use a rustfmt config file so that it's possible to use a range of different rustfmt versions and get the same result.

I think we looked at this at one point? But maybe we should take another look.

Rustfmt has a command that generates a config file that matches the current style, perhaps this would be a good place to start.

**Comment by mulkieran** [comment]
We used to have a ```rustfmt.toml```. But it turned out that the one configuration spec that we had in it, ```use_try_shorthand = true``` was considered unstable in rustfmt-preview at that time.

**Comment by mulkieran** [comment]
It turns out that 50/59 of the rustfmt configuation parameters cause a variant of this warning:

```
Warning: can't set `spaces_around_ranges = false`, unstable features are only available in nightly channel.
```

Here's all the configuration that's left:

```
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
wrap_comments = false
normalize_comments = false
merge_derives = true
force_explicit_abi = true
unstable_features = false
```

Note that the last one is ```unstable_features = false```. If we set that to true, the warnings that are received are the same. Using ```--unstable-features``` flag gives warning "Unstable features are only available on Nightly channel' and stops rustfmt entirely.

**Comment by mulkieran** [comment]
This is obsolete. We are getting along pretty well w/ rustfmt these days, and we'll add a configuration file when we need it. Also, the project is moving a bit slowly these days, so the configuration options that we most care about, the one that requires merged imports, will probably stay on nightly for a very long time.
