### ISSUE TITLE
Security concerns with returning mount points for Stratis mounted filesystems

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1090]
We are leveraging `/proc/self/mountinfo` for the mount information.  As this "view" is based on the current processes PID, it's an information leak to return information from it's view of the world and say a chroot'd client can see.  This makes the returned data suspect in that it's leaking mount information.  We need to find out if this is something we need to remove or potentially change, in that we consider the clients PID when we return the queried data.

**Comment by agrover** [comment]
no longer supported, closing.
