### ISSUE TITLE
Scalibility issues with returning mount points for Stratis filesystems

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1091]
Today the proposed implementation of the dbus property which returns mount points of each of the Stratis provided file system is iterating through the entire `/proc/self/mountinfo` for each Stratis file system.  For large configurations this will not scale.

One possible solution is to use poll on `/proc/self/mountinfo` and update an internal hashmap of mounts as needed, sample C code tested on F27 (ref. https://stackoverflow.com/questions/5070801/monitoring-mount-point-changes-via-proc-mounts).

``` c
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdlib.h>
#include <stdio.h>
#include <poll.h>


int main(void) {
	int rv = 0;
	int mfd = open("/proc/self/mountinfo", O_RDONLY, 0);
	struct pollfd pfd;
	
	pfd.fd = mfd;
	pfd.events = POLLERR | POLLPRI;
	pfd.revents = 0;
	while ((rv = poll(&pfd, 1, 5)) >= 0) {
		if (pfd.revents & POLLERR) {
		   fprintf(stdout, "Mount points changed.\n");
		}

		pfd.revents = 0;
	}
}
```
We could add this to the main event loop and keep the cache updated.  Then all dbus queries are handled in memory.

Although this will not work if we need to accommodate changes for https://github.com/stratis-storage/stratisd/issues/1090 which involve taking into account the clients process id which would then prevent us from having a single cache.

**Comment by agrover** [comment]
we no longer do this, I think I can close this one.
