### ISSUE TITLE
Get wrong information of disk after creating FS on a pool.

### ISSUE THREAD

**Issue by dragonJACson** [stratis-storage/stratisd#1112]
### System Information

- Kernel Version: 4.14.65-1-lts
- `stratisd` compiled from master branch
- `stratis-cli` installed from AUR
- The system is on NVMe SSD

### What's wrong

I create a pool on a 64GiB SSD, then I create FS on the pool. After that, I got a `1TiB SIZE` partition under that 64GiB SSD.

```
# lsblk
```

Partial Output:

```
NAME                                                                                        MAJ:MIN RM   SIZE RO TYPE    MOUNTPOINT
sdb                                                                                           8:16   0  59.6G  0 disk
└─stratis-1-private-60c1a5b2c2464261aa4d85b23a77aaed-physical-originsub                     254:0    0   1.6G  0 stratis
  ├─stratis-1-private-60c1a5b2c2464261aa4d85b23a77aaed-flex-thinmeta                        254:1    0    16M  0 stratis
  │ └─stratis-1-private-60c1a5b2c2464261aa4d85b23a77aaed-thinpool-pool                      254:3    0   1.6G  0 stratis
  │   └─stratis-1-60c1a5b2c2464261aa4d85b23a77aaed-thin-fs-7900e16f8dbe4cf8a615408d683ee623 254:5    0     1T  0 stratis
  ├─stratis-1-private-60c1a5b2c2464261aa4d85b23a77aaed-flex-thindata                        254:2    0   1.6G  0 stratis
  │ └─stratis-1-private-60c1a5b2c2464261aa4d85b23a77aaed-thinpool-pool                      254:3    0   1.6G  0 stratis
  │   └─stratis-1-60c1a5b2c2464261aa4d85b23a77aaed-thin-fs-7900e16f8dbe4cf8a615408d683ee623 254:5    0     1T  0 stratis
  └─stratis-1-private-60c1a5b2c2464261aa4d85b23a77aaed-flex-mdv                             254:4    0    16M  0 stratis
nvme0n1                                                                                     259:0    0 238.5G  0 disk
├─nvme0n1p1                                                                                 259:1    0    16M  0 part
├─nvme0n1p2                                                                                 259:2    0   500M  0 part
├─nvme0n1p3                                                                                 259:3    0 125.9G  0 part
├─nvme0n1p4                                                                                 259:4    0   1.7G  0 part
└─nvme0n1p5                                                                                 259:5    0 110.4G  0 part    /
```

```
# fdisk -l
```

Patial Output:

```
Disk /dev/sdb: 59.6 GiB, 64023257088 bytes, 125045424 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk /dev/mapper/stratis-1-60c1a5b2c2464261aa4d85b23a77aaed-thin-fs-7900e16f8dbe4cf8a615408d683ee623: 1 TiB, 1099511627776 bytes, 2147483648 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 1048576 bytes / 1048576 bytes
```

```
# stratis pool list
```

Output:

```
Name       Total Physical Size  Total Physical Used
stratis            < 59.63 GiB              598 MiB
```

```
# stratis fs list stratis
```

Output:

```
Name
storage
```

### My way to reproduce

```
# wipefs -a /dev/sdb
# stratis pool create stratis /dev/sdb
# stratis fs create stratis storage
```

### More Information

- [Log](https://glot.io/snippets/f40nb5ma1y) from stratisd

**Comment by agrover** [comment]
Hi, thanks for trying Stratis.

1 TiB is the filesystem's initial virtual size. I know this shows up in `df` but this value does not actually mean anything much to users. Used space in the pool will be less due to thin provisioning, and the virtual size will be automatically increased if data in the filesystem approaches 1 TiB. For Stratis, the important values are the capacity vs. used of the overall pool. It's also valuable to know how much space each filesystem uses, and we have updates to stratis-cli that will give this information.

This is going to be a very common question I think. It should be item 1 in the Stratis FAQ (when it is written). We also have discussed if changes to `df` could be made, but for the short term it is just a weird thing we need to document so people know to expect it.

**Comment by dragonJACson** [comment]
Thank you for your kind reply.

So this is an expected behavior, nothing goes wrong. That's good news for me. Yeah, it's really a weird thing for me, because I have a 1TiB HDD, when I got a 1TiB virtual size for the 64GiB SSD, I was a little bit worried about that HDD, but nothing happened. Now my doubts resolved, thank you.

BTW, I think this is really a great project, I will keep on trying it.
