### ISSUE TITLE
Test that Stratis works on a variety of block storage configurations

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1117]
#902 says we should document how to use Stratis on top of other things, but hey we should probably also actually TEST that Stratis works smoothly on LVM, raid, encryption etc. #1099 should ensure we don't work on devices also used for a multipath device, but Stratis *should* work on top of the composed devices, e.g. /dev/mpath0 or whatever.

We also need to see how Stratis works on top of network block storage like iSCSI. This is important so we can explicitly tell people not to try this, if there are issues.

**Comment by tasleson** [comment]
Tests done so far and what was encountered. 

Test is creating a Stratis pool and FS, taking UUID adding to fstab and rebooted to ensure Stratis backed FS comes up.

* Stratis pool created on LVM LVs => https://github.com/stratis-storage/stratisd/issues/1130
* Stratis pool created on md raid (mirror) => https://github.com/stratis-storage/stratisd/issues/1141
* Stratis pool created on luks encrypted devices => https://github.com/stratis-storage/stratisd/issues/1137

**Comment by tasleson** [comment]
@agrover Any other configuration you would like me to try out?  I think we've covered the basic stuff :smile_cat:

**Comment by agrover** [comment]
That's all I can think of. Righto! Are we ready to close this issue?

**Comment by tasleson** [comment]
Basics covered
