### ISSUE TITLE
Create a team Rustlang style guide

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#112]
It should be used when there is no obvious natural order.

It makes the addition of new things non-random, and it makes it reasonably easy for the programmer to read.

**Comment by agrover** [comment]
Is this for: use declarations? Ordering of members in a struct? function arguments?

**Comment by mulkieran** [comment]
Anywhere where there is nothing better and there are letters.

**Comment by agrover** [comment]
on top of rustfmt there are issues like ordering things. Having a small document to clarify and give reasons for a consistent style across the code is a good idea.

**Comment by agrover** [comment]
I've checked in a rough initial version into stratis-docs repo [here](https://github.com/stratis-storage/stratis-docs/blob/master/docs/style/StratisStyleGuidelines.lyx).
