### ISSUE TITLE
Add PoolState property to D-Bus API

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1121]
Extending on the rudimentary PoolState from #1083, this should be exposed as a read-only enumerated property (similar to Blockdev state). Ideally, it should also generate a signal when it changes.

**Comment by mulkieran** [comment]
How will we extend PoolState? ```Good``` and ```Bad``` pretty much cover the whole space. Are we going to have a suite of new states to communicate finer shades of meaning? This would be fine w/ me. I bring the matter of extensibility up, because everything that is part of our D-Bus API is part of our public API.

**Comment by agrover** [comment]
I was thinking a pair of values, with the first being stopped or started, and the second being conditions within each: eg  stopped/incomplete, stopped/duplicate name, started/good, started/read-only. Not sure of the complete set of values, hopefully the API would allow additions. Don't know. Also don't know how pool space states should be reflected, in this, or a separate property.

**Comment by agrover** [comment]
Maybe have a third value be space state?

**Comment by trgill** [comment]
Added PR #1158 as a step in the direction of this issue

**Comment by agrover** [comment]
fixed by #1229
