### ISSUE TITLE
Add a new interface for reports; use it to shown liminal block devices

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1122]
Depends on #1121. Add Incomplete to PoolState pool property. Incomplete pools should be shown in the D-Bus API, using the new pool state. Blockdevs should also be shown in D-Bus, using the Blockdev State field to indicate which of the 5 blockdev states they are (missing, bad, spare, notInUse, In-Use) with missing devices as Missing. Devices that are present in the incomplete pool, I guess list them as NotInUse, would make the most sense?

**Comment by mulkieran** [comment]
Unassembled devices do not really have all the attributes of pools until they become assembled. It's more reasonable to use a single method that returns formatted output, then to put objects on the D-Bus.

**Comment by mulkieran** [comment]
I think we should introduce a separate interface. Call it ```Reporting```, or possibly ```Unstable```.

**Comment by mulkieran** [comment]
Schema:

```
{ "type": "array",
  "items": {
    "type": {
                  "type": "object",
                  "properties": {"pool_uuid": { "type": "string" },
                                       "devices": {"type":
                                                                 {"type": "array",
                                                                  "items": "string"}}                 
                }
  }
}
```

So an example would be:

```
[{"pool_uuid": "<some UUID as simple ref>", "devices": ["/dev/abc", "/dev/bdg"]},
 {"pool_uuid": "<some UUID as simple ref>", "devices": ["/dev/gdh", "/dev/ths"]}]
```

**Comment by mulkieran** [comment]
Although jsonschema.net generates this:

```
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "The Items Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "examples": [
            {
                "devices": [
                    "/dev/abc",
                    "/dev/bdg"
                ],
                "pool_uuid": "<some UUID as simple ref>"
            },
            {
                "devices": [
                    "/dev/gdh",
                    "/dev/ths"
                ],
                "pool_uuid": "<some UUID as simple ref>"
            }
        ],
        "required": [
            "pool_uuid",
            "devices"
        ],
        "properties": {
            "pool_uuid": {
                "$id": "#/items/properties/pool_uuid",
                "type": "string",
                "title": "The Pool_uuid Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "<some UUID as simple ref>"
                ]
            },
            "devices": {
                "$id": "#/items/properties/devices",
                "type": "array",
                "title": "The Devices Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": [],
                "items": {
                    "$id": "#/items/properties/devices/items",
                    "type": "string",
                    "title": "The Items Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "/dev/abc",
                        "/dev/bdg"
                    ]
                }
            }
        }
    }
}
```

from the example.

**Comment by mulkieran** [comment]
@jbaublitz: I'm handing this over to you. There isn't much interesting in PR #1863 except that I do like "liminal devices" much more than "incomplete pools"; it's more descriptive and accurate. I outlined a format for the report, but that's not intended to be definite.

**Comment by jbaublitz** [comment]
@mulkieran I've begun work on this and am currently in the process of designing a `Report` interface that has one method, `get_report`, that takes the name of the report as a parameter and returns a JSON object as the return value. The two reports I plan to support at the moment are the engine state which we removed from the logging and the report of devices that were able to construct a complete pool. While I agree that liminal devices is more accurate than incomplete pool, I worry that this specific name will be unclear to users of the API. I would not know what liminal devices meant in the context of Stratis if I were not working on this PR so I would recommend that we discuss other names that we can potentially use over the API from a user-friendliness standpoint that will be equally accurate.

**Comment by mulkieran** [comment]
@jbaublitz Before you go ahead w/ the engine state; let's discuss in standup. It's probably a good idea, but the actual JSON output from the logging method that we use is cruddy. We will have to make sure that we have a good way of being obvious that there is some instability in this interface, because we will want to improve the output.

**Comment by jbaublitz** [comment]
Okay that sounds good! I'll proceed with the interface I've defined then but I'll hold off on implementing the engine state and focus in the other state outlined in the issue.
