### ISSUE TITLE
Add ability to unload Stratis pools for one, some, or all

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1128]
It would be good to have the ability to unload a configuration without resorting to destroying Stratis pools or using `dmsetup` manually.  This would be useful for development/testing and potentially may be needed to add for system shutdown as well (thinking dracut shutdown pivot)

**Comment by agrover** [comment]
This could make cleanup on CI nodes a lot less error-prone, for example.

**Comment by mulkieran** [comment]
We have two other issues w/ generally the same idea, closing this one.
