### ISSUE TITLE
Engine methods should be changed to add and remove multiple things

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#113]
Right now they only remove or add things one at a time. But, as we discussed, it may be necessary to realize efficiencies that are avilable when doing things in batches.

This is not an urgent problem for the sim enigine, but the real engine and the sim engien will have to match their API, and I think it should be addressed for the real engine.

**Comment by agrover** [comment]
see #156

**Comment by mulkieran** [comment]
Still need to work on ```RemoveDevs```, ```RemoveCacheDevs```, ```CreateFilesystems```, ```DestroyFilesystems```.

**Comment by agrover** [comment]
The first two can wait since it's going to be a long time before the engine (StratEngine at least...) is going to be able to do these, fwiw.

**Comment by mulkieran** [comment]
Closed by #190.
