### ISSUE TITLE
Enable NotInUse blockdevs to be removed from a pool.

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1138]
Since blockdevs are now used lazily, blockdevs that are not in use can potentially be removed. The only wrinkle (that I can think of atm) is that we would not want to allow an unused blockdev to be removed if its removal would result in the pool FreeSpaceState leaving a Good condition.

**Comment by mulkieran** [comment]
This is obsolete, as we track a different set of states for blockdevs and for pools, and currently allocate greedily.
