### ISSUE TITLE
Stratis stacked on multipath results in startup boot hang

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1142]
We are getting the following message when we try to boot:

```
WARN libstratis::engine::strat_engine::engine: no pool set up, reason: 
Engine(Error, "failed to set up pool for (pool UUID: 85c985d1-4e5b-4b02-8c1c-aeb5ca470fe9, devnodes: /dev/sdj ,/dev/sdd ,/dev/sdc ,/dev/sdk): 
reason: Engine(Invalid, \"The following list of Stratis UUIDs were each claimed by more than one Stratis device: [Uuid { bytes: [189, 15, 99, 222, 235, 237, 74, 210, 137, 134, 76, 198, 180, 69, 199, 239] }, Uuid { bytes: [214, 61, 167, 84, 184, 71, 70, 43, 146, 84, 81, 102, 253, 73, 49, 235] }]\")")
```
The device paths listed correspond to the individual paths that comprise the multipath devices.  We should be ignoring these paths, assuming the udev db has the correct values at the time we evaluate them.

Restarting the stratis daemon when we are in the emergency shell works and we utilize the correct multipath devices `/dev/mapper/mpatha` and `/dev/mapper/mpathb` and the FS gets mounted.

**Note: Code was build off of local branch that has multipath support and the fix for missing udev 'add' events.**

**Comment by tasleson** [comment]
It appears that at the time we get the udev events and we interrogate the udev db for the devices they don't have the values we are looking for, eg.

udev db entry when we interrogate
```
"DEVNAME": "/dev/sdk"
"DEVTYPE": "disk"
"MINOR": "160"
"SUBSYSTEM": "block"
"DEVPATH": "/devices/pci0000:00/0000:00:03.0/0000:08:00.1/host7/rport-7:0-0/target7:0:0/7:0:0:1/block/sdk", "MAJOR": "8"
```

Udev entry later
```
P: /devices/pci0000:00/0000:00:03.0/0000:08:00.1/host7/rport-7:0-0/target7:0:0/7:0:0:1/block/sdk
N: sdk
S: disk/by-id/scsi-360a98000423664653024426830595064
S: disk/by-id/wwn-0x60a98000423664653024426830595064
S: disk/by-path/pci-0000:08:00.1-fc-0x500a098190ba5a64-lun-1
E: DEVLINKS=/dev/disk/by-id/scsi-360a98000423664653024426830595064 /dev/disk/by-id/wwn-0x60a98000423664653024426830595064 /dev/disk/by-path/pci-0000:08:00.1-fc-0x500a098190ba5a64-lun-1
E: DEVNAME=/dev/sdk
E: DEVPATH=/devices/pci0000:00/0000:00:03.0/0000:08:00.1/host7/rport-7:0-0/target7:0:0/7:0:0:1/block/sdk
E: DEVTYPE=disk
E: DM_DEL_PART_NODES=1
E: DM_MULTIPATH_DEVICE_PATH=1
E: ID_BUS=scsi
E: ID_FS_TYPE=mpath_member
E: ID_FS_USAGE=raid
E: ID_FS_UUID=d63da754b847462b92545166fd4931eb
E: ID_FS_UUID_ENC=d63da754b847462b92545166fd4931eb
E: ID_MODEL=LUN
E: ID_MODEL_ENC=LUN\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_PATH=pci-0000:08:00.1-fc-0x500a098190ba5a64-lun-1
E: ID_PATH_TAG=pci-0000_08_00_1-fc-0x500a098190ba5a64-lun-1
E: ID_REVISION=811a
E: ID_SCSI=1
E: ID_SCSI_SERIAL=B6de0$Bh0YPd
E: ID_SERIAL=360a98000423664653024426830595064
E: ID_SERIAL_SHORT=60a98000423664653024426830595064
E: ID_TARGET_PORT=3
E: ID_TYPE=disk
E: ID_VENDOR=NETAPP
E: ID_VENDOR_ENC=NETAPP\x20\x20
E: ID_WWN=0x60a9800042366465
E: ID_WWN_VENDOR_EXTENSION=0x3024426830595064
E: ID_WWN_WITH_EXTENSION=0x60a98000423664653024426830595064
E: MAJOR=8
E: MINOR=160
E: MPATH_SBIN_PATH=/sbin
E: SUBSYSTEM=block
E: SYSTEMD_READY=0
E: TAGS=:systemd:
E: USEC_INITIALIZED=16068915
```
From the journal I can see that we interrogate the devices before `multipathd` gets a chance to run which then sets up the dm tables for multi-path.

Additionally, things are complicated by the fact that if we find a block dev with a stratis signature we add it to a list of devices that are incomplete.  However, in this case those devices shouldn't even be in the list as they are the individual paths to the devices.

Not sure what the best course of action is at this time.

**Comment by tasleson** [comment]
@prajnoha Suggestions?  Maybe we need to start the stratisd service after multipathd has started up?

**Comment by tasleson** [comment]
@prajnoha Thanks for the information.  We are using `libudev` library wrapper and it appears we are utilizing the `udev` source name, see: https://github.com/dcuddeback/libudev-rs/blob/master/src/monitor.rs#L33

```rust
    /// Creates a new `Monitor`.
    pub fn new(context: &'a Context) -> ::Result<Self> {
        let name = CString::new("udev").unwrap();

        let ptr = try_alloc!(unsafe {
            ::ffi::udev_monitor_new_from_netlink(context.as_ptr(), name.as_ptr())
        });

        Ok(Monitor {
            context: context,
            monitor: ptr
        })
    }
```

There is a method on the device `is_initialized` which internally calls `udev_device_get_is_initialized`, I'm not sure if that's something that should already return as completed if we are passing `udev` into the monitor creation or not.

**Comment by tasleson** [comment]
I created a super simple C program that listens for udev block events and ran it at boot too.  It appears that by the first time it gets an event for the block device it has the following:

```bash
Sep 04 12:04:16 rhel-storage-11.lab.bos.redhat.com udev_debug[599]: UDEV BLOCK EVENT DEBUG
Sep 04 12:04:16 rhel-storage-11.lab.bos.redhat.com udev_debug[599]: .ID_FS_TYPE_NEW=mpath_member
Sep 04 12:04:16 rhel-storage-11.lab.bos.redhat.com udev_debug[599]: ACTION=add
Sep 04 12:04:16 rhel-storage-11.lab.bos.redhat.com udev_debug[599]: DEVLINKS=/dev/disk/by-path/pci-0000:08:00.0-fc-0x500a098180ba5a64-lun-1 /dev/disk/by-id/scsi-360a98000423664653024426830595064 /dev/disk/by-id/wwn-0x60a98000423664653024426830595064
Sep 04 12:04:16 rhel-storage-11.lab.bos.redhat.com udev_debug[599]: DEVNAME=/dev/sdk
Sep 04 12:04:16 rhel-storage-11.lab.bos.redhat.com udev_debug[599]: DEVPATH=/devices/pci0000:00/0000:00:03.0/0000:08:00.0/host6/rport-6:0-0/target6:0:0/6:0:0:1/block/sdk
Sep 04 12:04:16 rhel-storage-11.lab.bos.redhat.com udev_debug[599]: DEVTYPE=disk
Sep 04 12:04:16 rhel-storage-11.lab.bos.redhat.com udev_debug[599]: DM_DEL_PART_NODES=1
Sep 04 12:04:16 rhel-storage-11.lab.bos.redhat.com udev_debug[599]: DM_MULTIPATH_DEVICE_PATH=1
...
```
The output from `stratisd` daemon which happened a couple of seconds earlier
```bash
Sep 04 12:04:14 rhel-storage-11.lab.bos.redhat.com stratisd[609]:  INFO libstratis::engine::strat_engine::backstore::device: Ours: ({"SUBSYSTEM": "block", "DEVNAME": "/dev/sdk", "DEVTYPE": "disk", "MAJOR": "8", "MINOR": "160", "DEVPATH": "/devices/pci0000:00/0000:00:03.0/0000:08:00.0/host6/rport-6:0-0/target6:0:0/6:0:0:1/block/sdk"})
```

It certainly appears like we are getting the event too soon for the Stratis daemon.

**Comment by prajnoha** [comment]
Hmm, the libudev wrapper looks good to me at first sight.

The `is_initialized` / `udev_device_get_is_initialized` should return false only in case there's no udev database entry for this device yet - usually when processing for the very first uevent for that device is not finished yet so there's no previous database entry. But this is not the case if you're listening with udev monitoring set with `udev` source (...because when you receive `udev` monitor event, there must be a record for the device clearly  - we've just completed udev rule processing). Normally, you could run into uninitialized devices when having monitor set with `kernel` source or if you're not monitoring at all, but asking about records directly through libudev (...so you can run into a situation where the first uevent is not yet processed).

So I'm thinking what might be the issue here - looks like the wrapper is not setting up the monitor correctly - but there's clear `udev` source set on the other hand...

Maybe try checking with the `is_initialized` and see what value it returns - if it returns 0 and at the same time  the `udev` source is set for monitoring, something is wrong in monitor initialization in the wrapper I suppose, not passing the argument correctly(?).

**Comment by mulkieran** [comment]
Is it possible to post the C program that yielded the above output?

**Comment by tasleson** [comment]
I also created a simple rust program and ran it at the same time as stratisd and the simple C program above.  It's also producing expected good results.  Thus whatever we are running into is some weird condition within the context of stratisd.  I'm not sure how to debug this at the moment.
```rust
extern crate libudev;
extern crate libc;
use std::os::unix::io::AsRawFd;

fn main() {

    let context = libudev::Context::new().unwrap();
    let mut monitor = libudev::Monitor::new(&context).unwrap();
    monitor.match_subsystem_devtype("block", "disk").unwrap();
    let mut udev = monitor.listen().unwrap();

    let mut fds = Vec::new();

    fds.push(libc::pollfd {
        fd: udev.as_raw_fd(),
        revents: 0,
        events: libc::POLLIN,
    });

    loop {
        let r = unsafe { libc::poll(fds.as_mut_ptr(), fds.len() as libc::c_ulong, -1) };

        if r < 0 {
            println!("Error on poll!");
            break;
        } else {
            if fds[0].revents != 0 {

                if let Some(event) = udev.receive_event() {

                    for property in event.properties() {
                        println!("{:?} = {:?}", property.name(), property.value());
                    }
                }
            } else {
                println!("poll returned, but revents == {} {} {}!",
                         fds[0].fd, fds[0].revents, fds[0].events);
            }
        }
    }
}

```

**Comment by mulkieran** [comment]
I _think_ that the problem is that this error is occurring in the call to ```find_all```. At that point, the monitor is not involved, devices are just obtained via enumerator mechanism.

**Comment by tasleson** [comment]
@mulkieran Very good catch, this indeed was the issue, thanks!
