### ISSUE TITLE
D-Bus properties that can fail should be eliminated

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1148]
Expensive D-Bus properties are properties that are computationally expensive or, even more important, require interacting with the environment. Cheap properties are ones that are obtained with a limited amount of computation and do not require any interaction with the environment.

Definitely cheap properties:
* Manager.Version

* Blockdev.Devnode
* Blockdev.HardwareInfo
* Blockdev.UserInfo
* Blockdev.InitializationTime
* Blockdev.State
* Blockdev.Pool
* Blockdev.Uuid
* Blockdev.Tier

* Filesystem.Devnode
* Filesystem.Name
* Filesystem.Pool
* Filesystem.Uuid
* Filesystem.Created

* Pool.Name
* Pool.Uuid

In-between Properties:
* BlockDev.TotalPhysicalSize - this may be an artifact of how this data is held now, but currently the computation _is_ cheap

Expensive Properties:
* Filesystem.Used - ~~May require mounting the filesystem, also statting~~. EDIT: Since #1149 requires DM status call.
* Pool.TotalPhysicalSize - Somewhat computationally expensive, as it is neccessary to iterate through all blockdevs belonging to the pool
* Pool.TotalPhysicalUsed - DM call to get status

See also #1267. Pool.TotalPhysicalUsed will be less and less meaningful as more layers are added.

**Comment by mulkieran** [comment]
The above should be an exhaustive list of currently published properties.

I propose that Blockdev.TotalPhysicalSize, Filesystem.Used, Pool.TotalPhysicalSize, Pool.TotalPhysicalUsed all be removed as properties and methods that obtain these values be substituted instead. The principal motivation is to avoid the problem of making invoking ```GetManagedObjects``` prohibitively expensive for large systems. Since almost every method in the CLI relies on a ```GetManagedObjects``` call, this is an important consideration.

Moreover, the four properties that I'm suggesting removing are not, unlike many of the cheap properties, useful for identifying particular objects of interest. It is very likely that a query for identifying Blockdev based on their pool would be constructed. But a situation where a Blockdev is identified by its total physical size is much less likely to arise programmatically. The only use that the CLI currently has for any of these expensive properties is to display them. This could be achieved quite easily with method calls.

This way, actually invoking these expensive methods becomes optional and not mandatory. 1.0 is approaching; we want to avoid having committing to supporting the computation of expensive and likely to fail values for virtually every Stratis CLI call, as once we're stuck in that position it will be very hard to write code that will fix the problem in a clean manner.

**Comment by mulkieran** [comment]
@agrover    I think this is an emergency, i.e., 1.0.

**Comment by agrover** [comment]
I disagree that these operations are obviously expensive, or that there is no way to mitigate their cost if they turn out to be more expensive than we thought.

* Filesystem.Used: a syscall per mounted filesystem seems fine. Could be cached. For umounted filesystems, mounting may be expensive (is it? I don't know. Haven't tested.) but we could record the last usage value we had for them and report that, since an unmounted filesystem is not being changed.
* Pool.TotalPhysicalSize: not expensive. could be cached.
* Pool.TotalPhysicalUsed: one syscall is not expensive, could be cached.

Using methods for some values would cause the API to have a mix of properties and methods for obtaining values, which is undesirable. e.g. D-Bus has a defined way to signal when property values change, but not method return values.

**Comment by mulkieran** [comment]
> I disagree that these operations are obviously expensive, or that there is no way to mitigate their cost if they turn out to be more expensive than we thought.

You misunderstood me if you think that is what I said. I'm not going to defend a position I did not choose to take.

**Comment by mulkieran** [comment]
Of the properties that I've suggested removing, only one is not set to ```EmitsChangedSignal::False```. It's not obvious to me that it is not the decision to make these properties, because it is possible, which is making it seem desirable to emit a signal on their change. Maybe that is a bad idea as well.

**Comment by mulkieran** [comment]
> Expensive D-Bus properties are properties that are computationally expensive or, even more important, require interacting with the environment.

Interacting with the environment is automatically expensive according to my definition, because it can fail. When it fails, ```GetManagedObjects``` fails, and the CLI invocation fails. If the particular method continues to fail, then it is very hard to interrogate stratisd via its D-Bus API, which is really its only API at this time, at all. I think that is a very bad situation to be in.

**Comment by mulkieran** [comment]
In case this wasn't clear, I was not proposing removing these D-Bus properties permanently; I was proposing removing them before 1.0 lands. After 1.0 lands, then we can change things up a bit. If we remove them from the properties now, and switch to methods, then we potentially have a story that just involves upgrades. For example, in the next release after 1.0, when we've worked out a really good way to handle these dangerous properties, we can put them back in and encourage newer users to make use of them, since they get the benefit, presumably, of signals on changes to these properties. If we keep them into 1.0, then we have to wait until 2.0 to deprecate them, and our story will very likely be one of buggy fixes made under duress.

Regarding your proposal of returning an Option value on error, I'm considering the consequences. The mechanics would be straightforward. The D-Bus layer in stratisd already has an underused function called ```tuple_to_option``` which translates a tuple put on the D-Bus by a client to an Option for stratisd's use. The way to handle your suggestion is to write an inverse function, ```option_to_tuple``` which take an optional value and puts a tuple on the D-Bus. This way, clients are forced by the type to take into account the possibility that no value is available, which is better than allowing them to forget.

**Comment by agrover** [comment]
They are not dangerous. These are core properties. They should always be available, and the likelihood of them failing is very very small. Thinking on this more, I now think we should keep them error-free & option-free. Instead, raise the stakes: if they fail, the entire pool should be put into an error state. Return the last-previously-retrieved value for the property value so GMO continues to work.

This is more work internally but simplifies the external interface, which I think is the right tradeoff. What do you think of this approach?

**Comment by mulkieran** [comment]
Can you guarantee that there is a last previously retrieved value for these properties that can fail, and for all subsequent properties that might be added and treated in the same way?

**Comment by agrover** [comment]
I haven't implemented yet but my thinking was we would require these values to be retrieved during `setup()`, or setup would fail.

If you're ok with this in principle I can work on a prelim PR.

**Comment by agrover** [comment]
I guess this would be a policy of our dbus api, some upper bound on how often these values would be updated (and generate signals). Signals every microsecond, even if that's how often the value is changing, are not useful imo.

So, a lower time bound on property update & signal generation? Maybe 1, 5, or 10 seconds-ish?

**Comment by mulkieran** [comment]
Removing from project, in favor of parent issue.

**Comment by mulkieran** [comment]
I'm closing this in favor of the parent issue: https://github.com/stratis-storage/project/issues/52. This can still be read as a reference.
