### ISSUE TITLE
Need a testing infrastructure for D-Bus signals

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1165]
AFAICT, this infrastructure would be best written in Rust. It seems like the Python implementation of D-Bus wrappers all require some heavy duty event-loop stuff for monitors and bring in more dependencies that way. A Rust implementation would probably have less overhead.

**Comment by mulkieran** [comment]
Currently, the only properties that emit signals are Name on pool and filesystem interfaces.

**Comment by mulkieran** [comment]
It looks like there was a bug in sim engine that caused properties not to be emitted, but we have all the infrastructure to do the emitting, and with the bug fixed I see this:

```
‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=8
  Sender=:1.3494  Path=/org/storage/stratis2/1  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.3494
  MESSAGE "sa{sv}as" {
          STRING "org.storage.stratis2.pool";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "Name";
                          VARIANT "s" {
                                  STRING "poolname2";
                          };
                  };
          };
          ARRAY "s" {
          };
  };
```

via "busctl monitor" when a pool is renamed.

**Comment by mulkieran** [comment]
@mvollmer: Can you confirm that this is what you would expect to see if a signal were being emitted when the pool "Name" property is changed?

**Comment by mvollmer** [comment]
> @mvollmer: Can you confirm that this is what you would expect to see if a signal were being emitted when the pool "Name" property is changed?

Yes, and I indeed do get this signals also in my own manual testing. I must have missed them earlier.

**Comment by mulkieran** [comment]
@mvollmer: Great!

I'm continuing to hold this bug open, because figuring out a good way to test that we do put out the signals as appropriate is desirable.

**Comment by jbaublitz** [comment]
@mulkieran I've found some Rust functionality in dbus-rs that should be able to listen for signals and send a notification back to main thread to indicate success. I'll see if I can put together some infrastructure for this. However, I'm unsure where this test would go as all of our Rust tests are currently unit tests and I don't think this would work very well as a unit test.

**Comment by mulkieran** [comment]
> @mulkieran I've found some Rust functionality in dbus-rs that should be able to listen for signals and send a notification back to main thread to indicate success. I'll see if I can put together some infrastructure for this. However, I'm unsure where this test would go as all of our Rust tests are currently unit tests and I don't think this would work very well as a unit test.

Rust also supports an integration test framework that might work. The other problem, though, is figuring out _what_ we would test.

**Comment by mulkieran** [comment]
I don't feel that the integration tests are the correct place, because these must work across the D-Bus. So, we would probably put the tests in the tests subdirectory in stratisd. We can, in fact, make them compound, Python and Rust, with the Rust part of the test being the part that detects the signals, and the Python being the part that runs any necessary commands.

So, what's the simple, maintainable test that will help us make sure that our signals are being set?

1. Start the signal receiving process.
2. Start stratisd.
3. Create a pool: lots of InterfacesAdded signals, for pool and for blockdevs.
4. Create filesystem: another InterfacesAdded signal.
5. Rename the filesystem: prop change signal.
6. Rename the pool: prop change signal.
7. Delete the filesystem: InterfacesRemoved signal.
8. Delete the pool: InterfacesRemoved signal.

What is our Rust-based signal receiving process doing? It is receiving signals from stratisd and recording them. It can either verify that they are as expected, or it can return a record of the signals received that the testing process can verify. In either case, though, the testing process that sends the commands to stratisd must specify the Rust process's expectations for signals.

**Comment by mulkieran** [comment]
@jbaublitz Can you point me at the callback functionality you were talking about?

**Comment by jbaublitz** [comment]
@mulkieran [This part of the D-Bus specification](https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-objectmanager) outlines typical client implementations for handling signals and dbus-rs seems to have a [corresponding binding here](https://docs.rs/dbus/0.8.4/dbus/blocking/struct.Connection.html#method.add_match).

**Comment by mulkieran** [comment]
Ok! It's a bit hard to figure out, but this connection stuff _looks_ like the low-level way in which the proxy stuff I was looking at is implemented.

**Comment by jbaublitz** [comment]
@mulkieran It's possible, but there's also a [higher level call on `Proxy`](https://docs.rs/dbus/0.8.4/dbus/blocking/struct.Proxy.html#method.match_signal). That might map more closely to what's described in the documentation.

**Comment by mulkieran** [comment]
I think that this testing will be so much less rewarding than all the other useful testing that we could be doing that we'll never get around to it.
