### ISSUE TITLE
Remove bad DbusErrorEnum enums such as NIX_ERROR

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1167]
We haven't looked at DbusErrorEnum and I think it is showing its age. For example:

* NIX_ERROR: we probably shouldn't expose the crate source of an error. Why should API users depend on this?
* INTERNAL_ERROR: How is this different from ERROR? It just sounds scarier (to me). See #1160. System-breaking errors should also consider putting the pool into an error state (#1121)
* IO_ERROR: Why would API users differentiate between this and ERROR?

I like the other ones -- API users may programmatically want to check if an API call failed for reasons like BUSY, ALREADY_EXISTS, or NOTFOUND, and then do a fallback action for example, but the ones above we should consider removing before API freeze for Stratis 1.0.

**Comment by mulkieran** [comment]
I think we need to be value-based, not type-based, on this one.

**Comment by agrover** [comment]
I don't follow, can you elaborate please?

**Comment by agrover** [comment]
waiting on #1179 since it touches the same area

**Comment by mulkieran** [comment]
This is surely in progress. But I think there will need to be work on the stratis-cli side as well. I'll take a look at it.
