### ISSUE TITLE
Review which signals we should include in Stratis 1.0

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1168]
@trgill @mulkieran @tasleson as per our discussion, we should want to minimize signals we support in Stratis 1.0, since for ones that can trigger frequently, we should specify how often they can trigger, and maybe offer some way for clients to set a threshold, perhaps.

Right now we expose 4 signals:
1. BlockdevStateChanged
1. FilesystemRenamed
1. FilesystemUsedChanged
1. PoolRenamed

The only one whose value will change often is FilesystemUsedChanged. Therefore I propose we push out supporting this signal past Stratis 1.0, until we can specify more details about the behavior that clients can expect from it.

**Comment by trgill** [comment]
Opened PR #1170 - don't send the signal - but leave the EventHandler in place.

**Comment by agrover** [comment]
done
