### ISSUE TITLE
What the test-suite thinks

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#117]
```
tests/manager/test_create.py sF.
tests/manager/test_destroy.py FFx
tests/manager/test_list.py ..
tests/manager/test_object_path.py ..F.FFF.FxFxFX
tests/manager/test_stratis.py sss
tests/pool/test_create_filesystem.py FF
tests/pool/test_destroy_filesystem.py ..F
tests/pool/test_list_devs.py F
```

It looks worse than it is, because a lot of those F's are due to Get*ObjectPath methods not yet available. Otherwise:

* ```create_filesystem``` engine method needs to be fixed so that it complains on duplicate filesystem names for same pool. I'll do that.
* ```CreateFilesystems()``` dbus method is occasionally failing because because dbus says that the method does not exist. My guess is that the proxy object does not exist yet when we invoke the method. We will have to address that issue more carefully and in a regular manner. The only sleeps I'm allowing in the test code are immediately after the service gets started, and it would be wrong to start putting in more. This problem is a lot harder than the first.

**Comment by mulkieran** [comment]
With PR #118, tests are a lot happier.

```
tests/manager/test_create.py s..
tests/manager/test_destroy.py .Fx
tests/manager/test_list.py .F
tests/manager/test_object_path.py .........xFxFX
tests/manager/test_stratis.py s
tests/pool/test_create_filesystem.py .F
tests/pool/test_destroy_filesystem.py Fss
tests/pool/test_list_devs.py F
```

and the problem with ```CreateFilesystems``` not existing appears to have been caused by my tests starting a new stratisd process before the previous one was quite terminated. That problem is now fixed. This was the most worrisome.

**Comment by mulkieran** [comment]
It is doing much better:

```
tests/manager/test_create.py s..
tests/manager/test_destroy.py ..x
tests/manager/test_list.py ..
tests/manager/test_object_path.py .........sssss
tests/manager/test_stratis.py s
tests/pool/test_create_filesystem.py ..
tests/pool/test_destroy_filesystem.py sss
tests/pool/test_list_devs.py .
```

but partly that is because it is skipping a few more. The next step is to start taking off some skips.

**Comment by agrover** [comment]
Any remaining work to do on this issue?

**Comment by mulkieran** [comment]
There's a few left:

```
tests/manager/test_create.py ..
tests/manager/test_destroy.py ...
tests/manager/test_list.py ..
tests/manager/test_object_path.py .........sssss
tests/manager/test_stratis.py s
tests/pool/test_create_filesystem.py ..
tests/pool/test_destroy_filesystem.py .F.
tests/pool/test_list_devs.py .
```

**Comment by mulkieran** [comment]
```
tests/dbus/manager/test_create.py ..
tests/dbus/manager/test_destroy.py ...
tests/dbus/manager/test_list.py ..
tests/dbus/manager/test_object_path.py .........sssss
tests/dbus/manager/test_stratis.py s
tests/dbus/pool/test_create_filesystem.py ..
tests/dbus/pool/test_destroy_filesystem.py .F.
tests/dbus/pool/test_list_devs.py .
```

**Comment by mulkieran** [comment]
This marks reaching some sort of parity with previous C implementation and is generally obsoleted by other issues.

The last F has been converted to an x, for an expected failure.
