### ISSUE TITLE
Fix/Document stratis pool add-cache causes IO to stop for the duration of the add

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1188]
Using `fio` test like:

```ini
[write-and-verify]
rw=randwrite
bs=4k
buffered=0
ioengine=posixaio
fallocate=none
iodepth=16
verify=crc32c
size=6G
max_latency=15s
```
`fio` will fail because the latency gets exceeded if we are using a debug build of `stratisd`.  I need to set the `max_latency` to 2 seconds to not fail the `fio` test with a release build when adding a cache device.

I'm not sure what improvements we can do to minimize the amount of time IO gets suspended, but we should likely instruct users to not add a cache device when the work load is sensitive to IO latency.

**Comment by tasleson** [comment]
@agrover I'll try to get some profiling data for this to see what's going on with debug version.

**Comment by tasleson** [comment]
For a release binary:
```
- 69.27% libstratis::engine::strat_engine::device::wipe_sectors                                                                ▒
               - libstratis::engine::strat_engine::device::write_sectors (inlined)                                                         ▒
                  + 46.79% std::io::Write::write_all                                                                                       ▒
                  + 15.60% <std::io::buffered::BufWriter<T> as libstratis::engine::strat_engine::device::SyncAll>::sync_all (inlined)      ▒
                  + 6.88% core::ptr::drop_in_place (inlined)
```

For debug binary

```
-   97.39%     0.00%  stratisd  stratisd                [.] libstratis::engine::strat_engine::device::wipe_sectors                         
     libstratis::engine::strat_engine::device::wipe_sectors                                                                                
   - libstratis::engine::strat_engine::device::write_sectors                                                                               
      - 95.65% std::io::Write::write_all                                                                                                   
         - 95.23% <std::io::buffered::BufWriter<W> as std::io::Write>::write                                                               
            - 94.85% <std::io::buffered::BufWriter<W>>::flush_buf                                                                          
               - 91.91% core::ptr::drop_in_place                                                                                           
                    <alloc::vec::Drain<'a, T> as core::ops::drop::Drop>::drop                                                              
                    core::iter::iterator::Iterator::for_each                                                                               
                    core::iter::iterator::Iterator::fold                                                                                   
                  + core::iter::iterator::Iterator::try_fold                                                                               
               + 2.94% <std::fs::File as std::io::Write>::write                                                                            
      + 1.09% <std::io::buffered::BufWriter<T> as libstratis::engine::strat_engine::device::SyncAll>::sync_all                             ▒
        0.50% core::ptr::drop_in_place
```
I haven't checked the code path, but I'm thinking that this `wipe_sectors` is happening in between when we suspend IO and resume it.  If that's indeed the case then hopefully we can reorder the `wipe_sectors` so it's not in the critical path.

**Comment by tasleson** [comment]
@agrover @mulkieran @trgill I looked at this one some more and I'm not seeing an **easy** way to fix us suspending IO for a non-trivial amount of time.  I was thinking that I could perhaps do a signature check of the devices to add for cache pool and if they are OK, zero the beginning of each device, but that's not what we are clearing when we do the `wipe_sectors`.  We are clearing the beginning of the resultant dm device after we create the tables for the cache.  Another thought was to not suspend in the case we are adding a **new** cache to a pool until we attach the cache to the existing pool, specifically until after we have cleared the beginning of the dm device, but I'm not sure of what sequence of steps are required to be done with the pool suspended.

I think someone that is more familiar with the intricacies of  how we are configuring the tables and adding it to the existing pool for caching would have better success in addressing this issue if we want it in the 1.0 release.

**Comment by mulkieran** [comment]
Do we know that the performance is different if block devices are added to the cache a second time, i.e., after the cache has been set up?

**Comment by tasleson** [comment]
> Do we know that the performance is different if block devices are added to the cache a second time, i.e., after the cache has been set up?

Looks like it's just the initial time when we are adding a cache to a pool, see below which illustrates adding a cache device for the first time and then adding another.

```
# time /root/stratis pool add-cache cache_add_pool /dev/sdg

real	0m43.647s
user	0m0.111s
sys	0m0.051s
[root@localhost target]# time /root/stratis pool add-cache cache_add_pool /dev/sdh

real	0m0.403s
user	0m0.136s
sys	0m0.063s
```

**Comment by mulkieran** [comment]
Thanks. The evidence is pretty consistent, then.

**Comment by agrover** [comment]
Document for 1.0 in relnotes, with a fix to come later.

**Comment by agrover** [comment]
@tasleson, merging #1244 may have lessened the impact of this issue.

**Comment by tasleson** [comment]
The impact has been lessened.
