### ISSUE TITLE
test_udev.py has begun failing intermittently

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1189]
This is the second time this has occurred, but here is one example: https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/1953/console.

**Comment by mulkieran** [comment]
Recent: https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/2275/console

**Comment by tasleson** [comment]
We got another failure with latest fixes, ref. https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/2328/console

**Comment by mulkieran** [comment]
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/2575/console

**Comment by mulkieran** [comment]
This might be relevant: https://github.com/stratis-storage/stratisd/pull/1477#issuecomment-478593419. This is not about ```test_udev.py``` per se, but about device discovery failing in a regular test.

**Comment by tasleson** [comment]
Addressed with https://github.com/stratis-storage/stratisd/pull/1510

**Comment by mulkieran** [comment]
Assuming this was all caused by #1446, and fixed by #1510, this can be closed.
