### ISSUE TITLE
D-Bus error message when running `stratis pool list` after blockdev removal

### ISSUE THREAD

**Issue by tstdin** [stratis-storage/stratisd#1195]
Steps:
1. Create a new pool and a FS on a USB flash drive
2. Remove the drive
3. See errors

After step 1, the FS was functional. 

Step 3: `# stratis pool list` (or other operation)
```
Execution failure caused by:
Message recipient disconnected from message bus without replying
    which in turn caused:
Error while invoking method "GetManagedObjects" belonging to interface "org.freedesktop.DBus.ObjectManager" with arguments ()
```

And each following `# stratis pool list`
```
Execution failure caused by:
Could not get owner of name 'org.storage.stratis1': no such name
    which in turn caused:
Launch helper exited with unknown return code 1
```

I would expect to see the pool name with status like *OFFLINE*, *UNHEALTHY*, or other. Definitelly not all operations failing.

---

System:
  - Fedora 28
  - Stratis from official repository - version 0.5.5
---

How can I recover Stratis from this? Reconnecting the drive didn't change anything. I have no problem clearing everything, it was just for testing of the capabilities.

**Comment by agrover** [comment]
See #1121 for exporting pool state info.

In addition to the D-Bus error message, you also raise the issue of how Stratis should handle blockdev removal, either when it means the whole pool is gone, or if some blockdev members of the pool remain. I've opened #1197 to track this.

**Comment by mulkieran** [comment]
I would like to close this, since I think that the #1121 and #1197 cover the problems here. I don't see any additional CLI issues.
