### ISSUE TITLE
Handling unexpected blockdev removal

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1197]
As mentioned in #1195, we should probably change the state of the pool and possibly perform some cleanup actions when this happens.

Things that might affect what Stratis does are: 1) Were any of the pool's filesystems mounted at the time? and 2) Did the removal result in a partial pool (i.e. remaining members of the now-incomplete pool are still present on the system) or complete removal, where no part of the pool remains?

**Comment by mulkieran** [comment]
From #1195 it seems clear that calling GetManagedObjects brought stratisd down. It would be nice to know why that is.

**Comment by tasleson** [comment]
I just did a test with master (47234e249c5e743339c7ddfed3d112bfa9deac7b).  I created a pool on a usb drive, created a fs and mounted it.  When I yank the jump drive out nothing apparent happens until I run the stratis cli.  When I do that stratisd panics:

```
thread 'main' panicked at 'Kernel must return at least 8 values from thin pool status', /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/devicemapper-0.26.1/src/thinpooldev.rs:488:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
             at /builddir/build/BUILD/rustc-1.32.0-src/src/libstd/panicking.rs:425
   6: devicemapper::thinpooldev::ThinPoolDev::status
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/devicemapper-0.26.1/src/thinpooldev.rs:488
   7: libstratis::engine::strat_engine::thinpool::thinpool::ThinPool::total_physical_used
             at src/engine/strat_engine/thinpool/thinpool.rs:795
   8: <libstratis::engine::strat_engine::pool::StratPool as libstratis::engine::engine::Pool>::total_physical_used
             at src/engine/strat_engine/pool.rs:391
   9: libstratis::dbus_api::pool::get_pool_total_physical_used::get_used
             at src/dbus_api/pool.rs:344
  10: core::ops::function::Fn::call
             at /builddir/build/BUILD/rustc-1.32.0-src/src/libcore/ops/function.rs:78
  11: libstratis::dbus_api::pool::get_pool_property
             at src/dbus_api/pool.rs:324
  12: libstratis::dbus_api::pool::get_pool_total_physical_used
             at src/dbus_api/pool.rs:349
  13: core::ops::function::Fn::call
             at /builddir/build/BUILD/rustc-1.32.0-src/src/libcore/ops/function.rs:78
  14: <dbus::tree::methodtype::MTFn<D> as dbus::tree::methodtype::MethodType<D>>::call_getprop
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/methodtype.rs:145
  15: <dbus::tree::leaves::Property<M, D>>::get_as_variant::{{closure}}
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:292
  16: dbus::arg::IterAppend::append_container
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
  17: dbus::arg::IterAppend::append_variant
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:114
  18: <dbus::tree::leaves::Property<M, D>>::get_as_variant
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:291
  19: dbus::tree::leaves::prop_append_dict::{{closure}}::{{closure}}
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:206
  20: dbus::arg::IterAppend::append_container
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
  21: dbus::arg::IterAppend::append_dict_entry
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:145
  22: dbus::tree::leaves::prop_append_dict::{{closure}}
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:204
  23: dbus::arg::IterAppend::append_container
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
  24: dbus::arg::IterAppend::append_dict
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:157
  25: dbus::tree::leaves::prop_append_dict
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:200
  26: <dbus::tree::objectpath::ObjectPath<M, D>>::get_managed_objects::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:229
  27: dbus::arg::IterAppend::append_container
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
  28: dbus::arg::IterAppend::append_dict_entry
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:145
  29: <dbus::tree::objectpath::ObjectPath<M, D>>::get_managed_objects::{{closure}}::{{closure}}::{{closure}}
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:227
  30: dbus::arg::IterAppend::append_container
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
  31: dbus::arg::IterAppend::append_dict
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:157
  32: <dbus::tree::objectpath::ObjectPath<M, D>>::get_managed_objects::{{closure}}::{{closure}}
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:224
  33: dbus::arg::IterAppend::append_container
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
  34: dbus::arg::IterAppend::append_dict_entry
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:145
  35: <dbus::tree::objectpath::ObjectPath<M, D>>::get_managed_objects::{{closure}}
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:222
  36: dbus::arg::IterAppend::append_container
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
  37: dbus::arg::IterAppend::append_dict
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:157
  38: <dbus::tree::objectpath::ObjectPath<M, D>>::get_managed_objects
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:220
  39: <dbus::tree::objectpath::ObjectPath<M, D>>::object_manager::{{closure}}::{{closure}}
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:282
  40: <dbus::tree::methodtype::MTFn<D> as dbus::tree::methodtype::MethodType<D>>::call_method
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/methodtype.rs:149
  41: <dbus::tree::leaves::Method<M, D>>::call
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:66
  42: <dbus::tree::objectpath::ObjectPath<M, D>>::handle
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:247
  43: <dbus::tree::objectpath::Tree<M, D>>::handle::{{closure}}::{{closure}}
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:397
  44: <core::option::Option<T>>::map
             at /builddir/build/BUILD/rustc-1.32.0-src/src/libcore/option.rs:424
  45: <dbus::tree::objectpath::Tree<M, D>>::handle::{{closure}}
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:397
  46: <core::option::Option<T>>::and_then
             at /builddir/build/BUILD/rustc-1.32.0-src/src/libcore/option.rs:632
  47: <dbus::tree::objectpath::Tree<M, D>>::handle
             at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:397
  48: libstratis::dbus_api::api::DbusConnectionData::handle
             at src/dbus_api/api.rs:265
  49: stratisd::MaybeDbusSupport::process
             at src/bin/stratisd.rs:355
  50: stratisd::run
             at src/bin/stratisd.rs:628
  51: stratisd::main
             at src/bin/stratisd.rs:659
  52: std::rt::lang_start::{{closure}}
             at /builddir/build/BUILD/rustc-1.32.0-src/src/libstd/rt.rs:74
  53: std::panicking::try::do_call
  54: __rust_maybe_catch_panic
  55: std::rt::lang_start_internal
  56: std::rt::lang_start
             at /builddir/build/BUILD/rustc-1.32.0-src/src/libstd/rt.rs:74
  57: main
  58: __libc_start_main
  59: _start
```

Cleanup afterwards:
* unmount fs
* dmsetup remove_all

**Comment by tasleson** [comment]
When the device is missing, you can run `dmsetup ls` and you get the same output we did before we yanked the device out.

```
[root@stratis-dev stratisd]# dmsetup ls
stratis-1-313789a0e88c4fc7a04d696c0cf0422c-thin-fs-f06e725927ff480d908328e0bcd87f7a	(253:5)
stratis-1-private-313789a0e88c4fc7a04d696c0cf0422c-thinpool-pool	(253:3)
stratis-1-private-313789a0e88c4fc7a04d696c0cf0422c-flex-mdv	(253:4)
stratis-1-private-313789a0e88c4fc7a04d696c0cf0422c-flex-thindata	(253:2)
stratis-1-private-313789a0e88c4fc7a04d696c0cf0422c-flex-thinmeta	(253:1)
stratis-1-private-313789a0e88c4fc7a04d696c0cf0422c-physical-originsub	(253:0)
[root@stratis-dev stratisd]# /root/stratis pool list
Execution failure caused by:
Message recipient disconnected from message bus without replying
    which in turn caused:
Error while invoking method "GetManagedObjects" belonging to interface "org.freedesktop.DBus.ObjectManager" with arguments ()
[root@stratis-dev stratisd]# dmsetup ls
stratis-1-313789a0e88c4fc7a04d696c0cf0422c-thin-fs-f06e725927ff480d908328e0bcd87f7a	(253:5)
stratis-1-private-313789a0e88c4fc7a04d696c0cf0422c-thinpool-pool	(253:3)
stratis-1-private-313789a0e88c4fc7a04d696c0cf0422c-flex-mdv	(253:4)
stratis-1-private-313789a0e88c4fc7a04d696c0cf0422c-flex-thindata	(253:2)
stratis-1-private-313789a0e88c4fc7a04d696c0cf0422c-flex-thinmeta	(253:1)
stratis-1-private-313789a0e88c4fc7a04d696c0cf0422c-physical-originsub	(253:0)
```

**Comment by tasleson** [comment]
When this happens the most simplistic thing would be
 1. Unmount any filesystems that belong to the pool (we may not be able too)
 2. Remove all the device mapper table entries for the file systems and the pool (Can't do if 1 isn't complete)

We could possibly be smart about it and only tear down those things affected by the disk be gone, but at the moment with the greedy algorithm we are using all the devices, thus they are all in use and are required for the pool to be operational.  If we have lazy allocation and the disk is one that wasn't being used, we could leave the pool and filesystems up.

**Comment by mulkieran** [comment]
> I just did a test with master ([47234e2](https://github.com/stratis-storage/stratisd/commit/47234e249c5e743339c7ddfed3d112bfa9deac7b)). I created a pool on a usb drive, created a fs and mounted it. When I yank the jump drive out nothing apparent happens until I run the stratis cli. When I do that stratisd panics:
> 
> ```
> thread 'main' panicked at 'Kernel must return at least 8 values from thin pool status', /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/devicemapper-0.26.1/src/thinpooldev.rs:488:9
> stack backtrace:
>    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
>    1: std::sys_common::backtrace::print
>    2: std::panicking::default_hook::{{closure}}
>    3: std::panicking::default_hook
>    4: std::panicking::rust_panic_with_hook
>    5: std::panicking::begin_panic
>              at /builddir/build/BUILD/rustc-1.32.0-src/src/libstd/panicking.rs:425
>    6: devicemapper::thinpooldev::ThinPoolDev::status
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/devicemapper-0.26.1/src/thinpooldev.rs:488
>    7: libstratis::engine::strat_engine::thinpool::thinpool::ThinPool::total_physical_used
>              at src/engine/strat_engine/thinpool/thinpool.rs:795
>    8: <libstratis::engine::strat_engine::pool::StratPool as libstratis::engine::engine::Pool>::total_physical_used
>              at src/engine/strat_engine/pool.rs:391
>    9: libstratis::dbus_api::pool::get_pool_total_physical_used::get_used
>              at src/dbus_api/pool.rs:344
>   10: core::ops::function::Fn::call
>              at /builddir/build/BUILD/rustc-1.32.0-src/src/libcore/ops/function.rs:78
>   11: libstratis::dbus_api::pool::get_pool_property
>              at src/dbus_api/pool.rs:324
>   12: libstratis::dbus_api::pool::get_pool_total_physical_used
>              at src/dbus_api/pool.rs:349
>   13: core::ops::function::Fn::call
>              at /builddir/build/BUILD/rustc-1.32.0-src/src/libcore/ops/function.rs:78
>   14: <dbus::tree::methodtype::MTFn<D> as dbus::tree::methodtype::MethodType<D>>::call_getprop
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/methodtype.rs:145
>   15: <dbus::tree::leaves::Property<M, D>>::get_as_variant::{{closure}}
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:292
>   16: dbus::arg::IterAppend::append_container
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
>   17: dbus::arg::IterAppend::append_variant
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:114
>   18: <dbus::tree::leaves::Property<M, D>>::get_as_variant
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:291
>   19: dbus::tree::leaves::prop_append_dict::{{closure}}::{{closure}}
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:206
>   20: dbus::arg::IterAppend::append_container
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
>   21: dbus::arg::IterAppend::append_dict_entry
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:145
>   22: dbus::tree::leaves::prop_append_dict::{{closure}}
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:204
>   23: dbus::arg::IterAppend::append_container
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
>   24: dbus::arg::IterAppend::append_dict
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:157
>   25: dbus::tree::leaves::prop_append_dict
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:200
>   26: <dbus::tree::objectpath::ObjectPath<M, D>>::get_managed_objects::{{closure}}::{{closure}}::{{closure}}::{{closure}}
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:229
>   27: dbus::arg::IterAppend::append_container
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
>   28: dbus::arg::IterAppend::append_dict_entry
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:145
>   29: <dbus::tree::objectpath::ObjectPath<M, D>>::get_managed_objects::{{closure}}::{{closure}}::{{closure}}
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:227
>   30: dbus::arg::IterAppend::append_container
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
>   31: dbus::arg::IterAppend::append_dict
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:157
>   32: <dbus::tree::objectpath::ObjectPath<M, D>>::get_managed_objects::{{closure}}::{{closure}}
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:224
>   33: dbus::arg::IterAppend::append_container
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
>   34: dbus::arg::IterAppend::append_dict_entry
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:145
>   35: <dbus::tree::objectpath::ObjectPath<M, D>>::get_managed_objects::{{closure}}
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:222
>   36: dbus::arg::IterAppend::append_container
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:100
>   37: dbus::arg::IterAppend::append_dict
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/arg/mod.rs:157
>   38: <dbus::tree::objectpath::ObjectPath<M, D>>::get_managed_objects
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:220
>   39: <dbus::tree::objectpath::ObjectPath<M, D>>::object_manager::{{closure}}::{{closure}}
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:282
>   40: <dbus::tree::methodtype::MTFn<D> as dbus::tree::methodtype::MethodType<D>>::call_method
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/methodtype.rs:149
>   41: <dbus::tree::leaves::Method<M, D>>::call
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/leaves.rs:66
>   42: <dbus::tree::objectpath::ObjectPath<M, D>>::handle
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:247
>   43: <dbus::tree::objectpath::Tree<M, D>>::handle::{{closure}}::{{closure}}
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:397
>   44: <core::option::Option<T>>::map
>              at /builddir/build/BUILD/rustc-1.32.0-src/src/libcore/option.rs:424
>   45: <dbus::tree::objectpath::Tree<M, D>>::handle::{{closure}}
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:397
>   46: <core::option::Option<T>>::and_then
>              at /builddir/build/BUILD/rustc-1.32.0-src/src/libcore/option.rs:632
>   47: <dbus::tree::objectpath::Tree<M, D>>::handle
>              at /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.6.4/src/tree/objectpath.rs:397
>   48: libstratis::dbus_api::api::DbusConnectionData::handle
>              at src/dbus_api/api.rs:265
>   49: stratisd::MaybeDbusSupport::process
>              at src/bin/stratisd.rs:355
>   50: stratisd::run
>              at src/bin/stratisd.rs:628
>   51: stratisd::main
>              at src/bin/stratisd.rs:659
>   52: std::rt::lang_start::{{closure}}
>              at /builddir/build/BUILD/rustc-1.32.0-src/src/libstd/rt.rs:74
>   53: std::panicking::try::do_call
>   54: __rust_maybe_catch_panic
>   55: std::rt::lang_start_internal
>   56: std::rt::lang_start
>              at /builddir/build/BUILD/rustc-1.32.0-src/src/libstd/rt.rs:74
>   57: main
>   58: __libc_start_main
>   59: _start
> ```
> 
> Cleanup afterwards:
> 
>     * unmount fs
> 
>     * dmsetup remove_all

From the stack trace we can see that this and https://github.com/stratis-storage/stratisd/pull/1211 are related. That is, if GetManagedObjects didn't require calling ioctl's on pools that have lost their devices then we wouldn't crash. This would be better, I think, but now we would have obsolete information.

**Comment by mulkieran** [comment]
We have fixed all these failures in the last release. stratisd doesn't crash and its D-Bus layer is not unresponsive when a block device is lost. We have other GitHub issues to address some of the problems or actions that might be necessary when this event occurs. This one is now out of date.
