### ISSUE TITLE
Need to think about the semantics of creating a cache automatically when pool is created

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#12]
Currently, a cache is created automatically when a pool is created.

This is tricky, because it is not clear what devices should belong to the cache.

Currenlty a cache has only properties, not methods. One of a cache's properties is its Dev. In the instance I'm looking at, I created a pool consisting of a single dev. The cache's unique dev is thus the pool's unique dev. This seems like it must be wrong.

If the cache is automatically created when the pool is created, initially, the cache will have no devices, or else it must get devices from the devices in the pool. It is not clear to me how stratis will always choose the correct devices for the cache, so the second option seems bad. This leaves the first option, with a cache with no devices. Given this possibility, stratis will have to be able to deal with the possibility of an empty cache or a cache that is way too small, such that there is no benefit.

The alternative is to make the user do the work, creating the cache and specifying the devices for the cache explicitly. This feels more desirable to me than auto-creating the cache. Since stratis presents a real API a smart client of stratis could encapsulate the creation of a pool and its cache into s single action in a reasonable way, i.e., stratis doesn't have to do so itself. This is the way I would prefer.

**Comment by agrover** [comment]
I agree, it makes sense for the user to specify which blockdevs are to be used for data and which are to be used as cache.

I think this opinion is reflected in the SW Design doc -- I think we're on the same page. Closing, but please feel free to reopen or open a new issue against the SWDD if you think there are further issues to iron out.

**Comment by mulkieran** [comment]
Ok. We can always go back to this if we need to refer to the decision we made.
