### ISSUE TITLE
Consistently failing first two tests on Jenkins, succeeding w/ the remainder

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1209]
The tests are:

```
test engine::strat_engine::backstore::backstore::tests::real_test_add_cache_devs ... FAILED
test engine::strat_engine::backstore::backstore::tests::real_test_request ... FAILED
```

occurrences are:
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/2006/
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/2005/
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/2002/
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/2001/
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/2000/
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/1998/
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/1996/
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/1993/
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/1991/
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/1990/
https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/1987/

It looks like there weren't any occcurrences of this particular problem before then, date is Sep 19 7:52:09 PM. All occurrences are on fedora-server-1. The previous use of fedora-server-1 was https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd/1975/, which failed on all tests due to repeated failures in the test infrastructure.

I think we should just take jenkins-server-1 out of circulation and try to figure out what is wrong with it, in order to proceed w/ regular development.

NOTE that somewhere in this sequence of identical failures, simply rebooting jenkins-server-1 has been tried and it did not help.

**Comment by trgill** [comment]
@mulkieran Ok - fedora-server-1 is offline.

The config of that system is close to fedora-server-[2,3].  Except they have different disk counts.

fedora-server-1 :  5 disks
fedroa-server-2 : 10 disks
fedora-server-3 : 15 disks

I typically run dnf update on them at the start of each week.  It is possible we pulled in a change that is causing issues.

**Comment by agrover** [comment]
#1212 is to blame for the first test.

**Comment by mulkieran** [comment]
Closing. This is really just a precursor to #1212.
