### ISSUE TITLE
dm-cache regression in kernel 4.18 (relnote-1.0)

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1212]
see #1207.

This passes with 4.17.19-200.fc28.x86_64 but this branch (and v0.9.0 and master) fail on 4.18.8-200.fc28.x86_64, with this in dmesg:
```
[   95.754178] device-mapper: cache metadata: dm_array_cursor_next for hint failed
[   95.754181] device-mapper: cache: 253:3: could not load cache mappings
[   95.754183] device-mapper: cache: 253:3: metadata operation 'dm_cache_load_mappings' failed: error = -61
[   95.754184] device-mapper: cache: 253:3: aborting current metadata transaction
[   95.758512] device-mapper: cache: 253:3: switching cache to read-only mode
[   95.758513] device-mapper: table: 253:3: cache: preresume failed, error = -61
```
To reproduce:
1. Configure 4 blockdevs in tests/test_config.json
1. Run `RUST_BACKTRACE=1 cargo test real_test_add_cache_devs -- --nocapture`

**Comment by mulkieran** [comment]
I guess this is mostly me since I'm trying to find a simple but accurate reproducer.

**Comment by mulkieran** [comment]
Well, there's a fix for the problem in DM that it detected, and I didn't need a reproducer, so we should call this in progress and watch the fix.
