### ISSUE TITLE
Stabilize D-Bus API

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1218]
Based on discussion in #1191, let's not declare API as stable in 1.0, so we have some more time to make sure we're happy with it.

**Comment by mulkieran** [comment]
I am still in favor of making the D-Bus properties be as inexpensive and safe to calculate as possible.

**Comment by mulkieran** [comment]
Closed in favor of: https://github.com/stratis-storage/project/issues/52.
