### ISSUE TITLE
Need to use a unique ID for devs and cache devs

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#122]
Using the user supplied path of a dev is going to cause problems.

**Comment by mulkieran** [comment]
This is absolutely true, because we need a unique id in order to reconstruct the position of the devices wrt. the layers above. But it's not part of the D-Bus API redesign, it goes quite a bit deeper.

**Comment by mulkieran** [comment]
And, we are doing it, because the BDA's StaticHeader object contains the device's UUID.
