### ISSUE TITLE
Investigate using profile sections to allow us to test configurations closer to what we ship

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1223]
Today we currently run all CI test using debug binaries.  We have seen that some operations like `write_sectors` can take 40+ seconds vs. ~1 second for release builds.  Because of the extreme differences in execution speed we may be missing issue because of different timings.  However, this can be helpful in some cases too.  Some checks like overflow are not checked by default in release builds, thus testing entirely with release code is sub-optimal too.   Ideally we should construct the CI infrastructure to rotate through various settings to find issues while testing what we ultimately ship.

Ref. https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections

Previous change: https://github.com/stratis-storage/stratisd/pull/1216

**Comment by mulkieran** [comment]
We routinely test our release configurations when running the tests in the testing repo, since we run those tests against installed packages, which are always release rather than debug builds. We likely won't do more unless specifically motivated by a suprising failure, closing.
