### ISSUE TITLE
Enhance metadata version tracking

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1228]
Currently we only have on version number for all three separate version. But, in future, we may have to have new versions. Right now, because we have a unique version, returning an error if the data that is read does not have that version is quite sensible. Later, if there are multiple version numbers, it will be necessary to show more finesse.

**Comment by agrover** [comment]
This is a problem that doesn't exist yet, and who knows, may never exist. Let's wait to open this issue until it *is* an issue.
