### ISSUE TITLE
Last chance to change units for size properties

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1243]
Right now they are all in Sectors or Bytes. Should they all be Bytes...or are we certain that the ones that are Sectors will always require or have only that amount of precision?

Recall that the CLI can _display_ the values however it wants.

Ones of interest currently exposed:
* BlockDev
  - physical size (Sectors)
* Filesystem
   - used (Bytes)
* Pool
   - total physical used (Sectors)
   - total physical size (Sectors)

**Comment by agrover** [comment]
I'm fine with this. If anything, I'd change filesystem.used to sectors, for consistency.

**Comment by jbaublitz** [comment]
@mulkieran Is your concern with `Sectors` that we could theoretically have different sector sizes at some point? If that's the concern, I'm on board with keeping that open as a possibility and changing to `Bytes`.

If not, what is the concern with precision? I don't think it's possible to run into an issue with anything more granular than sectors if we only allow sectors of the same size simply because you can't really have part of a sector to my knowledge.

**Comment by mulkieran** [comment]
Ok, we decided in standup that all sizes will be in bytes now (and that work can be added onto existing PRs for https://github.com/stratis-storage/projec.t/issues/52.

**Comment by jbaublitz** [comment]
@mulkieran I've played around with this a bit, and my recommendation is that we use sectors internally and convert to bytes right before sending these properties over the DBus. I think this makes the most sense as number of sectors is an important construct in stratisd and this would potentially break some things if we change all of the `.size()` methods to move away from returning `Sectors`. If we only change it at the top level of the `Engine` trait, some of the internal parts of stratisd use some of the methods that calculate size in hard to predict ways. I think leaving `Filesystem::used()` as `Bytes` makes sense from a contextual perspective, and we'll simply convert all of the sector return values from `.size()` calls to bytes right before sending them to the user. How does that sound?

**Comment by mulkieran** [comment]
I think that is the most reasonable thing to do at this time. We can adjust the internal representation if and when we need to. For right now, just making sure that all sizes sent across the D-Bus by the daemon represent bytes is what we're after.

**Comment by jbaublitz** [comment]
Hm, we seem to have a problem. When we convert to bytes using the `.bytes()` method in devicemapper for default pool size, multiplication by `SECTOR_SIZE` overflows the `u64` and stratisd panics. How do we want to address this?

**Comment by jbaublitz** [comment]
I see a few options here, but my guess is we should either switch to a different granularity or increase the representation size of units in devicemapper-rs to `u128`. I'm going to work on a preliminary PR for `u128` just to get an idea of how much work this would require.

**Comment by mulkieran** [comment]
@jbaublitz: Yes, should be a one-liner in ```range_macros.rs```. Do you have definite information on when the 128bit integers became available in Rust?

**Comment by jbaublitz** [comment]
@mulkieran Yes, I found that section but it requires many other devicemapper changes to have compatible operations between arguments passed in elsewhere as `u64`s. Still trying to see the scope of how much this will break.

**Comment by mulkieran** [comment]
Whoops! Yes, I can see that might be a problem. It still seems like the best way to go, though.

**Comment by mulkieran** [comment]
@jbaublitz Please resume work on this, but do it the hacky way, i.e., compute the value in bytes somewhere very close to the D-Bus layer.

**Comment by jbaublitz** [comment]
@mulkieran I can do that but just want to note that this will also require a PR on the stratis-cli side. Does that work?
