### ISSUE TITLE
Expose a way to tear down a pool or all pools

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1248]
Our testing is currently using a brute-force method to remove all DM devices after each test, which sometimes fails. It would be better if there was a command to give stratisd to tear down DM devices, since stratisd actually knows the DM layout tree, and can tear them down in an order that will succeed.

**Comment by agrover** [comment]
From #1248, some additional things to consider:

**Check that no filesystems are mounted in ThinPool::teardown()**

The thinpool will not be able to be torn down if still in use, i.e. because a filesystem is mounted. Currently, the code will return an error in this case, but still have possibly torn down some filesystems, leaving the pool in an inconsistent state.

This function should check that nothing is mounted, and return an error if so. However this exposes a [TOCTOU](https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use) race, so it should *also* reconstitute torn-down thindevs if after the check it still encounters an error while tearing one down.

**Comment by mulkieran** [comment]
Can we postpone or close this, since the #1323 has been closed?
