### ISSUE TITLE
Allow named (e.g. /dev/stratis/<pool>/filesystem) links in fstab

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1258]
Getting the fs uuid from blkid and putting that in fstab works fine. Why doesn't using /dev/stratis? It's good that there's a workaround but it really would be great if this worked -- sometimes using uuids isn't the best choice. @tasleson what do you think? And why is systemd -- I think we can say this is because of systemd -- treating these differently?

**Comment by tasleson** [comment]
My initial thought is that the symlink `/dev/stratis/<pool name>/<fs name>` is not in the udev db and systemd and the fstab support is likely working off of  what is generated from the udev rules files.

**Comment by agrover** [comment]
Is this doable in short order, for 1.0.1, perhaps?

**Comment by agrover** [comment]
I looked at this some this weekend, it was really bugging me that I didn't understand what was going on inside systemd.

**Notes**

can't use /dev/stratis/pool/fsname in fstab

because: systemd creates a .mount unit (see man systemd.mount) for each entry (see man systemd-fstab-generator), and that depends on a .device unit (see man systemd.device)

.device unit doesn't exist so .mount times out

why doesn't .device unit exist? because systemd automatically creates .device units based on udev block devices and aliases, and udev knows nothing of /dev/stratis aliases, so no .device exists for each of them

solution 1:

• manually create a .device for each link in /dev/stratis (in /etc/systemd/system?)
• fstab-generator will create a dependency from the .mount to the .device, which will be present
• change stratisd to create devnodes instead of links, since .mount "What=" cannot reference a symlink

solution 2:

• add a udev rule for stratis devices
• ...and have udev set up the /dev/stratis links?
• systemd will automatically create .device and make .mount depend on it
• problem: udev script doesn't know poolname or fsname of new device, only stratisd does

solution 3:

• problem only arises because systemd assumes it owns /dev, so anything in there it feels it needs to make a .device dependency for
• Instead, create /stratis/poolname/fsname .
• this is actually akin to what zfs does, see 
• a one line fix

**how to test w/o rebooting**

1. make change to fstab
1. systemctl daemon-reload (to reparse fstab/regen units etc)
1. systemctl start root-mnt.mount (e.g. if fstab entry mounted on `/root/mnt`) will timeout (90 sec) if bad, finish quickly if good.
1. `systemctl status root-mnt.mount` shows name of generated .device unit it depends on. Also, `systemctl show root-mnt.mount` gives much info.

**Comment by tasleson** [comment]
@agrover I vote for solution 3

**Comment by tasleson** [comment]
Fixed with https://github.com/stratis-storage/stratisd/pull/1279

**Comment by cgwalters** [comment]
Personally in `/etc/fstab` I tend to use `UUID=<uuid>` as the source line.  I think if Stratis encouraged that, it breaks the hard dependency here because systemd will just wait for a device with the matching UUID to appear, and Stratis can provide that however it wants.

**Comment by cgwalters** [comment]
OK sorry, the original issue description talks about wanting a not-UUID path.

So, `systemd-fstab-generator` is Free Software; it can be improved to handle Stratis better.  One thing we could do is have it defer generating mount units for fstab entries of a certain form, and stratis could ship its own `stratis-fstab-generator` which created `.mount` units however it wanted.
