### ISSUE TITLE
Limit what we allow in pool names & filesystem names

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1263]
``` bash
# stratis pool create "../../whats_up" /dev/sdf
# stratis filesystem create "../../whats_up" fs1
# ls -l /whats_up/*
lrwxrwxrwx. 1 root root 9 Oct  5 14:48 /whats_up/fs1 -> /dev/dm-5
# stratis filesystem create "../../whats_up" "../../whats_up"
```

Resultant error from last command above
```
WARN libstratis::engine::devlinks: unable to create symlink for "/dev/dm-6" -> "/dev/stratis/../../whats_up/../../whats_up", reason Os { code: 17, kind: AlreadyExists, message: "File exists" }
```

**Comment by tasleson** [comment]
Don't make a filesystem with the name `"/dev/sdb"`, when the pool is located on `/dev/sdb`, bad things happen.

**Comment by agrover** [comment]
Can I make a filesystem called :smiley: ?

:smiley:

**Comment by tasleson** [comment]
>  Can I make a filesystem called smiley ?

@agrover  **Yep**

``` bash
# stratis pool create yes_you_can /dev/sdf
# stratis filesystem create yes_you_can ☺
# /root/stratis filesystem list
Pool Name    Name  Used     Created            Device                      
yes_you_can  ☺     546 MiB  Oct 05 2018 16:24  /dev/stratis/yes_you_can/☺ 
```

Note: type <cntrl + shift + u> then 263A in your terminal to create the UTF-8 :smile:

**Comment by agrover** [comment]
I read https://stackoverflow.com/questions/457994/what-characters-should-be-restricted-from-a-unix-file-name but am left without a definitive solution. I'd like people to be able to name filesystems using non-Latin charsets.

Should we be looking at a list of approved chars, or a list of forbidden chars?

**Comment by tasleson** [comment]
> Should we be looking at a list of approved chars, or a list of forbidden chars?

Normally you only want to white list things, not black list.  However, I'm not sure about this one.

**Comment by trgill** [comment]
I'm working on #1275 to address at least part of this issue
