### ISSUE TITLE
Pool::total_physical_used is on its way to becoming unhelpful

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1267]
When we add another layer, say VDO, we may find ourselves in the disconcerting situation where total_physical_used is greater than total physical size the way we calculate it.

I think we would be better off going for a stabler and more accurate if not as precise value and simply returning the result of ```DataTier::allocated()``` for this value. This can overestimate, because some of the segments allocated may not actually be being used. But it can't actually exceed the total physical size, by definition.

Before there was lazy allocation from the data tier this suggestion wouldn't have made any sense. But now that there is lazy allocation, I think it is really the best suggestion.

I also think that these two values should be supplemented with another pair of values, which would be specific to the thin pool and not to the backstore. Again, with the VDO example, we can imagine a total thin pool size which is very large, and a value for used which is a lot less than the thin pool size, but still a lot larger than the total physical size.

**Comment by mulkieran** [comment]
I started to think about this problem while trying to figure out how to test #1266 .

**Comment by mulkieran** [comment]
Removing from project, in favor of parent issue.

**Comment by jbaublitz** [comment]
This will be resolved by #1662

**Comment by mulkieran** [comment]
We can close this. We decided that we were in a position to maintain this value accurately, so we will do that. The alternative suggestions are ones we will support naturally as the design and implementation proceeds.
