### ISSUE TITLE
writeback errors with async IO on 15 or more filesystems

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#1310]
The problem is more frequent with very fast storage (NVME or SSD) but can be seen with more typical storage also.

If I start IO on 15 filesystems in the same pool at the same time - I typically see:

```
> Nov 7 13:49] device-mapper: thin: 253:4: reached low water mark for data device: sending event.
> [ +10.744954] device-mapper: thin: 253:4: switching pool to out-of-data-space (error IO) mode
> [  +0.031216] xfs_destroy_ioend: 459 callbacks suppressed
> [  +0.000003] XFS (dm-17): writeback error on sector 1841944
> [  +0.003728] XFS (dm-17): writeback error on sector 1842000
> [  +0.000037] XFS (dm-17): writeback error on sector 1842040
> [  +0.000046] XFS (dm-17): writeback error on sector 1842072
> [  +0.000035] XFS (dm-17): writeback error on sector 1842112
> [  +0.000041] XFS (dm-17): writeback error on sector 1842144
> [  +0.000039] XFS (dm-17): writeback error on sector 1842184
> [  +0.000031] XFS (dm-17): writeback error on sector 1842224
> [  +0.000041] XFS (dm-17): writeback error on sector 1842256
> [  +0.000033] XFS (dm-17): writeback error on sector 1842296
> [  +0.433481] device-mapper: thin: 253:4: switching pool to write mode
> [  +0.096364] XFS (dm-31): Ending clean mount
> [  +0.315276] XFS (dm-33): Mounting V5 Filesystem
```

**Comment by trgill** [comment]
FIO config file: 

```
[sequential-write]
rw=write
size=6G
direct=0
numjobs=5
group_reporting
name=sequential-write-buffered
bs=4k
runtime=10
```

**Comment by agrover** [comment]
throwing out some ideas:
1. use a high throttle value on data dev to smooth out write spikes to an amount our existing thresholds can handle
1. revisit using queue_if_no_space. Maybe dealing with the issues around that is actually easier than this problem? :sweat_smile: 
1. use DM stats to scale grow_size and data_lowater on max values seen as the pool is in operation
1. use different values based on if data tier consists of disk, flash, or nvme devices
1. just simply further increase grow_size and data_lowater constants beyond what we've already increased them to

**Comment by trgill** [comment]
Closing this issue.  The behaviour can be explained by the following:

fio will not report errors on a dirty close by default:

       end_fsync=bool
              If true, fsync(2) file contents when a write stage has completed.  Default: false.

       fsync_on_close=bool
              If true, fio will fsync(2) a dirty file on close. This differs from end_fsync in that it will happen on every file close, not just at the end of the job. Default: false.

error_if_no_space will not immediately error IO when the data space is full.  DM waits for no_space_timeout before returning an error.
