### ISSUE TITLE
DRY: Don't repeat yourself

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1327]
`stratisd` has duplicate code especially in test cases, but there is some in production code too.  These are some examples which have the greatest number of lines of copy and pasted code.

Found 14 duplicate lines in the following files:
 Between lines 33 and 46 in stratisd/src/engine/strat_engine/backstore/data_tier.rs
 Between lines 56 and 69 in stratisd/src/engine/strat_engine/backstore/cache_tier.rs
``` rust
        let uuid_to_devno = block_mgr.uuid_to_devno();        let mapper = |ld: &BaseDevSave| -> StratisResult<BlkDevSegment> {
            let parent = ld.parent;
            let device = uuid_to_devno(parent).ok_or_else(|| {
                StratisError::Engine(
                    ErrorEnum::NotFound,
                    format!("missing device for UUUD {:?}", &parent),
                )
            })?;
            Ok(BlkDevSegment::new(
                parent,
                Segment::new(device, ld.start, ld.length),
            ))
        };
```

Found 12 duplicate lines in the following files:
 Between lines 230 and 243 in stratisd/src/dbus_api/pool.rs
 Between lines 83 and 95 in stratisd/src/dbus_api/pool.rs
```rust 
                   )                })
                .collect::<Vec<_>>();

            return_message.append3(return_value, msg_code_ok(), msg_string_ok())
        }
        Err(err) => {
            let (rc, rs) = engine_to_dbus_err_tuple(&err);
            return_message.append3(default_return, rc, rs)
        }
    };
    Ok(vec![msg])
}
```

Found 12 duplicate lines in the following files:
 Between lines 153 and 165 in stratisd/src/engine/strat_engine/thinpool/thinpool.rs
 Between lines 123 and 135 in stratisd/src/engine/strat_engine/backstore/blockdevmgr.rs
```rust
            true        } else {
            false
        }
    };

    if coalesced {
        segments.extend_from_slice(&right[1..]);
    } else {
        segments.extend_from_slice(right);
    }
    segments
}
```

Found 10 duplicate lines in the following files:
 Between lines 113 and 122 in stratisd/src/engine/strat_engine/thinpool/thinpool.rs
 Between lines 150 and 160 in stratisd/src/engine/strat_engine/backstore/blockdevmgr.rs
```rust 
       let line = TargetLine::new(            logical_start_offset,
            length,
            LinearDevTargetParams::Linear(params),
        );
        table.push(line);
        logical_start_offset += length;
    }

    table
}
```

Found 9 duplicate lines in the following files:
 Between lines 139 and 147 in stratisd/src/dbus_api/pool.rs
 Between lines 87 and 95 in stratisd/src/dbus_api/pool.rs
 Between lines 234 and 243 in stratisd/src/dbus_api/pool.rs
```rust
            return_message.append3(return_value, msg_code_ok(), msg_string_ok())        }
        Err(err) => {
            let (rc, rs) = engine_to_dbus_err_tuple(&err);
            return_message.append3(default_return, rc, rs)
        }
    };

    Ok(vec![msg])
}
```
Found 9 duplicate lines in the following files:
 Between lines 307 and 316 in stratisd/src/dbus_api/pool.rs
 Between lines 171 and 180 in stratisd/src/dbus_api/filesystem.rs
```rust
    let pool_uuid = pool_path        .get_data()
        .as_ref()
        .ok_or_else(|| MethodErr::failed(&format!("no data for object path {}", object_path)))?
        .uuid;

    let engine = dbus_context.engine.borrow();
    let (pool_name, pool) = engine.get_pool(pool_uuid).ok_or_else(|| {
        MethodErr::failed(&format!("no pool corresponding to uuid {}", &pool_uuid))
    })?;
```

Found 8 duplicate lines in the following files:
 Between lines 168 and 177 in stratisd/src/dbus_api/filesystem.rs
 Between lines 179 and 188 in stratisd/src/dbus_api/blockdev.rs
```rust
        ))    })?;

    let pool_uuid = pool_path
        .get_data()
        .as_ref()
        .ok_or_else(|| MethodErr::failed(&format!("no data for object path {}", object_path)))?
        .uuid;

    let engine = dbus_context.engine.borrow();
```

Found 8 duplicate lines in the following files:
 Between lines 92 and 99 in stratisd/src/engine/event.rs
 Between lines 82 and 89 in stratisd/src/engine/event.rs
```rust 
   unsafe {        INIT.call_once(|| ENGINE_LISTENER_LIST = Some(EngineListenerList::new()));
        match ENGINE_LISTENER_LIST {
            Some(ref mut ell) => ell,
            _ => panic!("ENGINE_LISTENER_LIST is None"),
        }
    }
}
```

Found 8 duplicate lines in the following files:
 Between lines 66 and 73 in stratisd/src/engine/macros.rs
 Between lines 45 and 52 in stratisd/src/engine/macros.rs
```rust 
           return Err(StratisError::Engine(                ErrorEnum::AlreadyExists,
                $new_name.into(),
            ));
        }
        old_name
    }};
}
```
Found 8 duplicate lines in the following files:
 Between lines 162 and 169 in stratisd/src/engine/strat_engine/backstore/cache_tier.rs
 Between lines 120 and 127 in stratisd/src/engine/strat_engine/backstore/cache_tier.rs
```rust  
          return Err(StratisError::Engine(                ErrorEnum::Invalid,
                format!(
                    "The size of the cache sub-device may not exceed {}",
                    MAX_CACHE_SIZE
                ),
            ));
        }
```

Found 8 duplicate lines in the following files:
 Between lines 137 and 145 in stratisd/src/engine/strat_engine/thinpool/thinpool.rs
 Between lines 105 and 113 in stratisd/src/engine/strat_engine/backstore/blockdevmgr.rs
```rust
    if left.is_empty() {        return right.to_vec();
    }
    if right.is_empty() {
        return left.to_vec();
    }

    let mut segments = Vec::with_capacity(left.len() + right.len());
    segments.extend_from_slice(left);
```

Found 8 duplicate lines in the following files:
 Between lines 552 and 559 in stratisd/src/bin/stratisd.rs
 Between lines 527 and 534 in stratisd/src/bin/stratisd.rs

```rust
                fds.extend(                    handle
                        .connection
                        .borrow()
                        .watch_fds()
                        .iter()
                        .map(|w| w.to_pollfd()),
                );
```

### An example of test code ####
Found 11 duplicate lines in the following files:
 Between lines 1401 and 1412 in stratisd/src/engine/strat_engine/thinpool/thinpool.rs
 Between lines 1508 and 1519 in stratisd/src/engine/strat_engine/thinpool/thinpool.rs
 Between lines 1554 and 1565 in stratisd/src/engine/strat_engine/thinpool/thinpool.rs
 Between lines 1613 and 1623 in stratisd/src/engine/strat_engine/thinpool/thinpool.rs
 Between lines 1725 and 1735 in stratisd/src/engine/strat_engine/thinpool/thinpool.rs
 Between lines 1955 and 1966 in stratisd/src/engine/strat_engine/thinpool/thinpool.rs
```rust  
      let pool_uuid = Uuid::new_v4();        devlinks::cleanup_devlinks(Vec::new().into_iter());
        let mut backstore = Backstore::initialize(pool_uuid, paths, MIN_MDA_SECTORS).unwrap();
        let mut pool = ThinPool::new(
            pool_uuid,
            &ThinPoolSizeParams::default(),
            DATA_BLOCK_SIZE,
            &mut backstore,
        ).unwrap();

        let pool_name = "stratis_test_pool";
        devlinks::pool_added(&pool_name);
```

**Comment by agrover** [comment]
Good to run this every so often I guess.. maybe every 6 months or yearly, just like getting a dentist checkup.

atm I don't see any red flags.

**Comment by mulkieran** [comment]
Related: https://github.com/stratis-storage/stratisd/issues/1136,

**Comment by mulkieran** [comment]
If we could incorporate use of Simian into our CI, then this could probably be made into a useful alerter for new duplicates. But it doesn't look to me like the license readily allows it. We can't take action on this; we already avoid duplication fairly well in our source, wherever we can figure out how.
