### ISSUE TITLE
Non-greedy thinpool allocation

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1332]
#1331 implements greedy allocation for thinpool i.e. thinpool takes all available space available in backstore.

This is a short-term measure to ensure data integrity, with the intention to re-enable non-greedy allocation in the future. Non-greedy is desirable in order to allow for potential growth in other flex-layer devices (e.g. the MDV) and also to allow unused block devices to eventually be removable.

**Comment by mulkieran** [comment]
Obsolete, being addressed by #2814
