### ISSUE TITLE
Passing Paths to engine methods to identify devices is probably a mistake

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#135]
We should broaden type to &str and sort out what th &str means internally.

**Comment by agrover** [comment]
What are the shortcomings of Path?

**Comment by agrover** [comment]
create_pool, {add,remove}_{block,cache}dev. Also need to worry about duplicates.

**Comment by mulkieran** [comment]
It's probably also a problem that BlockDevSave uses device nodes.

**Comment by agrover** [comment]
This needs updating based on 10.3.4 from the design doc.

**Comment by mulkieran** [comment]
At this point, we are passing device nodes in exactly two methods: ```Pool::add_blockdevs``` and ```Engine::create_pool```. These device nodes are passed on directly from the D-Bus API. Internally, the block devices are checked for duplicates by the engine, not the paths themselves, but the device numbers to which the paths correspond.

Since we do not currently remove devices, there are no other methods that directly specify devices at all.

It is not wrong to use device nodes in this fashion, but it is not at all certain that that is the _only way_ that devices should be specified to the D-Bus API and then to the engine. It seems like we ought to have a bigger type that allows more ways of specifying devices, and the ability to resolve these specifications to their device nodes so that we can then initialize them, etc.

**Comment by agrover** [comment]
@mulkieran can we close this, perhaps opening a fresh issue if needed?

**Comment by mulkieran** [comment]
I'll close this.
