### ISSUE TITLE
Let's split Pool state into two states (thinpool state and overall)

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1356]
overall state would just be ```Initializing```, ```Stopping```, and ```Running```.
thin pool state would just mirror the thinpool summary more or less, ```Fail```, ```ro```, ```rw``` (that's the good state), ```out of data space```.

I feel that this would make things easier for the user to understand and easier for the developer to implement.

Related: #1351.

**Comment by agrover** [comment]
For this one and for #1351, this is making me think more and more we should have the overall api-exposed state that is pretty high-level, and then we should feel free to use multiple state enums internally, but only make them visible to the user in how they affect the api-exposed state. The existence of a thinpool within the pool is an implementation detail. WDYT?

**Comment by mulkieran** [comment]
Not having a direct mapping between the internally recorded state and the state exposed on the D-Bus API is fine w/ me.

But we should be very careful what we expose on the D-Bus API. Right now, we do expose the "pool state" which is _very_ closely tied to the thin pool status. So, that we use a thin pool is currently exposed on the D-Bus API even if it shouldn't be.

**Comment by mulkieran** [comment]
A summary of states in Stratis and statuses available from devicemapper.

[states.md.txt](https://github.com/stratis-storage/stratisd/files/2691317/states.md.txt)

**Comment by mulkieran** [comment]
I think that the suggestion of making the states that we expose on the D-Bus API and the states that we use internally distinct naturally leads to the second suggestion which is to make the internal states as orthogonal as possible. That is what I am proposing in the specific case of the pool state in this issue.

I have drawn up a document showing the available devicemapper states and the existing stratisd pool states, some of which are also API states. I think it would be valuable, in the course of this effort, to draw up a document that also maps internal states or combinations of states to D-Bus exposed states.
This would probably require a table for every mapping.

**Comment by mulkieran** [comment]
I'm closing this as obsolete. We no longer export these on the D-Bus and #2106 and #2103 are addressing the internal implementation.
