### ISSUE TITLE
Investigate if dbus-rs emits InterfaceChanged signals properly

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#1377]
Even if our objects do not dynamically change interfaces, InterfaceAdded is the signal that should be emitted when an object is added to the set of object available via GetManagedObjects, and vice-versa for InterfaceRemoved.

~~We discussed using multiple interfaces to indicate a pool gaining or losing capabilities based on its state. In order to work, changing interfaces should (automatically) cause InterfaceChanged events to be generated. We need to verify this is the case before going much further in investigating this as part of our stable API plans.~~ We are not yet in a situation where we need to change interfaces on our objects.

**Comment by agrover** [comment]
Correction: The signals are InterfacesAdded and InterfacesRemoved.

**Comment by agrover** [comment]
I see a little on the client side of dbus-rs maybe, but nothing on the server side to generate these signals. There are some discouraging comments above `fn object_manager()` around line 651 in methoddisp.rs.

**Comment by mulkieran** [comment]
@jbaublitz it's all yours.
