### ISSUE TITLE
Expose stratisd version via DBus

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#138]
I'm thinking a read-only string property on our top-level service interface?

**Comment by mulkieran** [comment]
me, too.

**Comment by mulkieran** [comment]
This should make one more test pass.

**Comment by mulkieran** [comment]
```crate_version``` gets a compile-time value from the environment. Is that adequate for dbus?

**Comment by mulkieran** [comment]
No point in working on this until #153 gets figured out.

**Comment by mulkieran** [comment]
Resolved by #200 .
