### ISSUE TITLE
Strange warning in log on filling up volume.

### ISSUE THREAD

**Issue by ingothierack** [stratis-storage/stratisd#1383]
Starting using now stratis (on fedora 29 server latest updates)

created a new pool on a md-device(raid5 with 3 disks whit 4TB each). 
create a new filesystem and start copy over data to it.
Than i get a lot of warnings as seen below.
**Dec 22 18:09:06 nas001 stratisd[10829]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available in backstore; extended thinpool metada**

Problem or be only an warning?
I tested before lvm2 with thin-provisioning, and i saw here also the problem, the metadata fills up and can't be extended. Same here?

`Dec 22 18:09:05 nas001 kernel: device-mapper: thin: 253:6: reached low water mark for data device: sending event.
Dec 22 18:09:06 nas001 stratisd[10829]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool metadata sub-device belonging to pool 210e
b8dac6cb440993454dac6a885dae by 32768 sectors
Dec 22 18:09:06 nas001 stratisd[10829]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available in backstore; extended thinpool metada
ta sub-device belonging to pool with uuid 210eb8dac6cb440993454dac6a885dae by 0 sectors, request was 32768 sectors
Dec 22 18:09:06 nas001 stratisd[10829]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 3`

> stratis daemon version
1.0.2

**Comment by mulkieran** [comment]
Closing as obsolete. We have reworked our management of thin bock layer for stratisd 3.1.0.
