### ISSUE TITLE
StaticHeader::setup  Improve error reporting

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1443]
Note:  Taken from https://github.com/stratis-storage/stratisd/pull/1440#discussion_r259868293

```rust
fn setup<F>(f: &mut F) -> StratisResult<Option<StaticHeader>>
    where
        F: Read + Seek + SyncAll,
```
This returns an error in two situations:

 * If the metadata seems to indicate that the device is a Stratis deivce, but no well-formed signature could be found.
 * If a well-formed signature was found but an error occurred during the repair of a second, ill-formed, old, or unreadable signature.

I think it is right to return an error in the first case, but I think the second should possibly be handled differently. I think a good option is to enrich the return type to
```rust
StratisResult<Option<StaticHeader>, Option<some error thing if repair fails>>
```

Additionally, taken from: https://github.com/stratis-storage/stratisd/pull/1440#discussion_r259869237
```rust
let err_str =  "Appeared to be a Stratis device, but no valid sigblock found";
Err(StratisError::Engine(ErrorEnum::Invalid, err_str.into()))
```
Actually, better to include both errors, and improve the error messages in the errors returned from `sigblock_from_buf`.

**Comment by mulkieran** [comment]
Closing in favor of #2133, as that separates the action of reading and interpreting the signature buffers from the action of choosing and if necessary repairing.
