### ISSUE TITLE
strat_engine: add_blockdev cannot check new blockdev is not part of another pool

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#145]
We don't have access to the collection of all the pools, so we can't check for other pools that contain blockdevs with `Device` values that match the new one.

Possible solutions I can think of:
 * Read the new blockdev and see if it contains a Stratis header
 * Come up with a way for Pool to get a reference to its parent Engine, so it can do essentially the check `create_pool` does

**Comment by agrover** [comment]
Created from comments on #144

**Comment by mulkieran** [comment]
This will be true for ```add_cachedev``` as well.

**Comment by mulkieran** [comment]
What if we have two instances of stratis running at the same time, each managing separate pools? Then the only way we can know if a device belongs to another Stratis pool is by checking its metadata.

**Comment by mulkieran** [comment]
Resolved by PR #156.
