### ISSUE TITLE
Try to broaden our pre-conditions and narrow our post-conditions as much as possible

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#146]
Generally, a method is more useful to the caller if its pre-conditions are less restrictive and its post-conditions more precise.

Pre- and post-conditions are a very broad category. They can include types, but also all sorts of other conditions.

A good example in Rust of broadening a pre-condition is to prefer the type ```&str``` to ```String``` for parameters of methods.

Returning an error when it is possible for a method to succeed is a way of arbitrarily narrowing the pre-condition and so should be avoided. An obvious example is the case of a ```sort()``` method for vectors. It would clearly be a mistake to return an error if the vector argument was already sorted. The correct behavior is to return with success, regardless  of whether or not work had to be performed to get the vector into a sorted order. Other examples are not so obvious.

An example that came up recently is the ```destroy_pool``` method. By the theory above, it is best to return with success if the pool is already destroyed (analogous to the vector already being sorted). An argument for a different approach might be that it is important to alert the client to the _possibility_ of an error by returning an error value. I emphasize "possibility" because there may not have been an actually error.  Note that this argument, if applied generally, would also mean that the vector sort() method should return an error.

Is there some special dispensation or difference because this is an object being removed, not a vector being sorted? Not really. Consider the interfaces for map data structures, like Rust's own ```BTreeMap.remove()```. Does it return an error if the key is not in the map? Absolutely not. There are lots of good models to show that returning an error/raising an exception is the _wrong_ thing to do.

Why are we even asking this question in the case of ```destroy_pool()```? It seems to me that it is not the semantics of the method, but its return type, which is a bit broken. BTreeMap's remove() method has a return type which is rich enough to indicate whether or not there was something there. ```destroy_pool```'s could be enhanced to do the same.

The most basic approach is to use a boolean result, but one could also ramp up to one of the richer booleans if necessary. But, ```true``` to indicate something was actually removed and ```false``` to indicate no removal seems like a good start. How would this be useful for the calling code? Well, hypothetical code could do whatever it wanted with this extra bit of information. Our dbus code currently returns a return code and a message. The simplest thing is to return the 0 return code but expand the message to communicate something. That is not so helpful. Another thing to do is to have the dbus method take an extra boolean parameter, indicating that it wants an error return if the pool to be removed is not there. That extra bit can easily be managed in the dbus api. In the general case, this parameter should be false, but for the CLI it might be set to true...so that some sort of warning could be reported to the user. This seems like the correct break down to me.

**Comment by agrover** [comment]
If we reach agreement that this is desirable, what are the ramifications for our existing interfaces, both internally and DBus?

**Comment by agrover** [comment]
Should this go in the style guide?

**Comment by mulkieran** [comment]
Superceded by https://github.com/stratis-storage/project/issues/51. I think we can close this because it was more or less philosophical, and we are now actually doing what this issue urges as a principal.
