### ISSUE TITLE
meta allocation should look at usage compared to size

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#1462]
Currently the code looks to make sure the meta is 1/1000th of the total space in the pool, but doesn't check to make sure the usage has a margin of safety.

Some data requires more meta space (lots of small files?).  The greedy allocation algorithm doesn't leave any room for a subsequent meta expansion.

We should understand how https://github.com/stratis-storage/stratisd/issues/1456 had a meta extension fail as indicated by the log.

**Comment by mulkieran** [comment]
Being addressed by #2814
