### ISSUE TITLE
Why /stratis directory is used?

### ISSUE THREAD

**Issue by zeten30** [stratis-storage/stratisd#1478]
Hi, 

this is more a question than issue. Why we have /stratis directory - for example /stratis/mypool/testFS. Should it be somewhere in /etc, /srv../var..? 

Thanks in advance

**Comment by tasleson** [comment]
@zeten30 Full discussion is here: https://github.com/stratis-storage/stratisd/issues/1258

We initially had the symlinks in `/dev/stratis/<pool name>/<fs name>`

Excerpt from full discussion 

> can't use /dev/stratis/pool/fsname in fstab
>
> because: systemd creates a .mount unit (see man systemd.mount) for each entry (see man 
> systemd-fstab-generator), and that depends on a .device unit (see man systemd.device)
>
>.device unit doesn't exist so .mount times out
>
>why doesn't .device unit exist? because systemd automatically creates .device units based on udev block devices and aliases, and udev knows nothing of /dev/stratis aliases, so no .device exists for each of them

We selected solution 3 from the discussion which is

>solution 3:
>
>• problem only arises because systemd assumes it owns /dev, so anything in there it feels it needs to make a .device dependency for
• Instead, create /stratis/poolname/fsname .
• this is actually akin to what zfs does, see https://www.freebsd.org/doc/handbook/zfs-quickstart.html section 19.2.1
• a one line fix

**Comment by zeten30** [comment]
Make sense. Thank you. We've been covering statis during 'RHEL8 new features training' and this question appeared. I was not able to find   #1258 or I've overlooked it.
