### ISSUE TITLE
Use abstract name space unix domain socket instead of locking pid file

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1482]
Today stratisd uses a locking pid file to determine if another instance is already running.  This could be handled cleaner with the use of a unix domain socket that is using abstract name space.

ref. https://blog.petrzemek.net/2017/07/24/ensuring-that-a-linux-program-is-running-at-most-once-by-using-abstract-sockets/

**Comment by bgurney-rh** [comment]
I tried a test where I overwrote the /run/stratisd.pid file with another number, not corresponding to the PID of a running stratisd process.  (I also stopped stratisd.)

```
# echo 3141592653589793 | tee /var/run/stratisd.pid 
3141592653589793
```
After starting a new stratisd process, it starts (probably after determining that there is no stratisd PID with the value in the file), but only seems to overwrite enough bytes to contain the new PID:
```
# while true; do date; cat /var/run/stratisd.pid; sleep 1; done
Mon Jun  3 10:32:28 EDT 2019
3141592653589793
Mon Jun  3 10:32:29 EDT 2019
3141592653589793
Mon Jun  3 10:32:30 EDT 2019
3141592653589793
Mon Jun  3 10:32:32 EDT 2019
3141592653589793
Mon Jun  3 10:32:33 EDT 2019
3141592653589793
Mon Jun  3 10:32:34 EDT 2019
12365
2653589793
Mon Jun  3 10:32:35 EDT 2019
12365
2653589793
Mon Jun  3 10:32:36 EDT 2019
12365
2653589793
```

**Comment by mulkieran** [comment]
It looks like there's a latent bug in the PID reading mechanism as well. It reads the whole string available, but parses using ```s.parse::<pid_t>()```, and the ```pid_t``` type is defined as an i32. So, in the presence of larger PIDs than the standard maximum PID, the value will not be parsed properly.

**Comment by jbaublitz** [comment]
I'm going to put up a preliminary PR that we can take a look at and see if it's something we want to consider adding.

**Comment by mulkieran** [comment]
Great!

**Comment by jbaublitz** [comment]
Upon further evaluation of this method, this seems to have one particular flaw that could make this unusable. The article mentions that the socket method has no access permissions. After digging into this a bit and discussing it further, it appears that any unprivileged user can bind to the address and halt service start up for another unprivileged user with permissions only to start/stop the service. Remedying the situation would require root permissions to kill the process owned by the malicious unprivileged user. A more well-tested and secure solution seems to be creating a PID file and taking out an exclusive file lock on the PID file to prevent other stratisd processes from starting. Closing.

**Comment by jbaublitz** [comment]
Superseded by #1630.
