### ISSUE TITLE
journal filled with device-mapper: thin: Metadata device messages

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1495]
While running the udev tests I see many of the following messages in the journal.

`device-mapper: thin: Metadata device dm-1 is larger than 33292800 sectors: excess space will not be used.`

**Comment by mulkieran** [comment]
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1707461.

**Comment by gmat** [comment]
Hi, I've a broken xfs fs by this issue. It's there a way to fix it ?

**Comment by mulkieran** [comment]
> Hi, I've a broken xfs fs by this issue. It's there a way to fix it ?

Hi! Please be as specific as possible about the problem you are encountering.

**Comment by gmat** [comment]
On centos 8, one filesystem reach 10To used and go failed. Unable to mount it. Unable to repair it. 
ddrescue make a 1To image only.
Stratis has failed to create new filesystem.
Plenty of "device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be used" send to dmesg.
I suspect lvm thin metadata to get full
Please just tell me what kind of information  do you suspect and how to get it.
Thks

**Comment by mulkieran** [comment]
> On centos 8, one filesystem reach 10To used and go failed. Unable to mount it. Unable to repair it.
> ddrescue make a 1To image only.
> Stratis has failed to create new filesystem.
> Plenty of "device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be used" send to dmesg.
> I suspect lvm thin metadata to get full
> Please just tell me what kind of information do you suspect and how to get it.
> Thks

Hi! The devicemapper messages make be unconnected w/ your problem. I've filed a new issue for the problem you're experiencing: #1789. Please follow up there.

**Comment by wrigjz** [comment]
Not the only one with this issue, we created a 40Tb pool with 2 filesystems (4x 10Tb iscsi raid-6s), copied ~15TB data onto it. 

Rebooted the machine (Centos8) and while stratis daemon started ok and pool list, filesystem list all work fine we could not remount the filesystems - the message was that the superblock could not be read. Could not find anyway to repair it.

Luckily we had the original copy of the data still and so have converted from stratis to mdadm raid-0 and copying the back for a 2nd time.

A bit disappointed to say the least.

This was in the logs:

stratisd[935]: WARN libstratis::engine::strat_engine::engine: no pool set up, reason: Engine(Error, "failed to set up pool for (pool UUID: 56775cf8-503a-4314-b726-c4342a68e6cf, devnodes: /dev/sda ,/dev/sdb): reason: Engine(Invalid, \"UUIDs of devices found (2442fe33da9a4f2fb3cc14d8bc4fc825, cc43482d3db64b57b6f83a57327bed50) did not correspond with UUIDs specified in the metadata for this group of devices (cc43482d3db64b57b6f83a57327bed50, 2442fe33da9a4f2fb3cc14d8bc4fc825, 011c0ebdb3e643ef96a530290a0c771b, 5076d145091d40a2ad2053fa852daf4b)\")")

This is what was placed in the log when we tried to hand mount the filesystem

Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
st was 52606512 sectors
Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
used.
Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
st was 52606512 sectors
Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
st was 52606512 sectors
Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
used.
Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
used.
Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
st was 52606512 sectors
Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
used.
Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
st was 52606512 sectors
Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
used.
Jan 21 11:39:32 bristol kernel: attempt to access beyond end of device
Jan 21 11:39:32 bristol kernel: dm-7: rw=4096, want=17179869184, limit=2147483648
Jan 21 11:39:32 bristol kernel: XFS (dm-7): last sector read failed
Jan 21 11:39:32 bristol kernel: attempt to access beyond end of device
Jan 21 11:39:32 bristol kernel: dm-8: rw=4096, want=34359738368, limit=2147483648
Jan 21 11:39:32 bristol kernel: XFS (dm-8): last sector read failed
Jan 21 11:42:09 bristol kernel: attempt to access beyond end of device
Jan 21 11:42:09 bristol kernel: dm-8: rw=4096, want=34359738368, limit=2147483648
Jan 21 11:42:09 bristol kernel: XFS (dm-8): last sector read failed
Jan 21 11:45:00 bristol kernel: XFS (dm-6): Mounting V5 Filesystem
Jan 21 11:45:00 bristol kernel: XFS (dm-6): Ending clean mount

The XFS systems did not mount - the mount command gave a unable to read superblock error

**Comment by mulkieran** [comment]
> Not the only one with this issue, we created a 40Tb pool with 2 filesystems (4x 10Tb iscsi raid-6s), copied ~15TB data onto it.
> 
> Rebooted the machine (Centos8) and while stratis daemon started ok and pool list, filesystem list all work fine we could not remount the filesystems - the message was that the superblock could not be read. Could not find anyway to repair it.
> 
> Luckily we had the original copy of the data still and so have converted from stratis to mdadm raid-0 and copying the back for a 2nd time.
> 
> A bit disappointed to say the least.
> 
> This was in the logs:
> 
> stratisd[935]: WARN libstratis::engine::strat_engine::engine: no pool set up, reason: Engine(Error, "failed to set up pool for (pool UUID: 56775cf8-503a-4314-b726-c4342a68e6cf, devnodes: /dev/sda ,/dev/sdb): reason: Engine(Invalid, "UUIDs of devices found (2442fe33da9a4f2fb3cc14d8bc4fc825, cc43482d3db64b57b6f83a57327bed50) did not correspond with UUIDs specified in the metadata for this group of devices (cc43482d3db64b57b6f83a57327bed50, 2442fe33da9a4f2fb3cc14d8bc4fc825, 011c0ebdb3e643ef96a530290a0c771b, 5076d145091d40a2ad2053fa852daf4b)")")
> 
> This is what was placed in the log when we tried to hand mount the filesystem
> 
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
> data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
> in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
> st was 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
> Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
> used.
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
> data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
> in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
> st was 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
> data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
> in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
> st was 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
> Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
> used.
> Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
> used.
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
> data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
> in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
> st was 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
> Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
> used.
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
> data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
> in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
> st was 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
> Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
> used.
> Jan 21 11:39:32 bristol kernel: attempt to access beyond end of device
> Jan 21 11:39:32 bristol kernel: dm-7: rw=4096, want=17179869184, limit=2147483648
> Jan 21 11:39:32 bristol kernel: XFS (dm-7): last sector read failed
> Jan 21 11:39:32 bristol kernel: attempt to access beyond end of device
> Jan 21 11:39:32 bristol kernel: dm-8: rw=4096, want=34359738368, limit=2147483648
> Jan 21 11:39:32 bristol kernel: XFS (dm-8): last sector read failed
> Jan 21 11:42:09 bristol kernel: attempt to access beyond end of device
> Jan 21 11:42:09 bristol kernel: dm-8: rw=4096, want=34359738368, limit=2147483648
> Jan 21 11:42:09 bristol kernel: XFS (dm-8): last sector read failed
> Jan 21 11:45:00 bristol kernel: XFS (dm-6): Mounting V5 Filesystem
> Jan 21 11:45:00 bristol kernel: XFS (dm-6): Ending clean mount
> 
> The XFS systems did not mount - the mount command gave a unable to read superblock error



> Not the only one with this issue, we created a 40Tb pool with 2 filesystems (4x 10Tb iscsi raid-6s), copied ~15TB data onto it.
> 
> Rebooted the machine (Centos8) and while stratis daemon started ok and pool list, filesystem list all work fine we could not remount the filesystems - the message was that the superblock could not be read. Could not find anyway to repair it.
> 
> Luckily we had the original copy of the data still and so have converted from stratis to mdadm raid-0 and copying the back for a 2nd time.
> 
> A bit disappointed to say the least.
> 
> This was in the logs:
> 
> stratisd[935]: WARN libstratis::engine::strat_engine::engine: no pool set up, reason: Engine(Error, "failed to set up pool for (pool UUID: 56775cf8-503a-4314-b726-c4342a68e6cf, devnodes: /dev/sda ,/dev/sdb): reason: Engine(Invalid, "UUIDs of devices found (2442fe33da9a4f2fb3cc14d8bc4fc825, cc43482d3db64b57b6f83a57327bed50) did not correspond with UUIDs specified in the metadata for this group of devices (cc43482d3db64b57b6f83a57327bed50, 2442fe33da9a4f2fb3cc14d8bc4fc825, 011c0ebdb3e643ef96a530290a0c771b, 5076d145091d40a2ad2053fa852daf4b)")")
> 
> This is what was placed in the log when we tried to hand mount the filesystem
> 
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
> data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
> in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
> st was 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
> Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
> used.
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
> data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
> in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
> st was 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
> data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
> in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
> st was 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
> Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
> used.
> Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
> used.
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
> data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
> in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
> st was 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
> Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
> used.
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool meta
> data sub-device belonging to pool 56775cf8503a4314b726c4342a68e6cf by 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: WARN libstratis::engine::strat_engine::thinpool::thinpool: Insufficient free space available
> in backstore; extended thinpool metadata sub-device belonging to pool with uuid 56775cf8503a4314b726c4342a68e6cf by 0 sectors, reque
> st was 52606512 sectors
> Jan 21 11:39:09 bristol stratisd[935]: INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 41
> Jan 21 11:39:09 bristol kernel: device-mapper: thin: Metadata device dm-3 is larger than 33292800 sectors: excess space will not be
> used.
> Jan 21 11:39:32 bristol kernel: attempt to access beyond end of device
> Jan 21 11:39:32 bristol kernel: dm-7: rw=4096, want=17179869184, limit=2147483648
> Jan 21 11:39:32 bristol kernel: XFS (dm-7): last sector read failed
> Jan 21 11:39:32 bristol kernel: attempt to access beyond end of device
> Jan 21 11:39:32 bristol kernel: dm-8: rw=4096, want=34359738368, limit=2147483648
> Jan 21 11:39:32 bristol kernel: XFS (dm-8): last sector read failed
> Jan 21 11:42:09 bristol kernel: attempt to access beyond end of device
> Jan 21 11:42:09 bristol kernel: dm-8: rw=4096, want=34359738368, limit=2147483648
> Jan 21 11:42:09 bristol kernel: XFS (dm-8): last sector read failed
> Jan 21 11:45:00 bristol kernel: XFS (dm-6): Mounting V5 Filesystem
> Jan 21 11:45:00 bristol kernel: XFS (dm-6): Ending clean mount
> 
> The XFS systems did not mount - the mount command gave a unable to read superblock error

Please follow up in #1789, rather than here, thanks.

**Comment by gmat** [comment]
@wrigjz Yes it's clearly the same issue. They find the solution on #1789  :tada: 
Correct the wrong size in json file in the metadata. Too late for you but should help many desperate people

**Comment by mulkieran** [comment]
Device mapper enforces two limits: ```DM_CACHE_METADATA_MAX_SECTORS_WARNING``` and ```THIN_METADATA_MAX_SECTORS```. And here's the definitions:

```
/* FIXME: remove this restriction */
/*
 * The metadata device is currently limited in size.
 */
#define DM_CACHE_METADATA_MAX_SECTORS DM_SM_METADATA_MAX_SECTORS

/*
 * A metadata device larger than 16GB triggers a warning.
 */
#define DM_CACHE_METADATA_MAX_SECTORS_WARNING (16 * (1024 * 1024 * 1024 >> SECTOR_SHIFT))
```

we want to observe the warning value, to avoid the warnings.

**Comment by mulkieran** [comment]
According to my calculations, the maximum size of the metadata device is 17045913600 B, and the value reported by the log entry matches this. The value at which the warning is given is actually higher, 17179869184 B, to my surprise. We should cap the size of the metadata device at the max value, rather than the warning value.
