### ISSUE TITLE
proptest 0.9

### ISSUE THREAD

**Issue by ignatenkobrain** [stratis-storage/stratisd#1496]
Would be much appreciated :)

**Comment by mulkieran** [comment]
Having problems compiling the newer version of rand crate, 0.6.5, required by newer version of proptest:
A sample:

```
error[E0277]: the trait bound `rand_hc::Hc128Rng: rand_core::SeedableRng` is not satisfied
   --> /home/mulhern/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.5/src/deprecated.rs:280:5
    |
280 |     type Seed = <rngs::StdRng as SeedableRng>::Seed;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::SeedableRng` is not implemented for `rand_hc::Hc128Rng`

error[E0277]: the trait bound `rand_hc::Hc128Rng: rand_core::SeedableRng` is not satisfied
   --> /home/mulhern/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.5/src/deprecated.rs:282:5
    |
282 | /     fn from_seed(seed: Self::Seed) -> Self {
283 | |         StdRng(rngs::StdRng::from_seed(seed))
284 | |     }
    | |_____^ the trait `rand_core::SeedableRng` is not implemented for `rand_hc::Hc128Rng`

error: aborting due to 31 previous errors
```

**Comment by ignatenkobrain** [comment]
@mulkieran any news? what version of rustc are you using?

**Comment by mulkieran** [comment]
I'm using 1.33. No new news. I'm afraid I haven't had time to investigate why this isn't compiling properly.

**Comment by mulkieran** [comment]
Here's the very first error:

```
error[E0277]: the trait bound `rand_hc::Hc128Rng: rand_core::SeedableRng` is not satisfied
  --> /home/mulhern/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.5/src/rngs/std.rs:55:6
   |
55 | impl SeedableRng for StdRng {
   |      ^^^^^^^^^^^ the trait `rand_core::SeedableRng` is not implemented for `rand_hc::Hc128Rng`

```

This is our problem: https://github.com/rust-random/rand/issues/754, I think.

**Comment by mulkieran** [comment]
There is only one version of ```rand_hc``` so upgrading that can't fix the problem.

**Comment by mulkieran** [comment]
What's puzzling is that the version of rand being compiled is also the newest.

**Comment by ignatenkobrain** [comment]
I think it might be related that we have all kind of versions of rand in lock. What about to update rand in stratisd to 0.6?

**Comment by mulkieran** [comment]
I'm afraid that yields the same errors. We're compiling the newest version of rand, against the newest version of rand_hc when we fail. This is weird.

**Comment by mskarbek** [comment]
Bumping rand to 0.6 requires adding `rand_core="0.3.1"` in `Cargo.toml` and small change in `src/engine/sim_engine/randomization.rs` - then it compiles. I'm waiting for tests and will push that.

**Comment by ignatenkobrain** [comment]
I'll submit some bigger patch with updating deps

**Comment by mulkieran** [comment]
This is motivated by packaging problems on Fedora, which I don't fully understand yet. Moving to July.

**Comment by mulkieran** [comment]
Some problems will go away if we are able to move our lowest supported compiler up a bit: https://github.com/stratis-storage/project/issues/47, so I'll call it blocked by that.

**Comment by mulkieran** [comment]
We will try again now that we have pushed our lowest suppported compiler up to 1.35.

**Comment by mulkieran** [comment]
Raising our lowest supported compiler to 1.35 does not solve all issues, we'll have to keep working at this.

**Comment by jbaublitz** [comment]
Bumping `proptest` to `0.9` and running a blanket `cargo update` will resolve the problem but I've had less luck with independently bumping packages. How much are we willing to change the Cargo.lock file?

**Comment by jbaublitz** [comment]
I've now also managed to reproduce a fix only updating a few dependencies.

Case 1:
```
# Update proptest to 0.9 in Cargo.toml
cargo update
```
Tests pass and compilation succeeds.

Case 2:
```
# Update proptest to 0.9 in Cargo.toml
cargo update -p proptest
cargo update -p randcore:0.3.0
```
Tests also pass and compilation succeeds.

I'm open to both approaches. Major pro for the former is that it will keep us more current and seems not to break anything, but it is probably worth looking into it before making such a wide range of dependency updates.

**Comment by mulkieran** [comment]
We'll move this forward when be bump lowest supported compiler version.
