### ISSUE TITLE
all udev tests being skipped in Jenkins CI

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1502]
Currently the udev tests require the enviroment variable STRATIS_DESTRUCTIVE_TEST to be set, and it doesn't seem to be being set in the current environment.

Note that the reason for the use of this variable is more-or-less historical. At one time, the udev tests were mixed in w/ the dbus tests. The dbus tests all use the sim engine and can not effect the environment, where as the udev tests can affect the environment. Now that the udev tests are in a separate directory, there might be a good reason to make the decision in a different way (or to keep it the way it is).

**Comment by tasleson** [comment]
@mulkieran The udev tests create all their own block devices for testing, thus we could remove this check as we aren't using the devices specified in the json device test file.

**Comment by mulkieran** [comment]
It seems that we are all agreed that we can remove the need for the STRATISD_DESTRUCTIVE_TEST environment variable. So it's not a test script issue, it's just a matter of editing the tests a bit, so I'll pick it up.

**Comment by mulkieran** [comment]
Closed by #1505.
