### ISSUE TITLE
Add unit test for inaccessible block device

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1512]
`stratisd` did have an issue where it would panic if it was unable to comunicate with one of the block devices.  You can create this error situation by doing
```
echo offline > /sys/block/<devname>/device/state
```

You can restore operation by doing
```
echo running > /sys/block/<devname>/device/state
```

Note: No udev events are created by this

Thus it would be good to add an additional unit test to the existing udev tests which creates a pool with one or more loop back devices and then does the offline operation on one or more of them. Our expectation is that the stratisd process continues to run and you can query the pool(s) and get the expected number returned. Today I believe we don't crash the service, but when we retrieve all the managed objects we get an error as dm cannot talk to the device to retrieve information needed to fill out the properties.

**Comment by mulkieran** [comment]
The problem referred to of the GetManagedObjects call failing was fixed by stratisd release 2.0.0: https://stratis-storage.github.io/2019-11-06/.

We always have ongoing testing plans for all the work that we do, so we do not require this issue especially.
