### ISSUE TITLE
BDA_STATIC_HDR_SIZE should not be used in tests in mda module

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1543]
The offset of the MDA from the start of the device is always abstracted in the source. The tests should be abstracted, too, and use any valid offset. In this way, BDA_STATIC_HDR_SIZE can be made private to the bda module, created in #1541.

**Comment by mulkieran** [comment]
Currently blocked by #1541.

**Comment by mulkieran** [comment]
@GuillaumeGomez this would be a good immediate follow-up to #1541.

**Comment by GuillaumeGomez** [comment]
Then I'll do it once #1541 has been merged.

**Comment by GuillaumeGomez** [comment]
Can you assign me on this issue please? Makes it easier to retrieve it later on.
