### ISSUE TITLE
Correct excessive indentation in StaticHeader::setup

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1575]
Each match arm for ```BDA::read(f)``` has a corresponding expression which is nested one level deeply as

```
{
   match ...
}
```

Those extra braces should be eliminated. This extra nesting is apparently done in order to give the comments a place, but the comments shouldn't force the code that way.

**Comment by mulkieran** [comment]
@GuillaumeGomez Could you do this one before the other StaticHeader::setup() one? I know there will be conflicts again, but I'ld rather have the changes in separate PRs, and I'ld rather have this one first.

**Comment by GuillaumeGomez** [comment]
Sure! I'll try to do it quickly.
