### ISSUE TITLE
Move BDA::read out of BDA implementation

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1582]
It only reads the locations of the sigblocks and the only method that depends on it is ```StaticHeader::setup```.

~~We should probably make it a member of the static_header module, rather than a member of the ```StaticHeader``` impl, also.~~ We'll handle this part of the big move later if it seems indicated. Let's just move it into the ```StaticHeader``` impl, so that it can be with its friend, ```StaticHeader::write```.

**Comment by mulkieran** [comment]
@GuillaumeGomez Could you address this one next?

**Comment by GuillaumeGomez** [comment]
Sure. Leave me a few days.

**Comment by mulkieran** [comment]
Absolutely, whenever you're ready!
