### ISSUE TITLE
Move the implementation of BDA::wipe into the static header module

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1584]
~~I think that ```BDA::wipe``` is invoked from outside the metadata module, so the method itself should be left. A new method should be created inside the ```static_header``` module.~~

Here's the new proposal:
1. Hoist the ```device_identifiers``` method right out of the BDA implementation and into the module top-level. This can be done by defining it, as a public method, in metadata/mod.rs. A lot of callers which currently call ```BDA::device_identifiers``` will need to be updated accordingly. Internal tests which call ```device_identifiers``` should be updated to call ```StaticHeader::setup``` instead.

2. Simultaneously:
  * Add another method in metadata/mod.rs called ```disown_device```. Have this method call the ```StaticHeader::wipe``` method directly.

  * Move ```BDA::wipe``` into the ```StaticHeader``` implementation.

  * Update calls to ```BDA::wipe``` so that they instead call ```disown_device``` wherever necessary (or ```StaticHeader::wipe``` if they are metadata internal testing code).

Note that, after this, all StaticHeader-specific methods should have been moved into the ```StaticHeader``` implementation. So in the next step it should be possible to move the entire implementation into a separate module, one of the main parts of the goal of #1573.

**Comment by GuillaumeGomez** [comment]
Will do it in the next days then!

**Comment by mulkieran** [comment]
Great!
