### ISSUE TITLE
We would like CI to fail if the compiler generates warnings

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#159]
Something like the gcc flag -Wall.

In theory, we should be able to do this by modifying the dev profile, but in practice, the profile does not seem to include anything to change this behavior.

**Comment by agrover** [comment]
`-Werror`, but yeah.

**Comment by agrover** [comment]
https://github.com/rust-lang/rust/issues/8496#issuecomment-22592574

**Comment by mulkieran** [comment]
https://github.com/rust-lang/cargo/issues/60 final comment seems like it might helfp.

**Comment by mulkieran** [comment]
Resolved by #161.
