### ISSUE TITLE
Run up some tests of our properties obtained by FetchProperties

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1681]
We should definitely make sure of the types. Python is so forgiving, and the justbytes library is fairly forgiving, too, so the CLI tests are sometimes not going to pick up wrongly typed D-Bus values.

**Comment by jbaublitz** [comment]
@mulkieran Should we check all of the types for DBus calls? Just for `FetchProperties`? What's the scope for this?

**Comment by mulkieran** [comment]
I think for ```FetchProperties``` and the properties on ```...pool```, ```...filesystem```, etc. as well. There's a function that  exists in tests/client-dbus/tests/dbus/filesystem/test_properties.py for testing filesystem properties, but I think it's a bit unconsidered. Sometimes, there's an assertion about equality when a more generic assertion would be better and less likely to lead to annoying little errors.

For example, 

```
(used_success, used) = FetchProperties.Methods.GetProperties(
            filesystem, {"properties": ["Used"]}
        )["Used"]

        self.assertEqual(used_success, True)
        self.assertEqual(used, "12345678")
```

The last line is just due to a completely arbitrary choice of a return value in the sim engine, and shouldn't be relied upon for testing. It would be better to do something like check that the result is formatted as an int, somehow, because that is what is wanted to be ensured, always.

There should probably be a file like test_properties.py but improved in the manager and pool directory, as well as in the currently non-existent blockdev directory.
