### ISSUE TITLE
Don't ignore error message when stratisd fails to connect to the DBus

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#1683]
We currently ignore the error returned when connecting to the DBus in stratisd [here](https://github.com/stratis-storage/stratisd/blob/master/src/bin/stratisd.rs#L186). We should probably print out the error message so users can figure out what happened.

**Comment by mulkieran** [comment]
Yes, definitely, that would be better.

**Comment by mulkieran** [comment]
@jbaublitz If you want to do this for this release, please go ahead, as it has a direct bearing on PR #1682.
