### ISSUE TITLE
Update stratisd.conf to allow non-root user to use methods on FetchProperties interface

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1688]
Otherwise, obtaining various properties by means of FetchProperties, and hence calling ```stratis pool list``` or ```stratis filesystem list``` which uses these properties will require root permissions, which it did not preivously.

**Comment by jbaublitz** [comment]
I figured out a policy entry that works. We may want to tweak it to be more scoped, but `<allow send_interface="org.storage.stratis2.FetchProperties"/>` does allow this to work.
