### ISSUE TITLE
Clean up dbus tests to make variables local instead of instance variables wherever possible

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#1708]
There are a number of tests that make variables instance variables where they only need to be local. Eventually we should clean this up to make them scoped to only be accessible where they're needed.

**Comment by mulkieran** [comment]
Tentative assignment...we do not have the same problem in stratis-cli, as our tests make use of the command-line instead of the D-Bus, so this problem is probably local to stratisd.

**Comment by mulkieran** [comment]
Might as well do this immediately. The trick is to make _all_ identifiers that don't need to be global local to the one method in which they are used.
