### ISSUE TITLE
Consider abstracting methods that are identical between engines

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#172]
This is a judgement call, because it would involve exposing more API. The methods that are currently identical are ```get_pool()```, ```destroy_pool()```, and ```rename_pool()```. All these require access to struct members which happen to be the same between the engines, but, being members, are not part of the Engine's public API.

**Comment by mulkieran** [comment]
Also ```pools()```. This means that the only Engine methods that are different are ```create_pool()``` and ```configure_simulator()```.

**Comment by mulkieran** [comment]
Attributes that would have to be exposed:

* ```Engine::pools```

For ```destroy_pool()```
* ```Pools::filesystems```
* ```Pools::block_devs```
* ```Pools::cache_devs```

For all of which we already have methods. But using the methods is more expensive as they construct their own data structures, in the general case. This situation may very well call for macros.

**Comment by agrover** [comment]
I don't know if macros are the answer, or to try refactoring collections into common code.

**Comment by mulkieran** [comment]
I think the macros are working out quite well right now: https://github.com/stratis-storage/stratisd/pull/173.
They are an improvement in themselves, and will help make any other non-accidental similarities easier to discover.
They are not a high cost to make, and won't be a high cost to throw away, if necessary.
They will motivate abstracting the collections into shared code, if possible, to make them, i.e., the macros, not break.

**Comment by mulkieran** [comment]
Resolved by #173.
