### ISSUE TITLE
Not all setUp methods in dbus tests register a cleanup handler

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#1720]

**Comment by mulkieran** [comment]
@jbaublitz I can't find the tests that you're referring to, can you identify them?

**Comment by jbaublitz** [comment]
I'll take a look on Monday.

**Comment by jbaublitz** [comment]
I'm going to assume this was a misunderstanding on my part. The tests that I'm seeing without the cleanup handler registered are all dbus tests that use `SimTestCase` and after digging into the definition of `SimTestCase`, I see that it registers a cleanup handler there. Closing.
