### ISSUE TITLE
Use git objects for file deduplication

### ISSUE THREAD

**Issue by DaniellMesquita** [stratis-storage/stratisd#1722]
Look for files which are alike, then diff using git. Store git objects, and file mirroring are joints of these.

**Comment by DaniellMesquita** [comment]
@whyrusleeping @Stebalien
Git objects would also be used by IPFS, working like data chunking but he deduplication. Also, IPFS could use a filesystem (would be Stratis) for uploading objects of a file instead of the whole file itself.

**Comment by jbaublitz** [comment]
Hi @DaniellMesquita, I'm a little confused by the issue. Are you filing a bug with stratisd or requesting a feature? If so, would you be willing to provide some more information on what you're reporting or requesting? Thanks!

**Comment by DaniellMesquita** [comment]
If Stratis uses git objects, then it would be a bug report; but as Stratis doesn't uses git objects for deduplication, this is a suggestion.

**Comment by DaniellMesquita** [comment]
IPFS devs also demoed fear to reply this...
