### ISSUE TITLE
It should be possible to combine removing object paths from maps and queueing up removal for dbus

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#174]
Removing from map and forgetting to remove from dbus objects is like a memory leak and the opposite is like an early free.

**Comment by agrover** [comment]
You're saying, have one function that does both these things that other places can call, so they don't do one and not the other?

**Comment by mulkieran** [comment]
Yes. I think that's a D-Bus API sort of change.

**Comment by mulkieran** [comment]
This is obsolete. PR #244 makes the look-aside tables much simpler and so these actions are much more concise, The look-aside tables will themselves go away with help from the next dbus-rs release. Moreover, there isn't a lot of symmetry in the way object path addition and object path removal are put in the ActionQueue; it doesn't match updates to the look-aside tables.
