### ISSUE TITLE
dbus-rs 0.7 came out in September; we should consider moving up at some time

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1755]
We're currently pinned to 0.6.4 which came out in January 2019. We need to evaluate what the new version brings, as it has been under very active development; it is possible that it will bring us advantages which we can take advantage of on the upgrade.

**Comment by ignatenkobrain** [comment]
Actually 0.8 is out, #1835 . Would be very nice if you could upgrade it ASAP. I'm planning to update it in Fedora soon (because i3status-rs depends on it now).

**Comment by ignatenkobrain** [comment]
https://github.com/diwic/dbus-rs/blob/master/dbus/changes-in-0.7.md

**Comment by mulkieran** [comment]
Ok. We will give upgrading to 0.8 a go.
