### ISSUE TITLE
Need to find a better organizing principle for our dbus_api pool, filesystem, blockdev modules

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1760]
They are getting longer and by our support for multiple versions will get longer still and more complicated.

There are two obvious ways to subdivide the methods for easier looking: by interface that they implement and by level...some are purely internal to the implementation and some are invoked because they are the methods that do the work of the interface.

We can organize by both...a sort of internal shared util module and a module for each interface might work.

We would want to make sure that it would not need to be violently adjusted when we add additional interfaces.

NOTE that in #1705 support for multiple interfaces is necessarily added for pool and for api. This is done lazily, in the sense that only methods that are identical between interfaces undergo the ```_object``` generalization. This seems fine to me, but I think that it may be possible that it will be necessary to version even these ```_object``` methods, since a method may stick around through several versions, and then need to be updated. So, I'm suggesting this:

* Group methods by first interface in which they appear.
* Only generalize the methods so that they are constructed from the factory argument if they persist into at least two interface versions.

What this means is that it would be inappropriate to do any work to generalize the functions so they take the factory argument in the PR associated with this issue, since it is #1705 which first adds a new interface version.

**Comment by mulkieran** [comment]
With encryption added:

```
   17 src/dbus_api/mod.rs
   24 src/dbus_api/consts.rs
   72 src/dbus_api/event_handler.rs
   73 src/dbus_api/macros.rs
  139 src/dbus_api/types.rs
  169 src/dbus_api/util.rs
  308 src/dbus_api/filesystem.rs
  334 src/dbus_api/blockdev.rs
  360 src/dbus_api/api.rs
  655 src/dbus_api/pool.rs
```
current:

```
   17 src/dbus_api/mod.rs
   22 src/dbus_api/consts.rs
   60 src/dbus_api/macros.rs
   72 src/dbus_api/event_handler.rs
  139 src/dbus_api/types.rs
  169 src/dbus_api/util.rs
  306 src/dbus_api/api.rs
  308 src/dbus_api/filesystem.rs
  334 src/dbus_api/blockdev.rs
  564 src/dbus_api/pool.rs
```

api gains approx 50, pool approx 100.

**Comment by mulkieran** [comment]
@jbaublitz Over to you...

**Comment by jbaublitz** [comment]
@mulkieran 

I was thinking something along the lines of:
```
                          pool/
       /          /        |           \            \
shared.rs   pool_1/      pool_2/ fetch_properties/  mod.rs
           /  |  \      /  |  \      /  |  \
       api.rs |  |  api.rs |  |  api.rs |  |
    methods.rs-  | methods.rs | methods.rs |
        props.rs -    props.rs-    props.rs-
```

instead of `pools.rs`.

Per interface:
`api.rs` would contain methods to generate objects to pass to the D-Bus factory calls.
`methods.rs` would contain all underlying methods used to handle D-Bus method calls.
`props.rs` would contain all underlying methods used to handle D-Bus property accesses.

Per interface type:
`shared.rs` would include all common code across interfaces but common to the interface type.
`mod.rs` would include all exports.

**Comment by mulkieran** [comment]
Ok. I'm going to use your encryption PR has the most complex example we have available and see how the methods allocate.

**Comment by mulkieran** [comment]
```
pool
  - mod.rs  - just all necessary exports from pool
      I think the only necessary export is create_dbus_pool(); I wouldn't mind having it in mod.rs,
      under the circumstances.
  - fetch_properties
    - api.rs  # I think we don't expect to have to version FetchProperties interface so leaving as is
      * pub get_all_properties_method
      * pub get_properties_method
    - method.rs
       * pub get_properties
       * pub get_all_properties
       * get_properties_shared
    - props.rs
  - pool_1
    - api.rs
      * pub rename_method_object
      * pub add_blockdev_method_object
      * pub snapshot_method_object
      * pub destroy_filesystems_method_object
      * pub create_filesystems_method_object
      * pub uuid_property_object
      * pub name_property_object
      * pub add_chachedev_method_object # currently just add_cachedev_method
    - method.rs
      * pub rename_pool
      * pub add_cachedevs # there will be a different version in pool_2
      * pub add_datadevs
      * pub snapshot_filesystem
      * pub destroy_filesystems
      * pub create_filesystems
    - props.rs
      * pub get_pool_name
      * pub get_pool_property
  - pool_2
    - api.rs
      * pub init_cache_method_object  # currently just a method not a method object
      * pub add_cachedevs_method_object # currently just a method not a method object
    - method.rs
      * pub add_cachedevs #previous version in pool_1
      * pub init_cache
    - props.rs  
  - shared.rs
     * pub pool_operation
     * pub add_blockdevs
```

**Comment by mulkieran** [comment]
@jbaublitz Is that what you were thinking?

**Comment by mulkieran** [comment]
We would avoid making empty files, so, e.g.,  the ```fetch_properties``` directory does not need a ```props.rs```.

And for real purposes we should rename ```pool_1``` to ```pool_2``` and ```pool_2``` to ```pool_2_1``` to match our actual version numbers.

**Comment by mulkieran** [comment]
Err, correction, we will expect to have to version the FetchProperties interface, because we may add support for new "properties" or remove support from old ones.

**Comment by jbaublitz** [comment]
@mulkieran This looks reasonable to me. I agree that we should avoid empty files and the diagram above is meant to communicate structure only. The list above is indeed what I was thinking in terms of what methods go where. Does this seem like a reasonable set of rules for moving forward to you?

**Comment by mulkieran** [comment]
@jbaublitz Yes, please go ahead!
