### ISSUE TITLE
Have device_identifiers() return a struct instead of a tuple

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1794]
The struct should have two fields for the two identifiers and I don't think it needs any impl.

It can be used in the definition of the StaticHeader struct and also used in the result type of functions that call device_identifiers().

This should reduce type complexity and eliminate confusion in a few places.

It should wait until I've gotten in the PR that eliminates the device.rs module that defines DevOwnership, though, because that'll get rid of some invocations of device_identifiers.

**Comment by mulkieran** [comment]
Call it ```StratisIdentifiers``` and define it in ```static_header.rs```? Start out by just defining the method ```device_identifiers``` so that it returns ```StratisResult<Option<StratisIdentifiers>>``` and then do the right thing wherever that method is used.

**Comment by mulkieran** [comment]
Best to not touch until #1809 gets in.

**Comment by mulkieran** [comment]
@GuillaumeGomez, I think this would be a good one, but we'ld like to get #1809 merged first.

**Comment by GuillaumeGomez** [comment]
Sounds good to me. Please ping me once #1809 is merged.

**Comment by mulkieran** [comment]
@GuillaumeGomez Please feel free to begin at any time.

**Comment by GuillaumeGomez** [comment]
Ok!
