### ISSUE TITLE
For CI, need to worry about DISPLAY variable when using dbus

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#18]
BusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

**Comment by agrover** [comment]
We can't use DBus in CI. Continuing issue.

**Comment by mulkieran** [comment]
Jenkins test in stratisd-client-dbus and stratis-cli more or less resolve this. Question. Is it possible to rearrange Jenkins to run stratisd-client-dbus tests as part of stratisd CI and as part of stratisd-client-dbus CI?

**Comment by trgill** [comment]
Currently a PR in stratis-cli triggers "make dbus-tests" against the PR in stratis-cli using master for:

dbus-client-gen
dbus-signature-pyparsing
dbus-python-client-gen
into-dbus-python
stratisd

I think we easily change the Jenkins task to trigger the "make dbus-tests" for a stratisd PR using master for the other repos.  That is what you'd like?

Also, the current Jenkins task doesn't trigger the dbus-tests in stratisd-client-dbus.  Should I update that?

**Comment by mulkieran** [comment]
For stratisd-dbus-client:

If it, itself, is changed, D-Bus tests should be run.

It depends on dbus-client-gen, dbus-signature-pyparsing, dbus-python-client-gen, into-dbus-python. These are fairly unlikely to change, several haven't changed for over three months, but if they do it is probably right to run the D-Bus tests.

It tests stratisd, so it should probably be run when stratisd changes. Ideally, though, the results of this test would be reported in stratisd results. Is this possible?

For stratis-cli I think things are most the same. The only difference is that if stratisd changes it makes sense to run the D-Bus tests, but the results might as well be reported in stratis-cli results, not stratisd results.
