### ISSUE TITLE
Tracking issue for proposed libc changes

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1870]
https://github.com/rust-lang/libc/pull/1678

**Comment by jbaublitz** [comment]
Merged.

**Comment by mulkieran** [comment]
Let's hang onto this until they release the new version.

**Comment by mulkieran** [comment]
We'll check back on the release next month.

**Comment by jbaublitz** [comment]
As a last ditch effort, we can submit a PR to bump the version if it comes down to that. They've been very helpful when I've done that in the past and only have you wait if there's something specific holding it up.

**Comment by mulkieran** [comment]
Ok. Depends on what you think we need.

**Comment by jbaublitz** [comment]
I think we can hold off until we're ready to release, but we can try that at that point if there's been no new release.

**Comment by mulkieran** [comment]
Excellent. Feel free to do that as soon as is convenient.
