### ISSUE TITLE
Need to distinguish PoolUuid, DevUuid, FilesystemUuid by something more than aliases

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1877]
Currently, all these are just aliases for Uuid. This will make some definitions necessary for https://github.com/stratis-storage/stratisd/pull/1874 to have conflicts like:
```
error[E0119]: conflicting implementations of trait `std::fmt::Display` for type `engine::types::actions::RenameAction<uuid::Uuid>`:
  --> src/engine/types/actions.rs:33:1
   |
27 | impl fmt::Display for RenameAction<PoolUuid> {
   | -------------------------------------------- first implementation here
...
33 | impl fmt::Display for RenameAction<DevUuid> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `engine::types::actions::RenameAction<uuid::Uuid>`

error: aborting due to previous error
```

**Comment by jbaublitz** [comment]
@mulkieran I forgot to mention that I looked at this in stand up.

I see two potential paths forward:
1. Wrapping `Uuid` in three distinct structs and exposing the same methods provided by `Uuid` for `DevUuid`, etc. (so `DevUuid` would be a wrapping struct also with the method `::nil()` and `.to_simple_ref()` available.
2. Wrapping `Uuid` in three distinct structs and relying on modifying the `Uuid` code to rely on a `Deref` implementation.

Despite the fact that 2 will probably result in more manual wrangling of dereferences throughout the code, I prefer this solution as it will leave to less of what seems to me like a bandaid fix and will instead allow us to keep `Uuid` completely separate logically from `DevUuid` and friends.

**Comment by mulkieran** [comment]
Thanks for looking at this. Let's talk about it in standup tomorrow. I don't understand the distinction between the two that you are drawing.

**Comment by jbaublitz** [comment]
Sounds good!

**Comment by mulkieran** [comment]
@jbaublitz I'ld like to restrict the impl to the three Ds, Deref, Debug, and Display, as below, as I'ld like the Display info to include the particular category of UUID. What do you think? (Ultimately, of course, we'ld define the type for each category via a single macro, as they would be identical modulo the name of the type and the Display string, so this really constitutes an example that we'ld follow exactly for PoolUuid and DevUuid. The macro would also help enforce the restriction that these types don't implement any other methods.)

```
use std::fmt;
use std::ops::Deref;

use uuid::Uuid;

#[derive(Debug)]
/// Marker type to distinguish a filesystem UUID from other UUID categories.
struct FilesystemUuid(Uuid);

impl FilesystemUuid {
    fn new(uuid: Uuid) -> FilesystemUuid {
        FilesystemUuid(uuid)
    }
}

impl fmt::Display for FilesystemUuid {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "filesytem UUID {}", self.0.to_simple_ref())
    }
}

impl Deref for FilesystemUuid {
    type Target = Uuid;
    fn deref(&self) -> &Uuid {
        &self.0
    }
}

fn main() {
    let fs_uuid = FilesystemUuid::new(Uuid::new_v4());
    println!("{}", fs_uuid);
    println!("{}", *fs_uuid);
    println!("{:?}", fs_uuid);
}
```

**Comment by mulkieran** [comment]
Re-assigning. I think we can postpone the macro until later; now it's become a problem of fixing up use sites. We should start with the Uuid with the fewest uses.

**Comment by mulkieran** [comment]
Re assigning just to me, this has a lot of preliminary requirements.

**Comment by mulkieran** [comment]
Realistically, given where we are in August, won't make it until September.
