### ISSUE TITLE
Potential use case for mio

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#1906]
The comment [here](https://github.com/stratis-storage/stratisd/blob/develop-2.0.1/src/bin/stratisd.rs#L369-L379) makes a good case for avoiding nix. However, mio does not have the same limitations and provides a good cross-platform implementation of the poll interface for all supported operating systems. Moreover, because file descriptors should be unique if they are not duplicated which we do not do, there seems to be a clever way in which we could store the file descriptor as the `Token` value for use with D-Bus. While we should investigate this option as it doesn't seem to be the exact case for which `Token` was intended, there is also another possibility of implementing the `Source` trait for our own data structure wrapping the file descriptor which could do resource clean up using the `Drop` trait as well. Both of these options would take some investigation but seem like viable options over libc.

**Comment by jbaublitz** [comment]
@mulkieran This will no longer be relevant if #2282 gets merged.

**Comment by mulkieran** [comment]
I think we can consider this obsoleted by #2337.
