### ISSUE TITLE
Update stratisd.conf to support listing on new FetchProperties interface

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#1918]
Given that we now use `FetchProperties.r1` to fetch our encryption and cache properties using the CLI, the current policy in `stratisd.conf` no longer allows unprivileged users to list their pools. We should update the `stratisd.conf` file to also whitelist `FetchProperties.r1`.

**Comment by mulkieran** [comment]
Related: https://github.com/stratis-storage/project/issues/149.
