### ISSUE TITLE
Crypt module device wiping bug

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#1920]
Current method `ensure_inactive` in the crypt module does not actually have idempotent behavior as the name and documentation suggests. Due to the libcryptsetup deactivation methods not being idempotent and rather returning an error if an inactive device is deactivated, our wiping method (which relies on idempotently ensuring that devices are inactive) will return an error if the device is already inactive. This is triggered in the case of rolling back an initialization if activation could not be accomplished but the LUKS2 header has been written to the device. The crypt module will attempt to deactivate a device that has never been activated and will return early prior to wiping the LUKS2 metadata from the device. This leaves the encrypted device in a state where it cannot be initialized again without first wiping the device with a utility outside of Stratis.

@mulkieran This is a bug, not a problem with udev after all. I did some digging down to the superblock level and discovered this issue.

**Comment by jbaublitz** [comment]
I will also add a test that fails part way through initialization of a device to make sure that clean up in that case also works. The reason this was not caught by our previous tests is that all of those devices in the cleanup tests had been successfully initialized so they were all active at the time of cleanup. This bug is only triggered when a device fails to initialize partway through and never becomes active.

**Comment by mulkieran** [comment]
Ok! That's very good news.
