### ISSUE TITLE
Refine names of dm-crypt devices synthesized during initialization

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1935]
Currently, the names we use have format ```<pool uuid in simple form>-<device uuid in simple form>```.

These names are public enough that we should disambiguate them with a "stratis" prefix of some sort, as we do with other names.

Given that they can't be viewed as a private detail of the encryption mechanism, we should define the names more formally, in our names.rs module.

We have a countervailing consideration: the DM UUIDs synthesized by cryptsetup from the names specified are 111 characters, the hard limit on UUID length is 129. If cryptsetup changes its DM UUID synthesis algorithm, and makes the UUID longer, it could overflow the allowed length of the UUID.

If we add a prefix, like "stratis-", that's 8 characters eating up the remaining free space available for the DM UUID.

Should we shorten our name in order to avoid this? ~~There is an obvious way to cut the number of characters used to represent a UUID by half; just use the string representation of the raw number, rather than the string representation of the hexadecimal representation of the number.~~ This does not work, because it omits considerations of the representation. We can _store_ the UUIDs in half the bits; but representing them in the names is a whole different thing.

This is a precaution against future changes in cryptsetup, but it might be a prudent choice.

**Comment by jbaublitz** [comment]
We've raised one option of hashing the two UUIDs together as a solution that could satisfy our requirements:
* Constant length despite the data entered
* Shorter than the hex representation of two UUIDs when using SHA224 (40 vs. 65 characters)
* Deterministic
* We do not need an invertible method like encryption as we store the UUIDs separately elsewhere in the LUKS2 metadata

What are your thoughts on the above @mulkieran?

**Comment by mulkieran** [comment]
Resolved by #1942
