### ISSUE TITLE
Encrypted stratis blockdevs require the key to be in the keyring longer than necessary 

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#1961]
While writing encryption blackbox tests, I realized that the key is required to be available in the keyring to disown encrypted devices which has no logical purpose. It boils down to the `CryptHandle::setup()` method which checks if a device is an encrypted stratis device. Part of this check actually verifies that the correct key is in the kernel keyring which is out of scope for checking whether the device is an encrypted Stratis device.

My recommendation is that we make this check available in some public `crypt.rs` method but perform it neither in `CryptHandle::setup()` nor `CryptHandle::can_setup` as both of these methods were designed to only make a decision at a metadata level, not a machine environment level and we will bump into unintended consequences like the one I outlined above if we do not distinguish between them.

**Comment by mulkieran** [comment]
ok!
