### ISSUE TITLE
Consider making a struct for Stratis LUKS tokens and implementing Serialize and Deserialize traits

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1995]
This would be tidier if it were possible. I do not see any obvious lifetime-related counter indications. It would be desirable to verify that the keyslots value is empty, which might make things less simple.

**Comment by jbaublitz** [comment]
Per your comment in #1993:
> I'm not sure that simply deriving Deserialize on some struct representing a Stratis token wouldn't be all that was required for validity checking.

I think that even if we have to do additional checks outside of `Deserialize`, it's still probably a good idea from a readability standpoint.

**Comment by mulkieran** [comment]
In standup we agreed that we could drop the key description from the Stratis token. There also turns out to be a little work involved in implementing the Deserialize trait as there are some fields in one or both of the tokens that were irrelevant to us, so weren't being read, but which the implementation of the Deserialize trait must take into account. I assume this will apply to the Serialize trait also.

**Comment by jbaublitz** [comment]
Upon further investigation, this actually may not be practical. libcryptsetup-rs requires an input of type `serde_json::Value` when setting tokens. This makes sense from the perspective of providing a richer type than simply `&str` at the libcryptsetup-rs API level. I don't think we should change this as that would impact uses of libcryptsetup-rs outside of Stratis negatively.

However, this brings us to the `Serialize` trait. `Serialize` will result in a JSON string, not a `Value` type which means that we can't achieve this issue as it stands. We would have to change the libcryptsetup-rs API to accept a string to make this work which I don't think is a good idea.

The only other solution I can think of is accepting a generic type in libcryptsetup-rs that implements `Serialize` and doing the serialization there, but I don't think this adds a whole lot of benefit over what we have already.

**Comment by mulkieran** [comment]
> Upon further investigation, this actually may not be practical. libcryptsetup-rs requires an input of type `serde_json::Value` when setting tokens. This makes sense from the perspective of providing a richer type than simply `&str` at the libcryptsetup-rs API level. I don't think we should change this as that would impact uses of libcryptsetup-rs outside of Stratis negatively.
> 
I agree.

> However, this brings us to the `Serialize` trait. `Serialize` will result in a JSON string, not a `Value` type which means that we can't achieve this issue as it stands. We would have to change the libcryptsetup-rs API to accept a string to make this work which I don't think is a good idea.
> 

I agree with that.

> The only other solution I can think of is accepting a generic type in libcryptsetup-rs that implements `Serialize` and doing the serialization there, but I don't think this adds a whole lot of benefit over what we have already.

Yes. I think alterations to libcryptsetup-rs API wouldn't make much sense. Is there still value though in defining the structure of the Stratis token via a type definition and implementing ```TryFrom<Value> for StratisToken```?

**Comment by jbaublitz** [comment]
> Yes. I think alterations to libcryptsetup-rs API wouldn't make much sense. Is there still value though in defining the structure of the Stratis token via a type definition and implementing `TryFrom<Value> for StratisToken`?

I think this would be the cleanest solution. It also might be worth keeping the `Report` interface JSON conversion the way that it is `Into`/`TryFrom`.
