### ISSUE TITLE
Extend actions in crypt module to verify correct key description

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1998]
As far as I can tell, it is possible for Stratis to activate a device with one key description but end up storing another key description in its data structures during device discovery.

The LUKS2 and Stratis tokens are supposed to be matched by their key description. At present, it looks to me as if they could disagree and the device still be activated. I think it should be possible to add a check in ```is_encrypted_stratis_device``` to ensure that you can't get a CryptHandle unless the two tokens agree on the key description.

**Comment by mulkieran** [comment]
This may be resolved by simply dropping the key description from the Stratis token entirely, as we agreed to do in standup.

**Comment by jbaublitz** [comment]
#1995 should resolve this issue as well.

**Comment by jbaublitz** [comment]
Now that #2008 is closed, can we consider this resolved?

**Comment by mulkieran** [comment]
Yes, let's close this.
