### ISSUE TITLE
Make key description available from crypt methods

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#2000]
This value needs to be extracted from the encrypted device metadata in order to set it in the StratBlockDev struct. But it would also be desirable to extract it earlier via the ```can_setup``` method. The reason is that if the devices are grouped by pool UUID then a pre-check of the key_descriptions for a single pool can be done. If they are not all the same, then the devices can be shuffled into the not-yet-constructed ```rejected_devices``` data structure, because in that case something will be unrecoverably wrong. It would also be desirable for the ```activate``` method to return the same result values: the stratis identifiers and the key description. This allows Stratis to check that the values at activation are the same as the values at discovery if that ever becomes necessary.

**Comment by mulkieran** [comment]
So, I'ld say: enhance ```can_setup``` so it returns ```Result<Option<(StratisIdentifiers, String)>>``` and enhance ```activate``` so that it returns ```Result<(StratisIdentifiers, String)>``` where ```String``` is the key description in both cases.

**Comment by jbaublitz** [comment]
Based on our conversations around the invariants we discussed around adding block devices to a pool with same key that the pool was created with, does it make more sense to simply validate that all devices respond to a `can_unlock` invocation with `true`? I can see putting the pool in an unrecoverable state if somehow some devices can unlock and others cannot. If none of them unlock, that is potentially recoverable with the addition of the correct key. If they all unlock, we can construct our pool.

**Comment by jbaublitz** [comment]
Per stand up, I'll be removing `can_setup` and loading and exposing the information in the LUKS2 tokens (keyring and Stratis tokens) through the returned handle. The behavior of `can_setup` can be replicated by calling `.is_some()` on the `Option` part of the `Result<Option<CryptHandle>>` type.
