### ISSUE TITLE
Make blockdev's Devnode D-Bus property the actual devnode

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#2007]
Currently, for encrypted devices, the value is the "/dev/mapper" link to the devnode. We want to return the actual devnode.

We would like to do this within the engine, rather than adjusting it within the D-Bus layer. We hope that not much internal code is making use of ```Blockdev::devnode()``` when it should be using a more internal value.

**Comment by jbaublitz** [comment]
@mulkieran How do you feel about adding a method like `canonical_devnode()`? `devnode()` is used quite a lot internally.

**Comment by mulkieran** [comment]
> @mulkieran How do you feel about adding a method like `canonical_devnode()`? `devnode()` is used quite a lot internally.

What we really should be doing is using types to distinguish among different categories of PathBufs. For a storage project, PathBuf is just not enough.

But for now, it might be best to choose the less invasive approach that you suggested: canonicalize the path in the D-Bus layer. It'll be  hack in exactly one place in the D-Bus layer.

But we'll have to put a FIXME next to the code and attach an issue so that the problem can be corrected in future.

**Comment by mulkieran** [comment]
We decided to extend BlockDevPath's constructor for Encrypted devices with a third field.
