### ISSUE TITLE
Engine error: Failed to initialize DM context causes service to fail to start

### ISSUE THREAD

**Issue by FruityWelsh** [stratis-storage/stratisd#2024]
I tried to start it with: ```systemctl start stratisd```
Then checked it's status with ```systemctl status stradtisd```:
```
● stratisd.service - Stratis daemon
     Loaded: loaded (/usr/lib/systemd/system/stratisd.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Mon 2020-05-11 19:29:56 EDT; 43s ago
       Docs: man:stratisd(8)
    Process: 962408 ExecStart=/usr/bin/stratisd --debug (code=exited, status=1/FAILURE)
   Main PID: 962408 (code=exited, status=1/FAILURE)

May 11 19:29:56 manjaro systemd[1]: Started Stratis daemon.
May 11 19:29:56 manjaro stratisd[962408]: DEBUG libstratis::stratis::buff_log: BuffLogger: pass_through: true hold time: none
May 11 19:29:56 manjaro stratisd[962408]:  INFO stratisd: stratis daemon version 2.0.1 started
May 11 19:29:56 manjaro stratisd[962408]:  INFO stratisd: Using StratEngine
May 11 19:29:56 manjaro stratisd[962408]: Engine error: Failed to initialize DM context
May 11 19:29:56 manjaro systemd[1]: stratisd.service: Main process exited, code=exited, status=1/FAILURE
May 11 19:29:56 manjaro systemd[1]: stratisd.service: Failed with result 'exit-code'.
```
Manually running ```sudo RUST_BACKTRACE=1 /usr/bin/stratisd --debug```:
```
DEBUG libstratis::stratis::buff_log: BuffLogger: pass_through: true hold time: none
 INFO stratisd: stratis daemon version 2.0.1 started
 INFO stratisd: Using StratEngine
Engine error: Failed to initialize DM context
```

System info:
```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.80
KDE Frameworks Version: 5.71.0
Qt Version: 5.14.2
Kernel Version: 5.6.11-1-MANJARO
OS Type: 64-bit
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 5700 XT 
```

```sudo fdisk -l```:
```
Disk model: SPCC Solid State
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 83F12BB1-6505-49B0-8226-72C7199A1E85

Device       Start        End    Sectors   Size Type
/dev/sdb1     2048    1050623    1048576   512M EFI System
/dev/sdb2  1050624 2000408575 1999357952 953.4G Linux filesystem
```

I can provide any other info if it is useful.

**Comment by drckeefe** [comment]
@FruityWelsh 

Thank you for reporting this issue and providing information on what is happening.  The output from "systemctl status stratisd"  has a message of "stratisd[962408]: Engine error: Failed to initialize DM context", which leads be to believe that either device mappers isn't installed or isn't loaded yet.   You could see if device mapper is loaded in the kernel with 'lsmod |grep dm_mod'
or see if the control character device has been created in /dev/mapper/control, which I believe means that device mapper is loaded in the kernel.  With out device mapper stratisd will not start. 

Here is an issue that describes the problem: 
https://github.com/stratis-storage/stratisd/issues/1751

Here is a bugzilla that might have some information for you on how to resolve the issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1782856

Please let us know how you turn out or if you are still having problems.

Take care.

**Comment by mulkieran** [comment]
I'll go ahead and close this in favor of #1751. Please let us know if you have any further questions.
