### ISSUE TITLE
Data structure sizes are bounded by max value of usize.

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#204]
For example, ```HashMap::capacity()```'s result type is ```usize```, indexing into a Vec requires a ```usize``` value and so forth. Probably a LinkedList is truly unbounded.

So "unlimited" is not a claim that we can make using most data structures in the standard library.
Probably making linked lists of other data structures would be workable, and usually the linked list would have just one node because 2^64 is a pretty big number, really.

**Comment by agrover** [comment]
True.

Is there a bug to fix here, or should we just be careful to not say "unlimited"?

**Comment by mulkieran** [comment]
I like to say unlimited whenever that can actually be true, as when there isn't a 64 bit slot in some statically sized metadata on disk to enforce the constraint.

For other reasons, I'm having to make purpose built data structures fo store various things. What this means is that th eproblems of thing sbeing limited by usize is encapsulated and could be addressed at a later time. I've devoted a small amount of thought to this, and it shouldn't be a super burden.

**Comment by agrover** [comment]
it is known.
