### ISSUE TITLE
Find out if we really need to handle Change udev events

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#2064]
If we do, we should. But, there are more of them than there are of Add events, and each one requires some processing. If it is a LUKS devices, even if not belonging to Stratis, an attempt must be made to read the LUKS header. If it is a stratis device, then the metadata is read from the device. If there is no purpose to all this, it would be better not to.

**Comment by jbaublitz** [comment]
Based on my testing, sometimes when devices become available, this is registered as a `change` event, not an `add` event. One particular example that I discovered was for loopback devices. Attaching a file to a loopback device registers as a `change` event. I understand that this is a very specific case, but my concern is that we may bump into other block device node types that trigger `change` events when storage has become available and it seems like removing the `change` handler will break this.

I do also want to make a note that currently wiping a Stratis block device using `wipefs -a [BLOCK_DEVICE_PATH]` will trigger a `change` event according to `udevadm` but generates no additional log messages from stratisd and does not remove this device from the `errored_pools` designation in the liminal devices data structure. I'm curious why this `change` event seems to have no effect on the stratisd internal state, and I may do some more digging to see if I can figure out why this is.

**Comment by jbaublitz** [comment]
I was able to track down the code path that leads to no logging and no action taken. Do we want to take any action if this happens?

**Comment by mulkieran** [comment]
@jbaublitz Let's talk about this code path.

**Comment by mulkieran** [comment]
Ooooh, turns out we don't remove devices if their signatures get wiped. Since they're unowned, we just ignore them when information is returned about their identity. Need a little restructuring there.

**Comment by mulkieran** [comment]
This is at least an unusual condition, so taking off any specific calendar.

**Comment by mulkieran** [comment]
Closing as duplicate of #2094
