### ISSUE TITLE
Repair primary sigblock or metadata copies if bad and secondary is ok

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#210]
We have two copies of both the sigblock in the static header, and the metadata also stores two copies in 2 MDA regions. If the first one is bad (CRC fails), we can read the second one. Should we then go back and rewrite the bad one immediately with the secondary copy?

This sounds like a good, "self-healing" kinda thing to do, but 1) it's work and 2) we probably want to think about this, maybe run it by others, to make sure this is really a good thing to do and not too clever by half.

**Comment by tasleson** [comment]
Related to: https://github.com/stratis-storage/stratisd/issues/826
