### ISSUE TITLE
Improve error message passed across the D-Bus when a needed key is missing

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2114]
Related to stratis-storage/stratis-cli#618
Discussion around this issue in stratis-storage/stratis-cli#619

We should check whether a key description exists in the keyring before trying to unlock a device so that we can provide an informative error message on the CLI side for the user if they are missing that key. It would be harder to inform the user if the key data that was provided is incorrect because all operations that could validate whether the key can open the device or not before actually opening the device could fail for a number of reasons. We can still discuss that option and see if there's a way to make the error messaging better when a device fails to open because currently I think it will simply return a libcryptsetup-rs error code with very little information.

**Comment by mulkieran** [comment]
This seems reasonable. Just a note that there's not an actual dependency between this proposed change and the changes in PR https://github.com/stratis-storage/stratis-cli/pull/619.
