### ISSUE TITLE
Use clippy to find casting and change to From and TryFrom conversions

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2117]
When testing down-casting integers on s390x, a big endian system, going from a u64 to a u32 appeared to truncate the last 32 bits of the integer which, in this case, contain all of the information that we're looking for. Casting between integers of the same width should not be a problem, but in the interest of making stratisd cross-platform and as safe as possible, we should enable the clippy lint about unsafe conversions between integers and try to use the `From` and `TryFrom` traits for integer conversions instead.

~- [ ] Confirm behavior on s390x~
- [ ] Enable clippy lint for integer conversions
- [ ] Change all casts to `From`/`TryFrom`

**Comment by mulkieran** [comment]
Note that the use of ```Try/TryFrom``` is to hand off the management of endianness to Rust. We would still in all places know that a narrowing conversion was safe, and so we would ```expect()``` it to succeed.

**Comment by mulkieran** [comment]
Note that we're talking about a bunch of lints that are in the pedantic category and that are not turned on by default. Currently the only special lint that we turn on is the "needless_borrow" lint, which is actually in the "nursery" category, not the "pedantic" category.

**Comment by mulkieran** [comment]
Related: https://github.com/stratis-storage/project/issues/97.

**Comment by mulkieran** [comment]
First thing is to confirm the s390x behavior.

**Comment by jbaublitz** [comment]
@mulkieran It turns out that this was a sneaky bug in libcryptsetup-rs tests that perhaps was only visible on s390x for architecture for platform specific reasons, but the failure based on the code that I had was indeed a bug. The PR that I put up for the release of 0.4.2 does indeed fix it but it is not related to endianness. Ultimately it was a problem with an expression such as:
```
let ptr = &mut 1 as *mut _ as *mut c_void
```
This is not normally a problem unless you then try to convert the pointer to a `&mut 64` reference as the compiler will automatically assign 32 bits to a bare integer constant without changing the above to:
```
let ptr = &mut 1u64 as *mut _ as *mut c_void
```
When I added a type to the integer constants, the tests passed even when converting from the pointer to a `u64`. This has already been fixed in libcryptsetup-rs but I'm going to put explicit types on the integer constants anyway just so that this doesn't come back in the future.

As for safe conversions, I still think this is a valuable code improvement even though the problem we originally thought we found with endianness is not a concern here. Would you like me to continue with this?

**Comment by mulkieran** [comment]
> @mulkieran It turns out that this was a sneaky bug in libcryptsetup-rs tests that perhaps was only visible on s390x for architecture for platform specific reasons, but the failure based on the code that I had was indeed a bug. The PR that I put up for the release of 0.4.2 does indeed fix it but it is not related to endianness. Ultimately it was a problem with an expression such as:
> 
> ```
> let ptr = &mut 1 as *mut _ as *mut c_void
> ```
> 
> This is not normally a problem unless you then try to convert the pointer to a `&mut 64` reference as the compiler will automatically assign 32 bits to a bare integer constant without changing the above to:
> 
> ```
> let ptr = &mut 1u64 as *mut _ as *mut c_void
> ```
> 
> When I added a type to the integer constants, the tests passed even when converting from the pointer to a `u64`. This has already been fixed in libcryptsetup-rs but I'm going to put explicit types on the integer constants anyway just so that this doesn't come back in the future.
> 
> As for safe conversions, I still think this is a valuable code improvement even though the problem we originally thought we found with endianness is not a concern here. Would you like me to continue with this?

I don't entirely follow your explanation here. Regarding adding in these casting lints...it seems like a good idea to me. But we should take the lints one at a time and move pretty carefully, since it looks like some flag quite a few lines of code and we'll want to be quite sure that we're doing the correct thing.

**Comment by mulkieran** [comment]
There was only one clippy lint in question, so we can add that flag and fix all the lints.

**Comment by jbaublitz** [comment]
@mulkieran Upon further review, I'm going to add three lints one at a time and see what the results are. They are:
* `cast_lossless`
* `cast_possible_truncation`
* `cast_possible_wrap`

I assume the last one would be more of a problem in something like `libcryptsetup-rs` but there's not a very good way to approach that there so I'll try it here.

**Comment by mulkieran** [comment]
Ok! I'm curious to see how this works out.

**Comment by jbaublitz** [comment]
`cast_possible_wrap` does not seem like a good lint to add. The places we do that in stratisd are mostly timestamp conversions, and they sometimes happen in methods that don't return errors so we can bubble up an error if it happens. Do we want to invest time in making that "safe" when the timestamps are already 64 bits in Rust? To me it seems like it might be a little excessive.

**Comment by mulkieran** [comment]
Pushing back to September...we don't need to move on this one now, for sure.

**Comment by mulkieran** [comment]
We can close this. We aren't certain that we want to work on cast_possible_wrap and we have since changed the Makefile to allow all the lints we don't obey.
