### ISSUE TITLE
For engine state report it would be nice to give a little more detail about the blockdevs

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#2125]
Currently, we only get publicly available information via Backstore's implementation of ```Into<Value>```. It might be time to go deeper and define ```Into<Value>``` on individual blockdevs.

Note: It would probably be handy if the key description were in the output of this report but it is not yet, Defining ```Into<Value>``` is probably the cleanest way to get this value into the output.

**Comment by jbaublitz** [comment]
I'm happy to pick this one up if you'd like.

**Comment by mulkieran** [comment]
@jbaublitz: thx, assigning.
