### ISSUE TITLE
Add a script to set the Stratis keys in the initramfs

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2134]
This process would involve creating another executable in `src/bin/` in the stratisd repo. This executable would use existing code from the engine in stratisd to set a key in the keyring and unlock locked devices.

Motivations
---------------
* This could be used to further develop inspection and repair tools that do not require a complete instance of stratisd to be running.
* This could also be useful to users when attempting to set up something like encryption in a semi-automated way at boot.

Steps
-------

- [x] Write an executable that uses the key infrastructure in stratisd to do key operations.
- [x] Do some investigation into getting user input from dracut-based initramfs booting.
- [x] Write a prototype of a dracut module that can query the user for passphrase input and unlock the locked crypt devices.
- [x] Test that booting from this initramfs does indeed unlock root encrypted filesystems without issue at boot.

**Comment by alexminder** [comment]
Would it be possible to support [Clevis](https://github.com/latchset/clevis) for automated decryption a filesystem and rootfs particular?

**Comment by mulkieran** [comment]
@alexminder We actually have an issue out for NBDE for block devices: https://github.com/stratis-storage/project/issues/192. It's a bit terse right now, but it will be acquiring more detail, probably in the fairly near future. But we don't support encryption of individual filesystems at all. That would be very much a separate issue. rootfs is also a larger story, although we have done some investigation there as well. When we have made a little more progress it will likely receive its own issue.

**Comment by alexminder** [comment]
@mulkieran  My interest is in TPM2 store for encryption keys which supported by Clevis.

**Comment by alexminder** [comment]
TPM2 will be native supported by cryptsetup without Clevis, soon. https://gitlab.com/cryptsetup/cryptsetup/-/merge_requests/51 .
Would you plan to implement TPM2 support in stratir and which way?

**Comment by mulkieran** [comment]
@alexminder Please file an issue for this in the project repo: https://github.com/stratis-storage/project/issues/new. We can track it there much better than in this issue, which has really rather limited scope and will probably close in a week.

Please include in the issue both the link you included in your comment and motivation, i.e., what would make this enhancement desirable.

**Comment by alexminder** [comment]
The issue have been created https://github.com/stratis-storage/project/issues/207 .

**Comment by mulkieran** [comment]
@alexminder Thanks!
