### ISSUE TITLE
Move use of KeyDescription type all the way up to the D-Bus layer

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2156]
After the `KeyDescription` type was moved up to a shared scope between the sim_engine and strat_engine, some return types for key descriptions were still left as `&str` or `String`. The conversion should be done in the D-Bus layer only.

**Comment by mulkieran** [comment]
@jbaublitz You would like to change the types of trait KeyActions methods so that they return or take an argument of a KeyDescription rather than an &str or String as the case might be?

**Comment by jbaublitz** [comment]
That's correct. I think the D-Bus layer should be responsible for these conversions (from strongly typed to D-Bus compatible data types).

**Comment by mulkieran** [comment]
Ok. Tentatively re-assigning.
