### ISSUE TITLE
encrypted pool missing after reboot

### ISSUE THREAD

**Issue by quininer** [stratis-storage/stratisd#2213]
I created an encrypt pool but I can't find it in `stratis pool list` after the system reboot. 

os: ArchLinux

| package | version
|---|---
| linux | 5.8.5.arch1-1
| cryptsetup | 2.3.3-1
| stratisd | 2.1.0-2
| stratis-cli | 2.1.1-2

stratisd.log
```
9月 06 15:42:25 haa stratisd[82792]: DEBUG libstratis::stratis::buff_log: BuffLogger: pass_through: true hold time: none
9月 06 15:42:25 haa stratisd[82792]:  INFO stratisd: stratis daemon version 2.1.0 started
9月 06 15:42:25 haa stratisd[82792]:  INFO stratisd: Using StratEngine
9月 06 15:42:25 haa stratisd[82792]:  INFO libstratis::engine::strat_engine::backstore::identify: Beginning initial search for Stratis block devices
9月 06 15:42:25 haa stratisd[82792]:  WARN libstratis::engine::strat_engine::backstore::crypt: Failed to get LUKS2 keyring JSON token; failed with error: IO error occurred: Invalid argument (os error 22)
9月 06 15:42:25 haa stratisd[82792]:  WARN libstratis::engine::strat_engine::backstore::crypt: Operations querying device to determine if it is a Stratis device failed with an error: IO error occurred: Invalid argument (os error 22); reporting as not a Stratis device.
9月 06 15:42:25 haa stratisd[82792]: DEBUG libstratis::engine::strat_engine::backstore::crypt: Stratis LUKS2 token: {"activation_name":"stratis-1-private-a4d29ba028114aacbe45d7d71e84bc01-crypt","device_uuid":"a4d29ba028114aacbe45d7d71e84bc01","keyslots":[],"pool_uuid":"0bc44c36709f4739ac3ed0822c01cbc6","type":"stratis"}
9月 06 15:42:25 haa stratisd[82792]:  INFO libstratis::engine::strat_engine::backstore::identify: LUKS block device belonging to Stratis with Stratis pool UUID: "0bc44c36709f4739ac3ed0822c01cbc6", Stratis device UUID: "a4d29ba028114aacbe45d7d71e84bc01", device number: "8:16", devnode: "/dev/sdb", key description: "bkey" discovered during initial search
9月 06 15:42:25 haa stratisd[82792]:  INFO libstratis::engine::strat_engine::liminal: Device information LUKS device belonging to Stratis with Stratis pool UUID: "0bc44c36709f4739ac3ed0822c01cbc6", Stratis device UUID: "a4d29ba028114aacbe45d7d71e84bc01", device number: "8:16", devnode: "/dev/sdb", key description: "bkey" discovered and inserted into the set for its pool UUID
9月 06 15:42:25 haa stratisd[82792]:  INFO stratisd: D-Bus API is available
```

**Comment by drckeefe** [comment]
quininer, you may have done this already, but after rebooting did you set the key and unlock the pools?  
startis key set ...
stratis pool unlock

**Comment by drckeefe** [comment]
If you have tried to set the key and unlock the pool, what is the output of lsblk?
Also
can you print the luks2 key description?
cryptsetup token export /dev/sdb --token-id 1

**Comment by mulkieran** [comment]
@drckeefe: The key description is also in the logs: "bkey"; the two should match.

**Comment by quininer** [comment]
Oops, I don’t know I need to manually unlock the pool. :'(

**Comment by mvollmer** [comment]
> Oops, I don’t know I need to manually unlock the pool. :'(

I think it would be nice if `stratis pool` would also list locked pools.

**Comment by mulkieran** [comment]
> > Oops, I don’t know I need to manually unlock the pool. :'(
> 
> I think it would be nice if `stratis pool` would also list locked pools.

We wouldn't do that, because the characteristics of a miscellaneous set of devices that look like they go together because they share the same pool UUID are too different from those of a properly constructed pool. But we are working on an atlernative: https://github.com/stratis-storage/stratisd/issues/2194.

**Comment by mulkieran** [comment]
@quininer: In the meantime, though, using the reports interface will give you some insight into what it going on w/ stratisd.

```
$ PYTHONPATH=./src ./bin/stratis report --help
usage: stratis report [-h] report_name

positional arguments:
  report_name  Name of the report to display

optional arguments:
  -h, --help   show this help message and exit
```

Our favorite report name is ```engine_state_report```.
