### ISSUE TITLE
stratis_uuids_to_names times out sometimes

### ISSUE THREAD

**Issue by mvollmer** [stratis-storage/stratisd#2220]
When creating a snapshot of a filesystem, the symlink for the original filesystem disappears, but `udevadm trigger` brings it back:

```
# ls /dev/stratis/pool3
myfs6
# stratis fs snapshot pool3 myfs6 myfs6@now
# ls /dev/stratis/pool3
myfs6@now
# udevadm trigger
# ls /dev/stratis/pool3
myfs6 myfs6@now
```

I can find this in the journal:

```
Sep 09 13:19:34 dev stratis_uuids_t[13797]: Could not convert Stratis UUIDs to names. "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
```

stratisd seems to be slow to reply to D-Bus messages when it is busy with something else, such as creating a filesystem or taking a snapshot.

It is possible to disable the timeout in `stratis_uuids_to_names` (and I would recommend that as a rule), but there is another timeout for udev rules.

I think this is another reason to stop relying on D-Bus in udev rules.

**Comment by mulkieran** [comment]
We will push up the D-Bus timeout ..which will reduce the incidence of the problem, although we recognize it won't eliminate it.
