### ISSUE TITLE
How and why did we choose the minimum device size?

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#224]
I ask, because it is kind of large for mocking for testing purposes, and tests mocked with even the minimum size as a vector take a lot of time. So, if the number was arbitrarily chosen and can be decreased that might help. Alternatively, the testing can make a mock blockdev that is less than the minimum size, with the usual caveats.

**Comment by agrover** [comment]
It was an estimation on my part. 1GiB seemed like a reasonable value. We can discuss if this value should be higher or lower but I think factors other than testing hurdles should be the main criteria.

(Next version of the design doc will document this value.)

**Comment by mulkieran** [comment]
" I think factors other than testing hurdles should be the main criteria".

Who, in their right mind, would think otherwise?
