### ISSUE TITLE
Provide a typed error for incorrect passwords on unlock for encrypted Stratis pools 

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2241]
Currently, the error when a password is entered incorrectly for an encrypted Stratis pool, stratisd returns `EINVAL` as a wrapped libcryptsetup-rs error. We need to investigate whether this can reliably tell us if a password was incorrect. This typed error can be leveraged in #2160 when integrating with plymouth for prompting users for passphrases at boot.

**Comment by jbaublitz** [comment]
This may be unnecessary as we have a working prototype of handling incorrect passwords in #2256.

**Comment by jbaublitz** [comment]
@mulkieran Want me to close this one out?

**Comment by mulkieran** [comment]
@jbaublitz ok, thx.
