### ISSUE TITLE
Cargo: bump proptest to 0.10

### ISSUE THREAD

**Issue by decathorpe** [stratis-storage/stratisd#2244]
I'm planning to update proptest in fedora to version 0.10.1 soon, and was told to report this upstream:
https://src.fedoraproject.org/rpms/stratisd/pull-request/1

The stratisd package in fedora compiles fine against proptest 0.10 without src code changes.

**Comment by mulkieran** [comment]
https://src.fedoraproject.org/rpms/rust-proptest/commits/master
