### ISSUE TITLE
Make it easy to work with sector offsets and sector lengths

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#230]
Much of Stratis is devices layered on top of other devices, and these are usually specified by lists of (parent_blockdev, offset, length). What can we do to make these easy to work with?

**Comment by mulkieran** [comment]
```
struct Segment {
    offset: Sectors,
    length: Sectors,
}
```

Define an operation on Segments:

Segment(01, l1) op Segment(o2, l2) => Segment(o1 + l1, l2)

This would work fine with the one use of ```avail_range()``` I'm looking at.

**Comment by agrover** [comment]
This doesn't seem like an issue any more, closing.
