### ISSUE TITLE
Make stratis_uuids_to_names go away entirely

### ISSUE THREAD

**Issue by drckeefe** [stratis-storage/stratisd#2307]
Building stratis_uuids_to_names in debug creates a file of 21M, without debug the file is about 2MB.  Other files in /usr/lib/udev
are typically not over 40K.  So, would it be possible to optimize this file?

**Comment by mulkieran** [comment]
We believe that, because the standard library is compiled in, there's a lower bound in size for a Rust application of about 2MiB. We'll keep an eye on this issue and see if there are introduced any tricks for making our apps smaller.

**Comment by mulkieran** [comment]
It turns out we don't need the script at all because we send synthetic events for all creation and rename events that will require the devlinks to change. We can include the information in the synthetic event, and not need to ask for information over the D-Bus.
