### ISSUE TITLE
stratisd does not detect devices as encrypted after switching from initramfs

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2312]
Liminal device code appears to have a problem with detecting already set up encrypted devices when switching from the initramfs. When stratisd-min sets up the encrypted pool and switches over to stratisd, stratisd reports the pool as unencrypted, only detecting the devicemapper devices through which the Stratis metadata is detected (e.g. /dev/dm-0, etc.). It does not detect the physical devices. When stratisd is restarted after having booted, it successfully detects that the pool is encrypted.

@mulkieran I'm happy to test out any code edits that you make in my environment if you'd like to take the lead on fixing this. I'm also happy to do some additional debugging if you need it.

**Comment by mulkieran** [comment]
@jbaublitz As you think it's possible that you're running into problems caused by this now, I'm giving it explicitly to you, rather than planning to address it myself.

**Comment by jbaublitz** [comment]
I was just looking into this. I'm happy to take this over.

**Comment by mulkieran** [comment]
@jbaublitz Has this been resolved by your researches or is it still an issue?

**Comment by jbaublitz** [comment]
I'm not ready to close this quite yet until I circle back and verify.

**Comment by jbaublitz** [comment]
I have not been able to reproduce this since making stratisd-min start for the time between exiting the initramfs and the D-Bus becoming available. I'm going to close this.
