### ISSUE TITLE
stratisd is failed on boot Centos 8

### ISSUE THREAD

**Issue by abrams21** [stratis-storage/stratisd#2313]
Hello, 
I installed 2 VMs with pure Centos 8, on both ienabled and enabled stratisd service.
It works when i start service manually but when I boot the OS - the status of stratisd is faield with following entries in journal:

`-- Reboot --
Nov 19 12:50:38 servera stratisd[637]: DEBUG libstratis::stratis::buff_log: BuffLogger: pass_t>
Nov 19 12:50:38 servera stratisd[637]:  INFO stratisd: Using StratEngine
Nov 19 12:50:39 servera stratisd[637]: Engine error: Failed to initialize DM context
lines 7504-7547/7547 (END)
`
When OS is booted and i try systemctl restart stratisd there is no issue:

`[student@servera ~]$ systemctl restart stratisd

[student@servera ~]$ 
[student@servera ~]$ 
[student@servera ~]$ systemctl status stratisd
● stratisd.service - A daemon that manages a pool of block devices to create flexible file sys>
   Loaded: loaded (/usr/lib/systemd/system/stratisd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-11-19 15:35:42 CET; 7s ago
     Docs: man:stratisd(8)
 Main PID: 5211 (stratisd)
    Tasks: 1 (limit: 23811)
   Memory: 4.6M
   CGroup: /system.slice/stratisd.service
           └─5211 /usr/libexec/stratisd --debug

Nov 19 15:35:43 servera stratisd[5211]:         },
Nov 19 15:35:43 servera stratisd[5211]:     },
Nov 19 15:35:43 servera stratisd[5211]:     incomplete_pools: {},
Nov 19 15:35:43 servera stratisd[5211]:     watched_dev_last_event_nrs: {},
Nov 19 15:35:43 servera stratisd[5211]: }
Nov 19 15:35:43 servera stratisd[5211]:  INFO stratisd: D-Bus API is available
Nov 19 15:35:43 servera stratisd[5211]: DEBUG libstratis::engine::strat_engine::thinpool::thin>
Nov 19 15:35:43 servera stratisd[5211]: DEBUG libstratis::engine::strat_engine::thinpool::thin>
Nov 19 15:35:43 servera stratisd[5211]: DEBUG libstratis::engine::strat_engine::thinpool::thin>
Nov 19 15:35:43 servera stratisd[5211]: DEBUG libstratis::engine::strat_engine::thinpool::thin>
lines 1-20/20 (END)
`
![obraz](https://user-images.githubusercontent.com/74722705/99680926-de130880-2a7d-11eb-821d-57140d90dc39.png)

**Comment by jbaublitz** [comment]
Hi @abrams21. Can you post the output of `cat /usr/lib/systemd/system/stratisd.service` here? I was just working on a similar problem in the initramfs and I might have a quick fix for you.

**Comment by abrams21** [comment]
Hello, 
sure:

`[root@servera ~]# cat /usr/lib/systemd/system/stratisd.service
[Unit]
Description=A daemon that manages a pool of block devices to create flexible file systems
Documentation=man:stratisd(8)
Before=local-fs-pre.target
DefaultDependencies=no

[Service]
Environment="RUST_BACKTRACE=1"
ExecStart=/usr/libexec/stratisd --debug
KillSignal=SIGINT
Restart=on-abort
StandardOutput=syslog
StandardError=syslog

[Install]
WantedBy=sysinit.target
[root@servera ~]# 
`

`erverb ~]# cat /usr/lib/systemd/system/stratisd.service
[Unit]
Description=A daemon that manages a pool of block devices to create flexible file systems
Documentation=man:stratisd(8)
Before=local-fs-pre.target
DefaultDependencies=no

[Service]
Environment="RUST_BACKTRACE=1"
ExecStart=/usr/libexec/stratisd --debug
KillSignal=SIGINT
Restart=on-abort
StandardOutput=syslog
StandardError=syslog

[Install]
WantedBy=sysinit.target
[root@serverb ~]# 
`

**Comment by jbaublitz** [comment]
So my guess is that the problem here is that `/dev/mapper/control` is not present when you boot, but it is when you restart. `WantedBy=sysinit.target` should be late enough for udev to have started and created `/dev/mapper/control` so I'm curious if the devicemapper device is loaded early enough in system initialization process. Can you look through `journalctl` and determine when relative to stratisd starting at boot the devicemapper module is loaded?

**Comment by abrams21** [comment]
Is it sufficient ?
If not please advice how to filter journal to get what you need



```
[root@servera ~]# cat new | grep stratis
Nov 19 16:00:05 servera stratisd[664]: DEBUG libstratis::stratis::buff_log: BuffLogger: pass_through: true hold time: none
Nov 19 16:00:05 servera stratisd[664]:  INFO stratisd: Using StratEngine
Nov 19 16:00:05 servera stratisd[664]: Engine error: Failed to initialize DM context
Nov 19 16:00:07 servera systemd[1]: Mounting /mnt/stratis_fs...
Nov 19 16:00:07 servera mount[935]: mount: /mnt/stratis_fs: special device /stratis/pool1/fs1 does not exist.
Nov 19 16:00:07 servera systemd[1]: mnt-stratis_fs.mount: Mount process exited, code=exited status=32
Nov 19 16:00:07 servera systemd[1]: mnt-stratis_fs.mount: Failed with result 'exit-code'.
Nov 19 16:00:07 servera systemd[1]: Failed to mount /mnt/stratis_fs.



[root@servera ~]# cat new | grep dm
Nov 19 16:00:03 localhost.localdomain kernel: ata1: PATA max UDMA/33 cmd 0x1f0 ctl 0x3f6 bmdma 0x1060 irq 14
Nov 19 16:00:03 localhost.localdomain kernel: ata2: PATA max UDMA/33 cmd 0x170 ctl 0x376 bmdma 0x1068 irq 15
Nov 19 16:00:05 servera kernel: device-mapper: ioctl: 4.39.0-ioctl (2018-04-03) initialised: dm-devel@redhat.com
Nov 19 16:00:05 servera systemd-modules-load[660]: Inserted module 'dm_mod'
Nov 19 16:00:06 servera systemd[1]: Started Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
Nov 19 16:00:07 servera systemd[1]: Listening on Podman Remote API Socket.
Nov 19 16:00:08 servera kernel: kvdo0:dmsetup: underlying device, REQ_FLUSH: not supported, REQ_FUA: not supported
Nov 19 16:00:08 servera kernel: kvdo0:dmsetup: Using write policy sync automatically.
Nov 19 16:00:08 servera kernel: kvdo0:dmsetup: loading device 'vdo1'
Nov 19 16:00:08 servera kernel: kvdo0:dmsetup: zones: 1 logical, 1 physical, 1 hash; base threads: 5
Nov 19 16:00:08 servera kernel: kvdo0:dmsetup: starting device 'vdo1'
Nov 19 16:00:08 servera kernel: kvdo0:dmsetup: Setting UDS index target state to online
Nov 19 16:00:08 servera kernel: kvdo0:dmsetup: device 'vdo1' started
Nov 19 16:00:08 servera kernel: kvdo0:dmsetup: resuming device 'vdo1'
Nov 19 16:00:08 servera kernel: kvdo0:dmsetup: device 'vdo1' resumed
Nov 19 16:00:08 servera dmeventd[1164]: dmeventd ready for processing.
Nov 19 16:00:08 servera UDS/vdodmeventd[1161]: INFO   (vdodmeventd/1161) VDO device vdo1 is now registered with dmeventd for monitoring
Nov 19 16:00:08 servera kernel: XFS (dm-0): Mounting V5 Filesystem
Nov 19 16:00:08 servera kernel: XFS (dm-0): Ending clean mount
Nov 19 16:00:09 servera kernel: Key type cifs.idmap registered
Nov 19 16:00:10 servera crond[1636]: (CRON) INFO (Syslog will be used instead of sendmail.)
Nov 19 16:00:10 servera gdm-autologin][1681]: pam_console(gdm-autologin:session): Could not open lock file /var/run/console/student, disallowing console access
Nov 19 16:00:10 servera systemd[1784]: Listening on Podman Remote API Socket.
Nov 19 16:00:10 servera gdm-autologin][1681]: pam_unix(gdm-autologin:session): session opened for user student by (uid=0)
[root@servera ~]# 
```

**Comment by jbaublitz** [comment]
Could you post the output of the following command just so I can see the ordering?
`journalctl -S "$(date -d 'Nov 19 16:00:03' +'%Y-%m-%d %H:%M:%S')" -U "$(date -d 'Nov 19 16:00:07' +'%Y-%m-%d %H:%M:%S')"`

What my guess is happening here is the following:
* See this diagram for the ordering of systemd targets: https://www.freedesktop.org/software/systemd/man/bootup.html
* /etc/fstab filesystems are supposed be mounted by the time `local-fs.target` is reached
* stratisd is getting started to fulfill this but has no `After=` directive specifying that it should start late enough that devicemapper is loaded and ready.
* stratisd fails to start because `/dev/mapper/control` is not present yet.

This may not be correct, but seems to match pretty closely with what I bumped into in the initramfs. Let me try reproducing this on a VM, and I will give you an edit to make to your `stratisd.service` file if I'm able to resolve it.

**Comment by abrams21** [comment]
Here is what you requested:

```
[root@servera ~]#  journalctl -S "$(date -d 'Nov 19 16:00:03' +'%Y-%m-%d %H:%M:%S')" -U "$(date -d 'Nov 19 16:00:07' +'%Y-%m-%d %H:%M:%S')"
-- Logs begin at Tue 2020-11-17 23:06:39 CET, end at Thu 2020-11-19 17:28:35 CET. --
Nov 19 16:00:03 localhost.localdomain kernel: usb 2-2: new full-speed USB device number 3 usin>
Nov 19 16:00:03 localhost.localdomain systemd[1]: Started udev Kernel Device Manager.
Nov 19 16:00:03 localhost.localdomain systemd[1]: Starting udev Coldplug all Devices...
Nov 19 16:00:03 localhost.localdomain systemd[1]: Mounting Kernel Configuration File System...
Nov 19 16:00:03 localhost.localdomain systemd[1]: Mounted Kernel Configuration File System.
Nov 19 16:00:03 localhost.localdomain kernel: usb 2-2: New USB device found, idVendor=0e0f, id>
Nov 19 16:00:03 localhost.localdomain kernel: usb 2-2: New USB device strings: Mfr=1, Product=>
Nov 19 16:00:03 localhost.localdomain kernel: usb 2-2: Product: VMware Virtual USB Hub
Nov 19 16:00:03 localhost.localdomain kernel: usb 2-2: Manufacturer: VMware, Inc.
Nov 19 16:00:03 localhost.localdomain kernel: hub 2-2:1.0: USB hub found
Nov 19 16:00:03 localhost.localdomain kernel: hub 2-2:1.0: 7 ports detected
Nov 19 16:00:03 localhost.localdomain systemd[1]: Started udev Coldplug all Devices.
Nov 19 16:00:03 localhost.localdomain systemd[1]: Starting dracut initqueue hook...
Nov 19 16:00:03 localhost.localdomain systemd[1]: Starting Show Plymouth Boot Screen...
Nov 19 16:00:03 localhost.localdomain systemd[1]: Started Show Plymouth Boot Screen.
Nov 19 16:00:03 localhost.localdomain systemd[1]: Started Forward Password Requests to Plymout>
Nov 19 16:00:03 localhost.localdomain systemd[1]: Reached target Paths.
Nov 19 16:00:03 localhost.localdomain kernel: tsc: Refined TSC clocksource calibration: 3500.0>
Nov 19 16:00:03 localhost.localdomain kernel: clocksource: tsc: mask: 0xffffffffffffffff max_c>
Nov 19 16:00:03 localhost.localdomain kernel: clocksource: Switched to clocksource tsc
Nov 19 16:00:03 localhost.localdomain kernel: Fusion MPT base driver 3.04.20
Nov 19 16:00:03 localhost.localdomain kernel: Copyright (c) 1999-2008 LSI Corporation
Nov 19 16:00:03 localhost.localdomain kernel: Fusion MPT SPI Host driver 3.04.20
Nov 19 16:00:03 localhost.localdomain kernel: e1000: Intel(R) PRO/1000 Network Driver - versio>
Nov 19 16:00:03 localhost.localdomain kernel: e1000: Copyright (c) 1999-2006 Intel Corporation.
Nov 19 16:00:03 localhost.localdomain kernel: e1000: E1000 MODULE IS NOT SUPPORTED
Nov 19 16:00:03 localhost.localdomain kernel: mptbase: ioc0: Initiating bringup
Nov 19 16:00:03 localhost.localdomain kernel: libata version 3.00 loaded.
Nov 19 16:00:03 localhost.localdomain kernel: ata_piix 0000:00:07.1: version 2.13
Nov 19 16:00:03 localhost.localdomain kernel: scsi host0: ata_piix
Nov 19 16:00:03 localhost.localdomain kernel: scsi host1: ata_piix
Nov 19 16:00:03 localhost.localdomain kernel: ata1: PATA max UDMA/33 cmd 0x1f0 ctl 0x3f6 bmdma>
Nov 19 16:00:03 localhost.localdomain kernel: ata2: PATA max UDMA/33 cmd 0x170 ctl 0x376 bmdma>
Nov 19 16:00:03 localhost.localdomain kernel: ioc0: LSI53C1030 B0: Capabilities={Initiator}
Nov 19 16:00:03 localhost.localdomain kernel: scsi host2: ioc0: LSI53C1030 B0, FwRev=01032920h>
Nov 19 16:00:03 localhost.localdomain kernel: MPTSPI MODULE IS NOT SUPPORTED
Nov 19 16:00:03 localhost.localdomain kernel: scsi 2:0:0:0: Direct-Access     VMware,  VMware >
Nov 19 16:00:03 localhost.localdomain kernel: scsi target2:0:0: Beginning Domain Validation
Nov 19 16:00:03 localhost.localdomain kernel: scsi target2:0:0: Domain Validation skipping wri>
Nov 19 16:00:03 localhost.localdomain kernel: scsi target2:0:0: Ending Domain Validation
Nov 19 16:00:03 localhost.localdomain kernel: scsi target2:0:0: FAST-40 WIDE SCSI 80.0 MB/s ST>
Nov 19 16:00:03 localhost.localdomain kernel: scsi 2:0:1:0: Direct-Access     VMware,  VMware >
Nov 19 16:00:03 localhost.localdomain kernel: scsi target2:0:1: Beginning Domain Validation
lines 1-44
```

Do you think when we fixed this on my VMs - should it be fixed in the code of stratid itself for future releases ?

**Comment by jbaublitz** [comment]
If I'm able to reproduce and fix the issue, the fix will certain be included in future releases.

**Comment by abrams21** [comment]
Does my last output put some more lłight on your understanding of the issue ?

FYI 
I have used latest Centos image - CentOS-8.2.2004-x86_64-dvd1

**Comment by jbaublitz** [comment]
Hi @abrams21. I've been unable to reproduce the issue. I went through the following steps on Centos 8.2:
```
# dnf install stratisd stratis-cli
# systemctl enable stratisd
# systemctl start stratisd
# stratis pool create testpool /dev/sdb
# stratis fs create testpool testfs
// Added /stratis/testpool/testfs to /etc/fstab
// Rebooted
# stratis --version
2.0.0
# stratis daemon version
2.0.0
```
I did not have any issues initializing the devicemapper context in stratisd.

Could you paste your `/etc/fstab` entry for the Stratis mount?

**Comment by abrams21** [comment]
I haven't  entries in /etc/fstab for stratis when i raised the issue. I have removed everything to test but the only service fails anyway

**Comment by abrams21** [comment]
Is there anything i can check to find the root cause of this error ?
Any setting to increase log level ?

**Comment by jbaublitz** [comment]
@abrams21 I assumed you had an entry in /etc/fstab if there's a `.mount` file in systemd. Did you write that `.mount` file?

Here are a few commands I'm going to ask you to run the output of:
```
$ sudo lsinitrd | grep dm
$ sudo lsinitrd | grep stratis
$ cat /path/to/mnt-stratis_fs.mount
```

Based on your previous log output, I'm beginning to wonder if you have the devicemapper module being loaded in the initramfs or after boot time. This could make a difference because if it's not loaded in the initramfs, there could be a race condition between the devicemapper module loading after exiting the initramfs and stratisd starting up. In your most recent output, I don't see any mention of devicemapper loading which seems to support my suspicion that it's not getting loaded in the initramfs as there is output from dracut and a switch to /sysroot but no mention of devicemapper. If this is indeed the case, I can provide a few suggestions. Send along the output when you get the chance, and I'll be happy to walk you through the steps.

**Comment by jbaublitz** [comment]
Hi @abrams21. I was able to reproduce the issue! Apparently, the following will produce this error:
* Installing Centos not on LVM but on standard partitions.
* Blacklisting dm-mod from the dracut initramfs
* Rebooting

If there is no `dm-mod` kernel module in your initramfs, my suspicion is that this is what's causing the issue. Did you install on standard partitions or LVM?

**Comment by abrams21** [comment]
Hello John, 
yes i have installed my CentOS on standard partitions as this is default in automated installation from VMWare Workstation
```
[root@serverb ~]# lsblk
NAME                                             MAJ:MIN RM  SIZE RO TYPE    MOUNTPOINT
sda                                                8:0    0   20G  0 disk    
├─sda1                                             8:1    0  300M  0 part    /boot
├─sda2                                             8:2    0    2G  0 part    [SWAP]
└─sda3                                             8:3    0 17.7G  0 part    /
sdb                                                8:16   0    5G  0 disk    
└─sdb1                                             8:17   0    5G  0 part    
  └─vgvdo-lvvdo                                  253:0    0   15G  0 lvm     
    └─vdob                                       253:1    0   12G  0 vdo     
sdc                                                8:32   0    5G  0 disk    
└─sdc1                                             8:33   0    5G  0 part    
  └─vgvdo-lvvdo                                  253:0    0   15G  0 lvm     
    └─vdob                                       253:1    0   12G  0 vdo     
sdd                                                8:48   0    5G  0 disk    
└─sdd1                                             8:49   0    5G  0 part    
  └─vgvdo-lvvdo                                  253:0    0   15G  0 lvm     
    └─vdob                                       253:1    0   12G  0 vdo     
sde                                                8:64   0   20G  0 disk    
└─stratis-1-private-b4fb8ce02580495388a313c7b94fc73f-physical-originsub
                                                 253:2    0   20G  0 stratis 
  ├─stratis-1-private-b4fb8ce02580495388a313c7b94fc73f-flex-thinmeta
  │                                              253:3    0   16M  0 stratis 
  │ └─stratis-1-private-b4fb8ce02580495388a313c7b94fc73f-thinpool-pool
  │                                              253:5    0   20G  0 stratis 
  │   └─stratis-1-b4fb8ce02580495388a313c7b94fc73f-thin-fs-441fb19128274268861466eee3332cf9
  │                                              253:7    0    1T  0 stratis 
  ├─stratis-1-private-b4fb8ce02580495388a313c7b94fc73f-flex-thindata
  │                                              253:4    0   20G  0 stratis 
  │ └─stratis-1-private-b4fb8ce02580495388a313c7b94fc73f-thinpool-pool
  │                                              253:5    0   20G  0 stratis 
  │   └─stratis-1-b4fb8ce02580495388a313c7b94fc73f-thin-fs-441fb19128274268861466eee3332cf9
  │                                              253:7    0    1T  0 stratis 
  └─stratis-1-private-b4fb8ce02580495388a313c7b94fc73f-flex-mdv
                                                 253:6    0   16M  0 stratis 
[root@serverb ~]# 
```
I read something about dm_mod in case of simmilar issues and i even added dm_mod entry in /etc/modules-load.d/ but there was no difference so i removed this entry
As you can see i have also VDO on my system and uses dm_mod 

[root@serverb ~]# lsmod | grep dm_mod
dm_mod                151552  29 kvdo,dm_thin_pool,dm_bufio

Anything i can change in configuration ? 
As you saw sometimes it works, i installed yet another completely fresh VM and did steps you mentioned to reproduce the issue and there was no issue yet. Anyway i really would like to fix it on my serverb machine and I hope - to allow you you to find and fix the issue in the code for future releases

**Comment by jbaublitz** [comment]
This is good to know, but please provide me the output of the requested commands. I need to see the contents of your initramfs to be able to help you further. Even if the module is loaded after exiting the initramfs, the race condition can still occur. I will discuss how we can resolve this with the team, but I'd like to verify that I understand the specific problem that you're bumping into before I do.

**Comment by abrams21** [comment]
Hello, 
sorry i missed your previous post about commands
I have created test filesystem and added it to fstab, i included this entry  below

Here is the output
```
[root@serverb ~]# sudo lsinitrd | grep dm
-rwxr-xr-x   1 root     root        80048 Apr 24  2020 usr/bin/dmesg
-rwxr-xr-x   1 root     root        68416 Apr 24  2020 usr/bin/findmnt
-rwxr-xr-x   1 root     root       434592 Apr 24  2020 usr/bin/udevadm
-rw-r--r--   1 root     root          708 Apr 24  2020 usr/lib/systemd/system/initrd-udevadm-cleanup-db.service
lrwxrwxrwx   1 root     root           14 Apr 24  2020 usr/sbin/udevadm -> ../bin/udevadm
[root@serverb ~]# sudo lsinitrd | grep stratis
[root@serverb ~]# grep stratis /etc/fstab 
#/stratis/pool1/fs1 /mnt/stratisb xfs defaults,x-systemd.requires=stratisd.service 0 0
[root@serverb ~]# 
```

**Comment by jbaublitz** [comment]
Okay, this is what I'd expect. Can you try rebuilding the initramfs using the following command, paste the output of the command, and try rebooting?

`$ sudo dracut --force -m dm`

Just for a little bit of background, we do currently need `dm-mod` in the initramfs. I'm in the process of discussing our approach around booting with my team so this will eventually be resolved upstream, but if my suggestion fixes the problem, I can provide you with a configuration file to add to your system so that it will work even on initramfs updates in the future through the package manager. Thanks for reporting this!

**Comment by jbaublitz** [comment]
@abrams21 Actually hold off on that command. I need to tweak it slightly.

**Comment by abrams21** [comment]
I ran the command, it generated no output and caused kernel panic on reboot

![obraz](https://user-images.githubusercontent.com/74722705/99812569-eaaf6380-2b46-11eb-9606-fc673249f36b.png)

shoudn;t it be` sudo dracut --force -m dm_mod ` ?

**Comment by abrams21** [comment]
> 
> 
> @abrams21 Actually hold off on that command. I need to tweak it slightly.

I did not noticed this before i ran the command

**Comment by abrams21** [comment]
OS can't boot in emergency and rescue targets for this kernel, same kernel panic
Can you asist with fixing it 
?

**Comment by jbaublitz** [comment]
Is this a virtual machine or remote machine? Do you have access to the disk?

**Comment by abrams21** [comment]
It is VM

**Comment by jbaublitz** [comment]
What you'll want to do is the following:
* Use another Linux VM that does boot (you said you have 2 Centos 8 VMs, so if the other one boots, that could be a good candidate)
* Attach the virtual disk image that is not booting to that VM (this will be heavily dependent on what kind of virtualization software you are using)
* Mount the root filesystem partition to a directory (I'll be using /mnt for the purposes of this example)
* `cd` into that directory (/mnt)
* Mount any additional partitions that you have (for example the partition housing /boot) at the appropriate places in the filesystem (e.g. mount /path/to/partition/with/boot /mnt/boot) - make sure that all partitions are mounted and mounted in the right place
* Run:
  * mount --t proc proc /mnt/proc
  * mount --rbind /sys /mnt/sys
  * mount --rbind /dev /mnt/dev
  * chroot /mnt /bin/bash
* From there you should have access to the filesystem that isn't booting
* Run ls /boot
  * This should display any initramfs files that you have in the non-booting boot partition
  * The filename should look something like this: `initramfs-[KERNEL_VERISON_STRING].img` based on what I see on my CentOS VM
* Run ls /lib/modules
  * Make sure that there is a directory there named the same thing as `[KERNEL_VERSION_STRING]`
* Run `dracut --kver=[KERNEL_VERSION_STRING] -a dm --force`

This should allow your virtual machine to boot again.

**Comment by abrams21** [comment]
Hello
I was able to do the fix by booting into older kernel version and executing command you provided

I also see that issue with stratisd is fixed and after reboots the service is running and filesystem is mounted based on fstab
```

[root@serverb ~]# uptime
 16:54:35 up 2 min,  1 user,  load average: 1.18, 0.90, 0.38
[root@serverb ~]# systemctl status stratisd.service | grep Active
   Active: active (running) since Fri 2020-11-20 16:52:12 CET; 2min 29s ago
[root@serverb ~]# mount | grep stratis
/dev/mapper/stratis-1-b4fb8ce02580495388a313c7b94fc73f-thin-fs-441fb19128274268861466eee3332cf9 on /mnt/stratisb type xfs (rw,relatime,seclabel,attr2,inode64,sunit=2048,swidth=2048,noquota,x-systemd.requires=stratisd.service)
[root@serverb ~]# 

```

**Comment by jbaublitz** [comment]
@abrams21 Excellent! The configuration that you can add to your system moving forward is the following file contents:
```
add_dracutmodules+=" dm "
```
in the file `/usr/lib/dracut/dracut.conf.d/03-stratis.conf`. Make sure to include the spaces on either side of `dm` in the file. That is important.

This will force dracut to add the devicemapper module to the initramfs. If you update your initramfs and you bump into the same problem with Stratis filesystems, you'll want to look for dm-mod in the initramfs (`lsinitrd | grep dm`). If it is not there, run `dracut /boot/initramfs-stratis.img`. This will create a separate initramfs without overwriting your old one. Check that the configuration file did indeed pull in `dm-mod` with `lsinitrd /boot/initramfs-stratis.img | grep dm`. From here you can reboot and manually test the initramfs from the Grub command line if you hit `c` before booting into any of the options. Once you've verified that it can boot, you can overwrite your initramfs with `/boot/initramfs-stratis.img`. Let me know if you have any other questions.

**Comment by abrams21** [comment]
Thanks a lot !

**Comment by mulkieran** [comment]
Thanks @abrams21 for your report!
