### ISSUE TITLE
We should discuss the systemd unit file in more depth as it relates to /etc/fstab

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2318]
Currently, systemd waits until stratisd acquires a name on the D-Bus to consider the service up and running. This introduces a dependency on dbus to be up and running. Eventually, this makes sense as stratisd-min can set up all of the filesystems in the initramfs. However, until the initramfs code is merged, we should have a longer conversation about the order in which stratisd should be started. Otherwise, /etc/fstab will be broken until we get stratisd-min packaged in the initramfs.

**Comment by mulkieran** [comment]
Related; #2313

**Comment by mulkieran** [comment]
@jbaublitz Can we close this one?

**Comment by jbaublitz** [comment]
Yes!
