### ISSUE TITLE
Issue with dracut networking

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2376]
I've opened an issue with dracut for the networking here: dracutdevs/dracut#1003.

**Comment by mulkieran** [comment]
@jbaublitz Do you have enough information to close out the dracut bug?

**Comment by jbaublitz** [comment]
No, we would like a way to wait on the network to come up.

**Comment by mulkieran** [comment]
@jbaublitz Is this fixed now?

**Comment by jbaublitz** [comment]
Yes, it should be.
