### ISSUE TITLE
Improve DataBlock

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#241]
Assuming #238, we have a `DataBlocks` type that is like Sectors and Bytes, but has a non-constant relationship to these because we can configure how many sectors are in each thinpool data block.

Because of this, we may want to take a slightly different approach to it -- store per-block size as well as overall count, perhaps? And devote thought to its methods in light of this difference.

**Comment by mulkieran** [comment]
This is now a tricky devicemapper problem.
