### ISSUE TITLE
RFE: Add LUKS device identification to LockedPools property

### ISSUE THREAD

**Issue by vojtechtrefny** [stratis-storage/stratisd#2423]
I'm currently working on encrypted pools support for the [Stratis installer support](https://github.com/storaged-project/blivet/pull/915) and I think the API around encrypted pools a little too complicated to use, especially when dealing with multiple pools. The `UnlockPool` method requires pool UUID which can be obtained from the `FetchProperties.r2` interface, but there is no information about the underlying LUKS devices. This is a problem for Blivet (and other storage tools like UDisks too). The usual use case is to detect a LUKS device and ask user for a passphrase to unlock it. This means we need to scan through the LUKS tokens on the device and parse the pool UUID from the stratis token JSON metadata. This is certainly possible but Stratis already does this (I assume) so adding UUIDs of LUKS devices to the `LockedPools` would make this way more user friendly.

**Comment by mulkieran** [comment]
A couple of notes:

1. We would generally like leaving it to Stratis to scan its metadata, rather than other tools that use Stratis, for sure.
2. The way we manage pools right now is that all devices are encrypted with the same KEK, and so their devices can be unlocked all at once.
3. We are hoping to put a more complete picture of sets of devices that could become pools on the D-Bus eventually.
4. In our current scheme, devices are not unlocked w/ a password directly. A per-pool key must be set in the kernel keyring, and the devices are unlocked by specifying the description of that key.

Our website https://stratis-storage.github.io/ has some useful articles, https://stratis-storage.github.io/stratis-release-notes-2-1-0/ and https://stratis-storage.github.io/stratis-release-notes-2-3-0/ about the current encryption implementation.

**Comment by vojtechtrefny** [comment]
> A couple of notes:
> 
>     1. We would generally like leaving it to Stratis to scan its metadata, rather than other tools that use Stratis, for sure.
> 
>     2. The way we manage pools right now is that all devices are encrypted with the same KEK, and so their devices can be unlocked all at once.

Yes, this is very helpful with a single pool, but doesn't really help with multiple pools encrypted with different keys.

> 
>     3. We are hoping to put a more complete picture of sets of devices that could become pools on the D-Bus eventually.

Having the backing LUKS devices on DBus with `blockdev` interface would be also good.

> 
>     4. In our current scheme, devices are not unlocked w/ a password directly. A per-pool key must be set in the kernel keyring, and the devices are unlocked by specifying the description of that key.
> 
I know, but we still need to ask user for a passphrase and save it to the keyring using `SetKey`. We don't expect users to do this themselves (especially in the installer environment).

**Comment by jbaublitz** [comment]
> A couple of notes:
> 
>     1. We would generally like leaving it to Stratis to scan its metadata, rather than other tools that use Stratis, for sure.
> 
>     2. The way we manage pools right now is that all devices are encrypted with the same KEK, and so their devices can be unlocked all at once.

@mulkieran Just a note that the KEK may differ per device, but the passphrase is the same. I think that PBKDF uses some additional parameters other than the passphrase (a salt for example).

> 
>     3. We are hoping to put a more complete picture of sets of devices that could become pools on the D-Bus eventually.
> 
>     4. In our current scheme, devices are not unlocked w/ a password directly. A per-pool key must be set in the kernel keyring, and the devices are unlocked by specifying the description of that key.
> 
> 
> Our website https://stratis-storage.github.io/ has some useful articles, https://stratis-storage.github.io/stratis-release-notes-2-1-0/ and https://stratis-storage.github.io/stratis-release-notes-2-3-0/ about the current encryption implementation.

> I know, but we still need to ask user for a passphrase and save it to the keyring using SetKey. We don't expect users to do this themselves (especially in the installer environment).

@vojtechtrefny One thing I've done in my initramfs-ready version of stratisd that has a different IPC mechanism is that I've exposed an option to pass a file descriptor for the `unlock` command as well. Would something like this be of interest.

**Comment by mulkieran** [comment]
Ok! We think we can extend the LockedPools result to include two pieces of information about the devices it appears to own, a device node and the device UUID.
