### ISSUE TITLE
Should we provide optional git hooks in our repo?

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2445]
Providing git hooks will not automatically enable them, but will provide users with the hooks and will only require one command that they need to run to enable them which may be helpful for some users.

**Comment by mulkieran** [comment]
What steps would they manage? Linting, formatting, other things?

I don't object so long as they don't turn into a maintenance burden.

Probably I myself would never use them.

**Comment by jbaublitz** [comment]
They would catch formatting, linting, compilation, or safe unit testing errors prior to making a commit, they would check Python linting and formatting, and abort if any of this failed.

**Comment by mulkieran** [comment]
Essentially, do the subset of what our CI requires that a user would feel comfortable doing on their personal machine? That seems fine to me.

Feel free to work on this whenever you find convenient.
