### ISSUE TITLE
Symlinks may not be created on boot

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2477]
When looking at #2475, I realized that we are now fully dependent on synthetic udev events for symlink creation. We have covered the case of filesystem creation, filesystem snapshots, filesystem renaming, and pool renaming, but we have not covered the case of filesystem setup. This could affect #2372 as we need the symlinks when stratisd starts.

**Comment by jbaublitz** [comment]
I've confirmed that this is an issue.

**Comment by mvollmer** [comment]
Please also take "udevadm trigger" into consideration, if you haven't already.

**Comment by jbaublitz** [comment]
@mvollmer It was just a missing udev change event. My understanding is that `udevadm trigger` doesn't provide the necessary interface that synthetic udev events do. We are actually sending pool name and filesystem name in the synthetic udev event so `udevadm trigger` wouldn't provide us with enough information. I'm working on fixing a bug in my udev rule now and this should be resolved.

**Comment by mvollmer** [comment]
> My understanding is that `udevadm trigger` doesn't provide the necessary interface that synthetic udev events do. We are actually sending pool name and filesystem name in the synthetic udev event so `udevadm trigger` wouldn't provide us with enough information.

Yes, that was my concern. What happens when people run `udevadm trigger`? Do the symlinks disappear?

**Comment by jbaublitz** [comment]
They wouldn't. I'm curious what your thoughts are, @mulkieran, but I don't think the symlinks necessarily need to be there if stratisd is not running. If stratisd is running, they are guaranteed to be there.

**Comment by mulkieran** [comment]
> They wouldn't. I'm curious what your thoughts are, @mulkieran, but I don't think the symlinks necessarily need to be there if stratisd is not running. If stratisd is running, they are guaranteed to be there.
> 
> < SNIP>

I believe that is sufficient, and could be considered even desirable.
