### ISSUE TITLE
Should try to break up crypt.rs at some time

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#2505]
It's 2000 lines, almost. We should try for some useful division. One possibility that occurred to me was to break out the support code that massages Clevis configuration info, but there's not really much of that.

**Comment by jbaublitz** [comment]
I've had my eye on this two. My recommendation:
* `shared.rs` for all of the helper methods not associated with a struct
* Optionally we can break up structs into their own module or do `setup.rs` for `CryptActivationHandle` and `CryptInitializer` and `handle.rs` for `CryptHandle`

How does that sound to you?

**Comment by mulkieran** [comment]
> I've had my eye on this too. My recommendation:
> 
>     * `shared.rs` for all of the helper methods not associated with a struct
> 
>     * Optionally we can break up structs into their own module or do `setup.rs` for `CryptActivationHandle` and `CryptInitializer` and `handle.rs` for `CryptHandle`
> 
> 
> How does that sound to you?

I think breaking up by structs might help us to stay the best organized in the long run. We can probably leave this until after the upcoming release unless it's very straighforward.
