### ISSUE TITLE
Support encrypted Stratis pools in /etc/fstab

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2530]
Currently, encrypted Stratis pools in /etc/fstab can be unlocked with custom configuration, but we should add a `.service` file to enable this and establish some best practices.

**Comment by aanno** [comment]
An alternative would be to use stratis on encrypted partitions. This is the setup I use for about 2 years now...

**Comment by jbaublitz** [comment]
@aanno Stratis manages that now.
