### ISSUE TITLE
fedora live cd - stratisd running but no /stratis

### ISSUE THREAD

**Issue by aanno** [stratis-storage/stratisd#2532]
I would like to upgrade/reinstall my fedora system with a 34 (beta) live cd, and hence trying to get stratis running with the live cd. This is easy - just install stratis-cli. Stratis seems to work (see below) BUT there is nothing in/at `/stratis` .

Is there something that I can do about that?

```
# stratis pool list
Name                               Total Physical   Properties
stratis_hdd   1.43 TiB / 453.45 GiB / 1011.38 GiB       Ca,~Cr

# stratis fs list
Pool Name     Name   Used         Created             Device                          UUID                            
stratis_hdd   opt    99.95 GiB    Apr 28 2019 06:30   /dev/stratis/stratis_hdd/opt    fb19a29eab394b418d370dc6d222a2b9
stratis_hdd   home   353.43 GiB   Apr 28 2019 06:29   /dev/stratis/stratis_hdd/home   17155095e2254fb0b020ec2ffa6a5e4d

 stratis blockdev list
Pool Name     Device Node   Physical Size    Tier
stratis_hdd   /dev/dm-8        292.95 GiB   Cache
stratis_hdd   /dev/dm-9          1.43 TiB    Data

 ls /dev/mapper/
control                stratis-1-093c8d4221b846a2a7e85d35f458fa58-thin-fs-17155095e2254fb0b020ec2ffa6a5e4d
fedora-00              stratis-1-093c8d4221b846a2a7e85d35f458fa58-thin-fs-fb19a29eab394b418d370dc6d222a2b9
fedora-root            stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-flex-mdv
fedora-thinpool        stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-flex-thindata
fedora-thinpool_tdata  stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-flex-thinmeta
fedora-thinpool_tmeta  stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-physical-cache
hdd-vg                 stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-physical-cachesub
live-base              stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-physical-metasub
live-rw                stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-physical-originsub
root                   stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-thinpool-pool
ssd-vg

```

**Comment by mulkieran** [comment]
Please look in /dev/stratis. We migrated most things there in stratisd 2.2.0.

**Comment by aanno** [comment]
Well, the problem is that there is no `/stratis` _and_ no `/dev/stratis/stratis_hdd/home` (or `/dev/stratis/stratis_hdd/opt` or even `/dev/stratis`) _even_ when `stratis fs list` says otherwise. Hence it is difficult use this volumes in the live cd install process...

**Comment by aanno** [comment]
Ah, I'm beginning to understand the problem:

```
# ls -l /dev/mapper/
insgesamt 0
crw-------. 1 root root 10, 236 17. Apr 07:34 control
lrwxrwxrwx. 1 root root       7 17. Apr 07:34 fedora-00 -> ../dm-5
lrwxrwxrwx. 1 root root       7 17. Apr 07:34 fedora-root -> ../dm-4
lrwxrwxrwx. 1 root root       7 17. Apr 07:34 fedora-thinpool -> ../dm-3
lrwxrwxrwx. 1 root root       7 17. Apr 07:34 fedora-thinpool_tdata -> ../dm-2
lrwxrwxrwx. 1 root root       7 17. Apr 07:34 fedora-thinpool_tmeta -> ../dm-1
lrwxrwxrwx. 1 root root       7 17. Apr 07:34 luks-8cfdfb51-cdfa-401a-9815-d3be9a527942 -> ../dm-0
lrwxrwxrwx. 1 root root       7 17. Apr 07:34 luks-stratis-hdd-vg -> ../dm-7
lrwxrwxrwx. 1 root root       7 17. Apr 07:34 luks-stratis-ssd-vg -> ../dm-6
lrwxrwxrwx. 1 root root       8 17. Apr 07:34 stratis-1-093c8d4221b846a2a7e85d35f458fa58-thin-fs-17155095e2254fb0b020ec2ffa6a5e4d -> ../dm-16
lrwxrwxrwx. 1 root root       8 17. Apr 07:34 stratis-1-093c8d4221b846a2a7e85d35f458fa58-thin-fs-fb19a29eab394b418d370dc6d222a2b9 -> ../dm-17
lrwxrwxrwx. 1 root root       8 17. Apr 07:34 stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-flex-mdv -> ../dm-15
lrwxrwxrwx. 1 root root       8 17. Apr 07:34 stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-flex-thindata -> ../dm-13
lrwxrwxrwx. 1 root root       8 17. Apr 07:34 stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-flex-thinmeta -> ../dm-12
lrwxrwxrwx. 1 root root       8 17. Apr 07:34 stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-physical-cache -> ../dm-11
lrwxrwxrwx. 1 root root       8 17. Apr 07:34 stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-physical-cachesub -> ../dm-10
lrwxrwxrwx. 1 root root       7 17. Apr 07:34 stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-physical-metasub -> ../dm-9
lrwxrwxrwx. 1 root root       7 17. Apr 07:34 stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-physical-originsub -> ../dm-8
lrwxrwxrwx. 1 root root       8 17. Apr 07:34 stratis-1-private-093c8d4221b846a2a7e85d35f458fa58-thinpool-pool -> ../dm-14

# ls -l /stratis/stratis_hdd/
insgesamt 0
lrwxrwxrwx. 1 root root 10 17. Apr 07:34 home -> /dev/dm-16
lrwxrwxrwx. 1 root root 10 17. Apr 07:34 opt -> /dev/dm-17
```

Hence I'm looking for `/dev/mapper/stratis-1-<number>-thin-fs-<number>`.

I still not understand why there is no such thing as `/dev/stratis/stratis_hdd/opt` _even on my current fedora system_ (runnig with stratis).

**Comment by mulkieran** [comment]
We would expect to see the ```/dev/stratis/stratis_hdd/opt``` link, also. There is a udev rule that should be triggered and a script that should be run in order to set that symlink. We believe that ```/dev/stratis``` does not exist because none of the links have been set (udev itself manages the directory).

Can you trigger the udev rule by causing a synthetic event on the Stratis filesystem?

```> echo change > /sys/dev/block/<major>:<minor>/uevent```

where major and minor are the Stratis filesystem major and minor numbers.

If that succeeds, then you should be able to proceed as normal. If not, the journal may show the cause, look particularly for log messages from ```stratis-uuids-to-names```.

**Comment by aanno** [comment]
Dear @mulkieran,

yes the `echo` stuff does the trick. Now it's:

```
# tree /dev/stratis
/dev/stratis
└── stratis_hdd
    ├── home -> ../../dm-16
    └── opt -> ../../dm-17
```

Before that, there wasn't anything like `/dev/stratis` at all...

**Comment by mulkieran** [comment]
> Dear @mulkieran,
> 
> yes the `echo` stuff does the trick. Now it's:
> 
> ```
> # tree /dev/stratis
> /dev/stratis
> └── stratis_hdd
>     ├── home -> ../../dm-16
>     └── opt -> ../../dm-17
> ```
> 
> Before that, there wasn't anything like `/dev/stratis` at all...

Great! Likely there was some problem related to the script not being able to communicate w/ stratisd over the D-Bus at an early stage. We've improved the management of the symlinks in stratisd 2.4.0, so that there is no longer any reliance on the D-Bus, and we believe the new approach will prove more robust.

**Comment by mulkieran** [comment]
Please feel free to contact us if you have any additional difficulties.
