### ISSUE TITLE
need to deal with any thin_id collisions

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#257]
should replace with proper id generation. DM takes a 24 bit number for the thin_id.  Generate a u16 to avoid the possibility of "too big". Should this be moved into the DM binding (or lower)?

 How can a client be expected to avoid collisions?

**Comment by agrover** [comment]
A client must keep track of all in-use ids, it must ensure a new thinvol has an unused id. Because of this I don't think it's possible to hide this from the client.

**Comment by trgill** [comment]
I see.  

So we could just use a counter?  I was thinking it was a "kernel" id.

**Comment by mulkieran** [comment]
Technical detail: For greater randomness, it would be better to generate random u32 and shift it right. Or possibly, dm stuff somehow truncates a 32 bit value, so there is no work to be done.

**Comment by mulkieran** [comment]
This is resolved by #415.
