### ISSUE TITLE
[question] Does stratis store a full file on a single disk or strip it (in case on hard drive failure)

### ISSUE THREAD

**Issue by kocoten1992** [stratis-storage/stratisd#2570]
Hi stratis team, thank you for this software :smiley: , I have a few questions:

- Do we store a full file on a disk or strip it across disk like raid 0 (it is important in case hard drive failure). I dont know how stratis will behave when hdd failure happen ?
- We dont have remove disk command (we have one for add-data, but I cant find the opposite), do we have plan to support this ? In case for planned remove too old drives.

**Comment by drckeefe** [comment]
@kocoten1992 Today Stratis doesn't have a data protection layer.  It is recommended that a software or a hardware RAID be used below Stratis.  Devices are concatenated together when added to a Stratis pool, so data will be written to the first device and when that device is full, data will be written to the next device which was added to the pool.  Currently there is no option to remove a device from a Stratis pool, it is expected that removing a device be performed at the RAID layer.

**Comment by kocoten1992** [comment]
Thank you!

Last question, do we planning to support that in the future ?

**Comment by drckeefe** [comment]
Data protection is a feature Stratis would like to offer and it is being investigated.
