### ISSUE TITLE
revisit hard coded data blocksize and low water mark

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#259]
Should be more adaptive to what make sense.

**Comment by mulkieran** [comment]
I think these means that these values should not be constants, but instead configurable.

**Comment by agrover** [comment]
low water mark will not be using a hardcoded value, see https://github.com/stratis-storage/stratisd/issues/1083.

That leaves hardcoded data blocksize as a question. For 1.0, the answer is surely no. Beyond that.. maybe someday?

Going to close this issue, we can revisit in the future.
