### ISSUE TITLE
Should we make a better effort to roll back encryption operations?

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2610]
After reviewing some of the encryption operations like unbinding, I noticed that I did not attempt to roll back operation as they may not be able to be rolled back successfully. I have some ideas for how to attempt to roll some of them back if they fail by doing some prechecks before attempting to roll them back. This may give us better consistency if a requested operation fails.

**Comment by mulkieran** [comment]
Note that we dropped an assertion that no longer held true in #2612. If this is true, the encryption info is the same for every device. But if it is possible for binding to fail, then the encryption info may not be the same for every device, and we should understand how to deal with that possibilty.

**Comment by jbaublitz** [comment]
@mulkieran In #2604, I'm going to assume for rollback that the state is consistent at the beginning given that stratis-storage/project#310 will guarantee that once we implement that. Since I'm going to try to work on that next, are you okay with this assumption as long as we get it in before the next release?

**Comment by mulkieran** [comment]
> @mulkieran In #2604, I'm going to assume for rollback that the state is consistent at the beginning given that [stratis-storage/project#310](https://github.com/stratis-storage/project/issues/310) will guarantee that once we implement that. Since I'm going to try to work on that next, are you okay with this assumption as long as we get it in before the next release?

That makes sense to me.
