### ISSUE TITLE
devicemapper requires an initial size for a thin provisioned device.

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#262]
But we don't require a size to be provided for create_filesystem.  We should figure this out.

**Comment by agrover** [comment]
Yes, we need to pick a starting value. How about 1G?

**Comment by agrover** [comment]
actually, after talking to XFS devs, they recommend 1TiB.

**Comment by trgill** [comment]
Decided on 6/1 to make the initial size 1TiB.

**Comment by mulkieran** [comment]
And 1 TiB it now is, in ```ThinPool::make_thin_device()```.
