### ISSUE TITLE
In Rust 1.53 bindgen emits bindings that are rejected by the compiler

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#2658]
Sample error, they seem to be all the same:

```
error: dereferencing a null pointer
    --> /__w/stratisd/stratisd/target/debug/build/libstratis-2db48ea0cb163798/out/bindings.rs:3685:19
     |
3685 |         unsafe { &(*(::std::ptr::null::<__va_list_tag>())).reg_save_area as *const _ as usize },
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this code causes undefined behavior when executed
```

**Comment by mulkieran** [comment]
Related https://github.com/stratis-storage/stratisd/pull/2657

**Comment by jbaublitz** [comment]
This looks like a totally valid error on the part of the Rust compiler. What would be most helpful for me to look into? My initial thoughts are that this is most likely worthy of a bug report against bindgen, but I can do more investigation and report back here.

**Comment by mulkieran** [comment]
@jbaublitz Ok! Looks like they've known about it, the trail seems to start here: https://github.com/rust-lang/rust-bindgen/issues/2049. If the best plan is to ```allow``` it for now, we can just go ahead and do that, but we should make a note to stop allowing when bindgen gets in a fix.

**Comment by jbaublitz** [comment]
After reading up on the issue, it seems like allowing it for now seems like the best option.

**Comment by mulkieran** [comment]
Ok! Plz go ahead.

**Comment by mulkieran** [comment]
Taken care of by #2659 and similar PRs in other repos.
