### ISSUE TITLE
Find sizes of property return values for various stratisd D-Bus objects

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2700]
It appears that while Unix sockets can't be sniffed, `dbus-monitor` allows sniffing D-Bus traffic to determine the size of the property hashes for various D-Bus objects.

I'll be using `dbus-monitor --system --pcap > pcapfile` to output something readable by wireshark and then reporting the sizes of various D-Bus objects here in this issue in an attempt to determine what the limit is for pools, filesystems, and block devices based on D-Bus's 128MiB limit for packets.

I'll most likely be using `busctl` commands to dump the properties of individual objects and checking this against `GetManagedObjects` for all of the resources.

**Comment by jbaublitz** [comment]
Blockdev properties packet size: around 400 bytes
Pool properties packet size: around 200 bytes
GetManagedObjects reply packet with 1 pool and 2 block devices: 4769 bytes

**Comment by jbaublitz** [comment]
Minimum size seems to be about 104 bytes.

Updated values:
Pool properties packet size: 177 bytes
pool with:
name "testpool"
block devices /dev/thisdevice, /dev/that/device

Blockdev properties packet size: 361 bytes
for both blockdevs /dev/thisdevice and /dev/that/device

Filesystem properties packet size: 337 bytes
with:
name testfsssssssssssssssss

Total GetManagedObjects return size: 5808 bytes

**Comment by mulkieran** [comment]
This is good information. We've our decision to move to standard D-Bus properties, closing.
