### ISSUE TITLE
/etc/fstab entry devicemapper set up failure

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2749]
When switching from stratisd-min to stratisd, stratisd will occasionally fail to set up the linear device and generate similar to the following error messages for device entries in `/etc/fstab`. We need to figure out why this is happening and see if we can resolve the difference between the initial set up by stratisd-min and the parameters determined by stratisd. This is particularly interesting due to the fact that stratisd-min will set up `/etc/fstab` entries after switching the root and exiting the initramfs and stratisd-min is using the same engine code as stratisd.

```Aug 17 14:55:17 fedora stratisd[1752]: [2021-08-17T18:55:17Z INFO  stratisd::engine::strat_engine::liminal::device_info] Device information LUKS device description: Stratis pool UUID: "52fc9bdb-bc45-49b7-b231-c299a2b2e3f8", Stratis device
 UUID: "613ee39c-8d86-4aba-b6d5-be0607cfb170", device number: "252:64", devnode: "/dev/vde", key description: "fstabkey", no Clevis information discovered and inserted into the set for its pool UUID
Aug 17 14:55:17 fedora stratisd[1752]: [2021-08-17T18:55:17Z INFO  stratisd::engine::strat_engine::liminal::device_info] Device information Stratis device with logical device with Stratis pool UUID: "52fc9bdb-bc45-49b7-b231-c299a2b2e3f8",
 Stratis device UUID: "613ee39c-8d86-4aba-b6d5-be0607cfb170", device number: "253:10", devnode: "/dev/dm-10" and physical device with Stratis pool UUID: "52fc9bdb-bc45-49b7-b231-c299a2b2e3f8", Stratis device UUID: "613ee39c-8d86-4aba-b6d5
-be0607cfb170", device number: "252:64", devnode: "/dev/vde", key description: "fstabkey", no Clevis information replaces previous device information for the same device UUID in the set for its pool UUID
Aug 17 14:55:17 fedora stratisd[1752]: [2021-08-17T18:55:17Z DEBUG stratisd::engine::strat_engine::backstore::crypt::shared] Stratis LUKS2 token: {"activation_name":"stratis-1-private-613ee39c8d864abab6d5be0607cfb170-crypt","device_uuid":"613ee39c-8d86-4aba-b6d5-be0607cfb170","keyslots":[],"pool_uuid":"52fc9bdb-bc45-49b7-b231-c299a2b2e3f8","type":"stratis"}
Aug 17 14:55:17 fedora stratisd[1752]: [2021-08-17T18:55:17Z INFO  stratisd::engine::strat_engine::liminal::liminal] Attempt to set up pool failed, but it may be possible to set up the pool later, if the situation changes: An attempt to set up pool with UUID 52fc9bdb-bc45-49b7-b231-c299a2b2e3f8 from the assembled devices failed: DM error: DM error: Invalid: Specified new table "LinearDevTargetTable { table: [TargetLine { start: Sectors(0), length: Sectors(32768), params: Linear(LinearTargetParams { device: Device { major: 253, minor: 11 }, start_offset: Sectors(0) }) }] }" does not match kernel table "LinearDevTargetTable { table: [TargetLine { start: Sectors(0), length: Sectors(32768), params: Linear(LinearTargetParams { device: Device { major: 253, minor: 11 }, start_offset: Sectors(32768) }) }] }"```

**Comment by jbaublitz** [comment]
Just confirmed that this is not reproducible 100% of the time.

**Comment by jbaublitz** [comment]
@mulkieran @bgurney-rh I'd definitely like to get your thoughts here because this is quite a strange bug. It appears that it is timing related and specifically happens when setting up the metadata device linear target.

So far I've determined:
* It only happens when setting up pools in `/etc/fstab`
* The devicemapper values are consistent with the spare metadata section in the MDA in the failure case
* The devicemapper values are consistent with the metadata section in the MDA in the success case
* If I immediately type in the password and unlock the `/etc/fstab` device, the set up will fail
* If I wait a number of seconds prior to typing in the password, the set up will succeed

I'm unsure if the failure case corresponding to the information in the spare metadata section is just a coincidence, but even if it is, I'm at a loss for why timing might impact the parameters passed to devicemapper when setting up the metadata device. That should be determined directly from the block device metadata so my thought here is that timing of when I unlock the device should not at all impact the result of the devicemapper table.

**Comment by jbaublitz** [comment]
Interesting! After looking at the code, this will happen if `thin_check` fails. Let me do some digging and see if I can determine the cause of the thin check failing in this case with some logging.

**Comment by jbaublitz** [comment]
This actually is due to the combination of systemd and the fact that we shut down stratisd-min and then bring up stratisd. Apparently, systemd kills the entire control group by default which includes the spawned `thin_check` process if the timing works out that way. Subsequently, because stratisd will handle `SIGTERM`, stratisd-min will recognize the failure, use the spare metadata space changing the devicemapper table, and then exit. This leaves the metadata device in a bad state for when stratisd comes up because the `thin_check` command will not fail in that case which will cause stratisd to error out when trying to set up the pool the second time.

@mulkieran My recommendation is that we change the systemd kill setting to only target the stratisd and stratisd-min processes as we can handle those whereas we cannot guard against `SIGTERM` in fork-exec processes. What are your thoughts?

**Comment by mulkieran** [comment]
@jbaublitz Can you post the text of the error from ```thin_check``` that you saw?

**Comment by mulkieran** [comment]
@jbaublitz Just thinking that it might also be possible to use separate ```StratisError``` constructors for the errors from the ```execute_cmd``` call and always skip ```thin_repair``` call if ```thin_check``` call errored for a reason not having to do w/ corrupted metadata. I _think_ that we can distinguish that pretty well in ```execute_cmd```. Note that there's been a ```TODO``` about that for a while; firing off ```thin_repair``` regardless is an obvious flaw.

For this particular source of the problem, I follow the idea of your solution but not the implementation. Do we have ```stratisd``` and ```stratisd-min``` respond to a different signal, specified in their service files?

**Comment by jbaublitz** [comment]
Hi @mulkieran, here are the logs!

```
Aug 18 17:31:01 fedora systemd[1]: Stopping Stratis minimal daemon...
Aug 18 17:31:01 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=stratis-fstab-setup@52fc9bdb-bc45-49b7-b231-c299a2b2e3f8 comm="systemd" exe="/usr/lib/systemd/systemd" hos
tname=? addr=? terminal=? res=success'
Aug 18 17:31:01 fedora kernel: audit: type=1131 audit(1629322261.866:116): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=stratis-fstab-setup@52fc9bdb-bc45-49b7-b231-c299a2b2e3f8 comm="systemd" exe="
/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 18 17:31:01 fedora stratisd-min[1571]: [2021-08-18T21:31:01Z WARN  stratisd::engine::strat_engine::thinpool::thinpool] Thin check failed: Command failed: cmd: "/usr/sbin/thin_check" "-q" "/dev/dm-12", exit reason: process terminated b
y signal stdout:  stderr:
```

The log about stopping stratisd-min gives me confidence around my initial guess at what's happening.

As for distinguishing between errors, how do you propose doing that? It looks like the exit reason is potentially programmatically available so that may be one option. I'm assuming we're both in agreement about not try to parse error messages based on previous conversations. Did you have something else in mind?

I'm definitely happy to discuss other options if you would rather kill the thin check than let it complete. My argument for not killing subprocesses was because in stratisd, we make sure not to exit partway through operations through our handling of signals. Not sending signals to commands would be a consistent choice with how we handle things in stratisd. My main worry about sending signals to processes that we've shelled out to is that if we ever decide to run an operation the background that accepts signals and causes inconsistencies or corruption in storage if interrupted partway through, then we would leave ourselves vulnerable to this same problem with more destructive consequences in the future.

Personally, my ideal option would be to send signals to child processes from stratisd if we need to kill something off with `SIGTERM` or even less gracefully with another signal. That way we have control over it and don't accidentally cause behavior like what we're seeing in this issue.
