### ISSUE TITLE
Thin provisioning rework proposal

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#2814]
Recently we've bumped into some reliability and usability problems with our thin provisioning solution. Some of the notable problems, some of which have been resolved, are:
* Filesystem extension not being triggered
* Imprecise metadata size calculation
* No guard rails for out of space conditions on the thin pool

After a number of discussions with the LVM team and other storage engineers, I'm suggesting the following changes:
* Decoupling filesystem extension from the thin pool low water mark (this change has already been merged)
  * We have added a timer to periodically check for the need to extend the filesystem.
  * Thin devices have sizes, but the size is not constrained by physical storage so there is no event to listen for when the thin device (and filesystem on top of it) begins to run out of space.
  * Previously, relying on the low water mark alone could occasionally cause the filesystem extension to fail and the filesystem would fill up before resizing was retried.
* Switch to lazy allocation for the data and metadata thin pool device
  * Currently, our metadata calculation is simply 1/1000th of the total available space.
  * The proposed solution involves the following:
    * Allocate data and metadata device space as needed.
    * Disable flush on device extension. This involves disabling flush on suspend, extending the table and allocating the storage from the cap device, and disabling flush on resume. This will prevent unnecessary IO storms on device extension.
    * Data device extension will be triggered by the thin data device low water mark and metadata extension will be calculated accordingly.
    * We do not need to listen for the metadata low water mark because of the restrictions below on metadata growing operations.
    * The benefit of this is increased flexibility around usage allocated to data and metadata space depending on whether data device size and number of filesystems on the pool changes over time.
* For metadata extension, this can be triggered by either growing the data device (background) or increasing the limit on thin devices (IPC request). We will disable filesystem creation and data device extension if the metadata device cannot be extended accordingly.
  * Calculate the necessary metadata space using the `thin_metadata_size` tool, and resize the metadata accordingly.
  * This allows us to disregard the metadata device low water mark because we will always be guaranteed to have enough space for metadata operations.
  * Add a limit on thin devices that can be created on a specific pool to ensure that the user does not create more thin devices than there is room to record metadata for.
* D-Bus API:
  * Writable property for limit on filesystems for a pool. Changing the value may cause a metadata device resize.
    * This limit will be applied to the pool on filesystem creation and any attempt to create more filesystems than the limit allows will be prevented.
  * (Optional) Writable property for data device resize allocation size (how much the data device should grow when it begins to run out of space)
    * This would change how much the data device is extended at one time.
    * This tunable may be a bad idea as it could have unintended consequences depending on how large the extension is.
    * For example, a large data device extension at one time with a small amount of storage could prevent future metadata extensions.
    * Perhaps we could provide some guidance or validation of what is allowed based on the amount of physical storage available. 
  * Writable property for space left in data device before signal is triggered indicating an out of space condition.
    * This limit indicates is a number indicating how much free space is left to be allocated to the thin pool data device when stratisd sends out a signal to tell users to stop writing to filesystems on the pool altogether.
  * Signal indicating that no more space is left to be allocated to and further writes has the possibility of causing serious failure states.
    * This signal will be sent out when the space left in the data device is equal to the value of the above property and can be used to cease writes in applications.
    * We cannot enforce that applications will stop writing so this should be a major highlight in documentation.
    * This solution will not work very well for something like a root filesystem as applications will not be listening for this signal.
    * Preventing overprovisioning should be the default if there is no ability to ensure that all applications will stop writing when this signal is triggered.
* We are also proposing a mode that denies overprovisioning in the case where (for example, the root filesystem) we cannot reliably expect all daemons to listen for the low space signal outlined in the D-Bus API section.
  * This will guarantee that out of space conditions are never reached on the data device by only allowing filesystem and snapshot total logical size that is less than or equal to the total available space.
  * The major drawback of this mode is decreased space efficiency.

Notes:
* We are exploring other options for thin provisioning safety in the future.
  * Overwriting data that is shared between a filesystem and a snapshot can cause the snapshot and filesystem to diverge. This will trigger a copy on write in the thin pool, not the filesystem, and thus a new allocation in the thin pool data device. We cannot stop overwriting data that has already been allocated by the filesystem as the filesystem relies on this space already being allocated and does not need a new allocation internally. The thin pool layer where the snapshots are implemented, however, could fill up simply from overwrites.
  * If a filesystem and snapshot are identical, all blocks will be shared. Let's say we overwrite all allocated data on the filesystem and the snapshot stays the same. This doubles the amount of storage needed in the thin pool simply from overwriting data in the filesystem due to the need to now map the two divergent blocks instead of sharing the mapping. If a thin pool is already running out of space, this could cause an out of space condition very easily. 
  * Overprovisioning (making a larger filesystem than there is physical storage to house the entire filesystem if it were full) and snapshots together can cause this to happen so users must proceed with caution.
  * The major benefit of overprovisioning with snapshots is increased storage efficiency when blocks are shared between a snapshot and a filesystem.
  * The drawback is increased risk.

**Comment by mulkieran** [comment]
Resolved by merged PRs.
