### ISSUE TITLE
When stratisd fail to create a snapshot it leaves mount in /tmp behind

### ISSUE THREAD

**Issue by bleve** [stratis-storage/stratisd#2824]
Environment: rhel8 based distro, stratis-cli-2.3.0-3.el8, stratisd-2.3.0-2.el8

When running command:

stratis filesystem snapshot tuomo home 20211026-0410-snap-home

stratisd gives error:
Execution failed:
stratisd failed to perform the operation that you requested. It returned the following information via the D-Bus: ERROR: Nix error: EBUSY: Device or resource busy.
And leaves behind this mount:

/dev/dm-12        1073217536  7517520 1065700016   1% /tmp/stratis_mp_xd1UUi

**Comment by mulkieran** [comment]
Ok! I'm going to reopen this and we'll see what we can find out. We would not expect stratisd to return until the requested snapshot was completed, so that's not likely to be the cause.

**Comment by mulkieran** [comment]
Actually, @bleve, are you running a released version, or checking stratisd out from the repo? #2942 will make it into the next release, 3.1.0.

**Comment by bleve** [comment]
I'm running rhel8 version.

**Comment by mulkieran** [comment]
Ok! If you run into the same trouble with stratisd 3.1.0 plz reopen, otherwise we'll assume this one is fixed.

**Comment by jbaublitz** [comment]
@mulkieran I'm not sure if we retry snapshot unmounts yet. Do you want me to take a look?

**Comment by mulkieran** [comment]
@jbaublitz I was assuming problems with the mdv all through. But the snapshot itself could be the culprit here, good point. I'll reopen and the plan will be to add a retry on the conditional snapshot unmount as well. Good thought.
