### ISSUE TITLE
test_prediction_encrypted is failing regularly because it finds a pool created in previous test on startup

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#2825]
test_prediction runs before test_prediction_encrypted; the pool it creates and which should have been destroyed by the UdevTest cleanup mechanism, which removes all DM devices and loopbacked devices, does not seem to completely destroy the devices or does not complete before the second test is run.

**Comment by jbaublitz** [comment]
Another note is that as seen here:

https://github.com/stratis-storage/stratisd/runs/4255926408?check_suite_focus=true

lazy allocation will break this.

**Comment by mulkieran** [comment]
We will remove the tests for the lazy allocation PR, so they will stop failing, and this will become obsolete. We do still have a more generic problem w/ the udev tests and loopbacked devices, though.
