### ISSUE TITLE
find_all() method crashed my machine when running as root

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#286]
It doesn't seem to cause any trouble when running not as root.

I was running it as root because my loopbacked tests required it.

What is the stance we take about running stratisd as root?

**Comment by mulkieran** [comment]
We do. I guess I'm wondering now, if stratisd runs as root, can clients not running as root make it do whatever they want over the D-Bus? How should we express any restrictions on them, and whose job is it?

**Comment by agrover** [comment]
see #381
