### ISSUE TITLE
Incomplete pools on setup

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#293]
From discussion on 4/4/2017

Should we keep a list of pools we expect to be in a good state at the next startup?  If not, how do we know the difference between devices moved from another system and some devices not being available due to a path failure.

**Comment by mulkieran** [comment]
There is also the interesting possibility that the devices that are missing contain the most up-to-date metadata. In that case, we get obsolete metadata and I don't know what happens next. Maybe there really is nothing we can do about such a situation.

**Comment by mulkieran** [comment]
We ought to consider storing the device UUID as part of the blockdev information.

**Comment by agrover** [comment]
> We ought to consider storing the device UUID as part of the blockdev information.

I believe we do.

**Comment by mulkieran** [comment]
We store the blockdev UUID both in the staticheader and in the variable length metadata. So, that's all good. We also verify that the blockdevs we have are exactly the blockdevs that our variable length metadata says we should have. So, we could only go wrong if we lost exactly the blockdevs that contain the newest metadata AND those blockdevs were exactly the ones that were just added. In that case, we shouldn't really be expected to recover.

I'm thinking we can actually close this one.
