### ISSUE TITLE
Remove redundancy option from PoolCreate method

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#2969]
it does nothing.

**Comment by jbaublitz** [comment]
@mulkieran Do you think this is a good candidate for @bmr-cymru?

**Comment by mulkieran** [comment]
@jbaublitz Yes. I'll reassign.

**Comment by mulkieran** [comment]
@bmr-cymru Note that this will require some update to stratis-cli as well. It just unconditionally calls the method with a 0, at this time, but that will have to be removed with this change. This part could be done by either you or me, your choice.

**Comment by mulkieran** [comment]
Easier to do this after #3079 is merged (because it adds new files for the manager r4 interface).

**Comment by mulkieran** [comment]
Next release...it requires coordination between stratis-cli and stratisd and so it's a little late right now.

**Comment by mulkieran** [comment]
Part of https://github.com/stratis-storage/project/issues/399 `
