### ISSUE TITLE
Drop udevadm settle calls in source

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#2989]
There are two calls, both to be executed before cleanup after some failure.

1. ```StratFilesystem::initialize()``` if ```create_fs``` (for creating xfs filesystem fails).
2. ```ThinPool::create_filesystem``` if saving the metadata to the mdv fails.

Can we just use the retry crate for both?

**Comment by mulkieran** [comment]
@jbaublitz, @bmr-cymru Do you see a compelling reason to use udevadm settle on these error paths instead of just retrying the cleanup using the facilities in the retry crate?

**Comment by jbaublitz** [comment]
@mulkieran Based on my experience with udev, I'm wondering if retries are really necessary for the MDV save case. Just writing to a filesystem shouldn't trigger udev processing but @bmr-cymru correct me if I'm wrong. As for failing to create the filesystem, that would trigger a udev event for sure but I think waiting until the whole udev queue is cleared is a bit overboard. We have similar cases where we use the retry crate elsewhere so this seems like it would work here too.

**Comment by bmr-cymru** [comment]
@mulkieran I don't see a strong reason for waiting on udev here and I think there are other (rare/unlikely) cases where we might legitimately need to retry the cleanup.

@jbaublitz agreed - a close of a writeable file descriptor on the block device that contains the file system will trigger udev events, but ordinary IO to files in a mounted file system will not.

I need to look at the retry crate and understand how it works better (I just had a quick look at the umount retry in `StratFilesystem::snapshot()`), but I don't see any reason to require the full udev settle, and a retry has some minor benefit.

Creating the file system and mounting the MDV both require the thin device node but cleaning up the DM device doesn't - it just requires ioctl access to `/dev/mapper/control` (which is already open in any case I think, looking at devicemapper-rs?), and for the device to be in a state where removal can succeed (i.e. not mounted or open). Changing these to retries seems like it would cover cases that the udev settle doesn't - for example another process having the device open and blocking the remove.
