### ISSUE TITLE
Malicious on-disk metadata

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#299]
@tasleson points out that it's possible for someone to construct a block device with metadata that looks like Stratis metadata but that is invalid in some way. If such a device is added to a Stratis system, bad things could happen.

We need to understand what these cases are, and what steps Stratis can take to minimize the negative effects from this.

Not a high priority, since I think this is less likely than Stratis not working for other reasons 😃 and AFAIK no other filesystems or LVMs have dealt with purposefully corrupted or invalid metadata failure scenarios.

**Comment by ibotty** [comment]
Neither do the filesystems.

**Comment by mulkieran** [comment]
We may someday actually have some protections against this kind of thing with dm-integrity.

**Comment by mulkieran** [comment]
This is vague; we already have code that verifies correctness of a pool wrt. the information that is available and we continue to work to improve that. If the idea is that the metadata could be correct but the data could be wrong, that is a possibility. We do have some plans for making use of dm-integrity and that would then make another aspect of this problem go away.
