### ISSUE TITLE
Make stratisd fail in a more helpful way when Clevis scripts are not available

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#3018]
There are options:
* The most complete solution is to check for clevis scripts whenever a Clevis-requiring command is invoked.
* Simpler but still helpful would be to advise the user to install the required Clevis scripts and to restart stratisd.

Orthogonal to this is making the list of required scripts more precise: currently we report all the scripts that stratisd might need, it would be a bit better to report all the scripts that stratisd might need AND has not found.

**Comment by mulkieran** [comment]
@drckeefe Please feel free to comment on solutions you consider more desirable.

**Comment by drckeefe** [comment]
@mulkieran 
- Does checking for clevis script require Stratis to maintain a list that could change frequently? 
- What is the cost to check for these scripts?  Would it add noticeable time to issuing each Stratis command?
- Could this be solved with a sub-package that has a requirement for these packages and installed them, then restarts stratisd?
- I believe the second bullet would be helpful while we collect more information.
- Your orthogonal comment would also help bullet number 2, though I wonder how much text output this would generate.

**Comment by mulkieran** [comment]
We decided to go with a dynamic approach and precede every invocation of a clevis script w/ a check to make sure that the Clevis scripts on which stratisd depends are there. We'll also refine the error message to indicate exactly what Clevis scripts are missing.

We'll also toss in a CI task that verifies correct action when Clevis dependencies are not installed. These could be unit tests or could be tests made by running commands over the D-Bus.

**Comment by mulkieran** [comment]
It should be noted that having a stratisd command-line option to skip the checks for the Clevis scripts when performing an invocation is not incompatible with the dynamic approach we're pursuing and could be implemented at a later time.

**Comment by mulkieran** [comment]
One last thing, a static approach is undesirable for the same reason that the dynamic approach is done better on each Clevis script invocation rather than at the engine interface. For many commands, whether or not a Clevis script is invoked depends on the current state of a pool's devices. Adding data devices is a really obvious example. If the existing devices are encrypted using Clevis, then Clevis commands will be required to encrypt the new devices, if not, not.

Compiling out Clevis support is doable, but would require leaving stubs that returned errors instead of invoking the Clevis scripts.
This would duplicate the experience that the user would get with the dynamic approach, except that it would not be fixable by installing the necessary Clevis packages. So it seems like there is no benefit to the static approach.
