### ISSUE TITLE
Disappearing symlinks on boot with a Stratis rootfs

### ISSUE THREAD

**Issue by refi64** [stratis-storage/stratisd#3019]
This is something that I'm not entirely clear on, to be honest, but after a bit of research, I'm now moderately sure this is a bug in stratisd/-min...somewhere.

Currently, I use Stratis for my root filesystem, with two subvolumes, the root and home partitions. When setting it up, I followed the [blog post](https://stratis-storage.github.io/stratis-rootfs/), in particular for the fstab changes. And, it all worked! ...well, mostly.

A while ago, I noticed this very sporadic issue with my main computer, where I'd get dropped into emergency mode because the home partition failed to mount. It turned out, this was because `/dev/stratis` was *entirely* missing, and I could continue the boot process with `udevadm trigger`, which would create the missing symlinks. I had assumed this was some strange local system issue, since my setup was basically layers upon layers of "different" (running Stratis on top of Silverblue, in particular).

Recently, I managed to acquire an M1 device and install Fedora onto it, once again using Stratis as my rootfs. To my surprise, I hit the *same* exact, entirely identical issue...except now it happens *every* boot, quite reliably (I'm guessing because the new disk is significantly faster than the old one?). Once again, running `udevadm trigger` allowed me to continue boot.

My fstab looks like this:

```
/dev/stratis/fedora/root / xfs defaults,relatime 0 0
UUID=006c04be-05b5-474d-a1b9-d23a1477f956 /boot ext4 defaults,relatime 1 2
UUID=7E9D-1AEE /boot/efi vfat umask=0077,shortname=winnt 0 2
/dev/stratis/fedora/home /home xfs defaults,relatime,x-systemd.requires=stratis-fstab-setup@fccd3f78-2670-40b6-8e51-f1c326a4147b.service,x-systemd.after=stratis-fstab-setup@fccd3f78-2670-40b6-8e51-f1c326a4147b.service 0 0
UUID=00c7c481-de21-4361-8a78-0d89aa5af79e none swap defaults,noatime 0 0
```

The UUID in `stratis-fstab-setup@` should match the pool UUID:

```
$ stratis pool
Name                      Total Physical   Properties                                   UUID   Alerts
fedora   3.63 TiB / 60.36 GiB / 3.57 TiB      ~Ca, Cr   fccd3f78-2670-40b6-8e51-f1c326a4147b
```

And here's `stratis fs`, for completeness purposes:

```
$ stratis fs
Pool Name   Name   Size                              Created             Device                     UUID
fedora      home   3 TiB / 38.10 GiB / 2.96 TiB      May 31 2022 18:00   /dev/stratis/fedora/home   d791471f-fb4f-4f60-bb7d-4317f5184ef2
fedora      root   1 TiB / 18.53 GiB / 1005.47 GiB   May 31 2022 18:00   /dev/stratis/fedora/root   38251e78-f606-42d7-9551-a5e0747819e9
```

While first encountering the bug, I did notice that `stratisd` wasn't started yet, because, well, it can't be, stratisd needs dbus, dbus needs the local filesystem, and the local filesystem...well, it couldn't be mounted.

Here's a link to the full journal around the time of the incident: https://paste.sr.ht/~refi64/a16818fdc9f1e92fed5ee52021d7fa4027bd5be6

The final log at `01:30:26` is when I was fully dropped into emergency mode, and the logs starting at `01:30:31` was after I ran `udevadm trigger` and then hit ctrl-d to continue boot. Some relevant snippets that stood out to me:

```
###### stratis-fstab-setup runs here
Jun 11 01:30:26 m1-fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=stratis-fstab-setup@fccd3f78-2670-40b6-8e51-f1c326a4147b comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 11 01:30:26 m1-fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=stratis-fstab-setup@fccd3f78-2670-40b6-8e51-f1c326a4147b comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

##### systemd starts trying to mount /home
Jun 11 01:30:26 m1-fedora systemd[1]: Mounting home.mount - /home...

##### while systemd is mounting /home, stratisd stops
Jun 11 01:30:26 m1-fedora systemd[1]: Stopping stratisd-min-postinitrd.service - Stratis minimal daemon...
Jun 11 01:30:26 m1-fedora stratisd-min[892]: [2022-06-11T06:30:26Z INFO  stratisd::stratis::run] Caught SIGINT; exiting...
Jun 11 01:30:26 m1-fedora systemd[1]: run-stratisd-keyfiles.mount: Deactivated successfully.

##### systemd realizes /dev/stratis/fedora/home does not exist
Jun 11 01:30:26 m1-fedora mount[1077]: mount: /home: special device /dev/stratis/fedora/home does not exist.
Jun 11 01:30:26 m1-fedora mount[1077]:        dmesg(1) may have more information after failed mount system call.
Jun 11 01:30:26 m1-fedora systemd[1]: home.mount: Mount process exited, code=exited, status=32/n/a
Jun 11 01:30:26 m1-fedora systemd[1]: home.mount: Failed with result 'exit-code'.
Jun 11 01:30:26 m1-fedora systemd[1]: Failed to mount home.mount - /home.
Jun 11 01:30:26 m1-fedora systemd[1]: Dependency failed for local-fs.target - Local File Systems.

[...]

##### Emergency shell is started
Jun 11 01:30:26 m1-fedora systemd[1]: Started emergency.service - Emergency Shell.
Jun 11 01:30:26 m1-fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=emergency comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 11 01:30:26 m1-fedora systemd[1]: Reached target emergency.target - Emergency Mode.

[...]

##### After I recover, stratis-fstab-generator runs again, but this time it fails because the setup service already exists from before
Jun 11 01:31:35 m1-fedora systemd[1]: Reloading.
Jun 11 01:31:35 m1-fedora stratis-setup-generator[1246]: systemd generator failed with error: File exists (os error 17)
Jun 11 01:31:35 m1-fedora systemd[1237]: /usr/lib/systemd/system-generators/stratis-setup-generator failed with exit status 1.
```

The fact that `udevadm trigger` works is *strange*, because `stratis-fstab-setup` [already runs `udevadm settle`](https://github.com/stratis-storage/stratisd/blob/c859be244160e2200e652902f3b0c2a34873367b/systemd/stratis-fstab-setup#L36).

My **completely uneducated** guess is that:
- `stratis-fstab-setup` creates the symlinks
- `stratisd-min` stops, somehow clearing the symlinks with it
- now mounting `/home` is attempted, failing because the symlinks are gone

This would sort of explain why the faster disk can more easily reproduce it, as well?

**Comment by jbaublitz** [comment]
Hi @refi64! I just wanted to let you know that I reproduced the issue in my set up and I'm going to try the delay solution to see if it fixes it. If not, I'll try to get you another workaround.

**Comment by jbaublitz** [comment]
Hi @refi64! It turns out this is actually a bug in our systemd unit files. I will put up a fix for you to test.

For now, if you add under `[Unit]`
```
After=systemd-udevd.service
Requires=systemd-udevd.service
```
to `/usr/lib/systemd/system/stratisd-min-postinitrd.service`, this fixed the problem for me. It appears this is a systemd synchronization problem that we handle correctly for the root filesystem but not for /etc/fstab.

**Comment by i2** [comment]
@refi64 and others: Would you please be able to tell me the exact steps you have followed to successfully install this on Stratis as rootfs?

I am trying to setup RHEL/Fedora on Stratis rootfs and have followed [this guide](https://stratis-storage.github.io/stratisd-rootfs-packaging/). When I am done with setup and reboot, it drops me on GRUB'
s `minimal BASH-like` rescue terminal.

This is a EFI computer and my disk layout is:
```
/dev/sda1 -> EFI FAT32
/dev/sda2 -> rootfs for Stratis
```
Here's a template for my /mnt/etc/default/grub
```
GRUB_CMDLINE_LINUX="root=/dev/stratis/mypool/fs01 stratis.rootfs.pool_uuid=[POOL_UUID]"
```

And then I rebuild GRUB config file with above changes.

Is it not booting because GRUB can't find /boot/initramfs-XYZ.img which is on stratis rootfs? Do I need to have a separate non-Stratis boot partition which houses initramfs?

Thanks!

**Comment by mulkieran** [comment]
@i2 Could you relocate this to the Question area: https://github.com/stratis-storage/project/discussions/new?category=q-a ? Thanks!
