### ISSUE TITLE
Add additional D-Bus property showing when a pool is approaching data full

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#3026]
We already have a property, NoAllocSpace, which indicates that all the space on a pool's data devices has been allocated. This does not, however, mean that the pool is out of space. Some, possibly considerable, amount of the allocated space may be empty. We propose another property, which constitutes an alert which will be toggled to true when the space that has allocated becomes "mostly" full, and it is an imminent possibility that, unless an allocation of additional space occurs, the pool will run completely out of space.

The property might be called LowDataSpace. The difficulty is defining what "mostly" full means.

When LowDataSpace is true and NoAllocSpace is true the situation becomes most interesting. stratisd is not in a position to allocate any more space for user data and the user has used up almost all the available space there is.

Related https://github.com/stratis-storage/project/discussions/463#

**Comment by jbaublitz** [comment]
Closing. I explained the current state of things to @refi64 who is okay with this signal being sent out when 15GB of space is left.
