### ISSUE TITLE
Might want to have a third alternative that compiles in neither IPC mechanism

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#3105]
Currnently, there is no way to compile in neither IPC mechanism. It is likely to be desirable to do this, though, as we make use of the stratisd engine source code to support various applications or tools of which the most obvious to me is stratis-dumpmetadata. At present we compile this application with the other IPC mechanism (i.e., not D-Bus) and that reduces the size of the debug executable by (160 - 116) / 160 /approx 40 / 160 = 1/4.

**Comment by jbaublitz** [comment]
This seems reasonable to me! Do you think this would be a good issue for @bmr-cymru?

**Comment by mulkieran** [comment]
Let's tentatively do that. It is in no way urgent yet...

**Comment by mulkieran** [comment]
This turns out to be more complicated than was originally expected because the IPC mechanism picks up udev events and transmits them to the engine so that the engine can react to them and notify the IPC mechanism of any changes made so that the IPCmechanism, if it is D-Bus can update D-Bus properties and so forth.

So, to run w/out any IPC mechanism currently would prevent the engine's handling of udev events.

A solution to this is to add a third, dummy IPC mechanism, that passes the udev events along to the engine and otherwise does nothing.
