### ISSUE TITLE
statically compile udev lib binaries 'stratis-str-cmp' and 'stratis-base32-decode'

### ISSUE THREAD

**Issue by leseb** [stratis-storage/stratisd#3195]
As part of the containerization effort, we need to copy `stratis-str-cmp` and `stratis-base32-decode`, on the host under `/usr/lib/udev/` so that Stratis's udev rule can work adequately and `/dev/stratis` devices can be created.
Statically compiling allows us to not rely on any libraries and avoid potential execution issues, even though the scripts are relatively simple.

Today, `stratis-utils` governs the generation of the util binaries, due to the increased numbers of dependencies it cannot be statically compiled with `RUSTFLAGS='-C target-feature=+crt-static`.

One idea would be to decouple/extract both binaries into individual ones, I believe this is how things used to be.
Happy to discuss whatever approach is the best for the team given the above requirement.

Also, happy to work on the solution under the team's guidance.
Thanks!

**Comment by jbaublitz** [comment]
@leseb One note about static linking in Rust is that without musl, there will always be at least a glibc dynamic link dependency. Would that concern you?
