### ISSUE TITLE
If the dbus API serves up the return codes, it should be responsible for translating.

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#32]
That is, either the engine has its own return codes and the dbus API changes them to its visible return codes, or else the engine serves up the return codes.

**Comment by agrover** [comment]
My initial thinking was the dbus api would convert from internal to API-visible codes.

**Comment by mulkieran** [comment]
Ok!

**Comment by mulkieran** [comment]
This will be impossible to do in a general way unless there is a one-to-one mapping between internal stratis engine codes and dbus codes. This means that the internal codes have to be no more general than the dbus codes.

**Comment by agrover** [comment]
I think this is complete, at least an initial implementation.

**Comment by mulkieran** [comment]
I think we should discuss it some more today.

**Comment by mulkieran** [comment]
I'll looking into making the internal error more interesting and useful.

**Comment by mulkieran** [comment]
Closed by #65.
