### ISSUE TITLE
stratis-min fails to create /dev/stratis after unlocking an encrypted filesystem

### ISSUE THREAD

**Issue by eashleyfl** [stratis-storage/stratisd#3271]
I'm trying to create an encrypted root filesystem with both a Tang server and a keyfile but am stuck on the fact that I have to use a live image, install, enable and start stratisd. Then stratis-min pool start --unlock-method clevis fails with errno 2 because /dev/stratis never gets created, though the logs indicate that the unlock succeeded.

If I install stratis-cli, it will correctly unlock the pool.

Command line log snippet follows:

`Mar 03 14:03:00 fedora kernel: Command line: BOOT_IMAGE=/images/pxeboot/vmlinuz root=live:CDLABEL=Fedora-WS-Live-37-1-7 rd.live.image stratis.rootfs.pool_uuid=6fb21c84-2496-4bbc-858b-9571ec099369 rd.neednet=1`

This is starting stratisd and executing stratis-min pool start... twice:

`Mar 03 14:11:21 localhost-live stratisd[2777]: [2023-03-03T19:11:21Z INFO  stratisd::stratis::run] stratis daemon version 3.5.1 started`
`Mar 03 14:11:21 localhost-live stratisd[2777]: [2023-03-03T19:11:21Z INFO  stratisd::stratis::run] Using StratEngine`
`Mar 03 14:11:21 localhost-live stratisd[2777]: [2023-03-03T19:11:21Z INFO  stratisd::engine::strat_engine::liminal::identify] Beginning initial search for Stratis block devices`
`Mar 03 14:11:21 localhost-live stratisd[2777]: [2023-03-03T19:11:21Z DEBUG stratisd::engine::strat_engine::backstore::crypt::shared] Stratis LUKS2 token: {"activation_name":"stratis-1-private-c6963eeec2164765849bdafeb2d63b0d-crypt","device_uuid":"c6963eee-c216-4765-849b-dafeb2d63b0d","keyslots":[],"pool_name":"callisto_pool","pool_uuid":"6fb21c84-2496-4bbc-858b-9571ec099369","type":"stratis"}`
`Mar 03 14:11:21 localhost-live stratisd[2777]: [2023-03-03T19:11:21Z INFO  stratisd::engine::strat_engine::liminal::identify] LUKS block device belonging to Stratis with device number: "252:3", devnode: "/dev/vda3", Stratis pool UUID: "6fb21c84-2496-4bbc-858b-9571ec099369", Stratis device UUID: "c6963eee-c216-4765-849b-dafeb2d63b0d", key description: "stratis-random", clevis pin: "tang", clevis configuration: "{"thp":"UTBiEYWGqgahVCKcVh5xNRFuK-5UtJyD5fnoCh80pNU","url":"http://192.168.2.1:7500"}" discovered during initial search`
`Mar 03 14:11:21 localhost-live stratisd[2777]: [2023-03-03T19:11:21Z INFO  stratisd::engine::strat_engine::liminal::device_info] Device information LUKS device description: device number: "252:3", devnode: "/dev/vda3", Stratis pool UUID: "6fb21c84-2496-4bbc-858b-9571ec099369", Stratis device UUID: "c6963eee-c216-4765-849b-dafeb2d63b0d", key description: "stratis-random", clevis pin: "tang", clevis configuration: "{"thp":"UTBiEYWGqgahVCKcVh5xNRFuK-5UtJyD5fnoCh80pNU","url":"http://192.168.2.1:7500"}" discovered and inserted into the set for its pool UUID`
`Mar 03 14:11:21 localhost-live stratisd[2777]: [2023-03-03T19:11:21Z INFO  stratisd::engine::strat_engine::liminal::liminal] Attempt to set up pool failed, but it may be possible to set up the pool later, if the situation changes: Some of the devices in pool with UUID 6fb21c84-2496-4bbc-858b-9571ec099369 are unopened`
`Mar 03 14:11:21 localhost-live audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=stratisd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success`
`Mar 03 14:11:21 localhost-live systemd[1]: Started stratisd.service - Stratis daemon. `

**Comment by eashleyfl** [comment]
If I install `stratis-cli` after the `stratis-min` failure, I'm able to successfully unlock the pool.

**Comment by jbaublitz** [comment]
Based on the logs, I'm seeing a different story. The log messages you shared are saying that the pool was actually not set up properly because some of the devices are still locked. I'm also seeing from these logs that stratisd is running instead of stratisd-min which is a sign that this is probably not running in the initramfs. D-Bus is not available in the initramfs so these appear to be logs from later in the boot process. One last note is that I see no indication that stratis-min start is being run at all, and stratisd is only being started once. The message you see at the end is the success message for starting stratisd. You may see some stratisd logs before the success message because stratisd only considers itself up when it registers with the D-Bus which occurs after initial device discovery. I'm not entirely sure why this is happening, but just to get some preliminary stuff out of the way:
* Take a look at this blog post if you haven't already: https://stratis-storage.github.io/stratis-rootfs/
* Have you explicitly enabled the `stratis-clevis` module in `/usr/lib/dracut/dracut.conf.d` before regenerating your initramfs? This would look like:

```
add_dracutmodules+=" stratis-clevis "
```
in a configuration file in `/usr/lib/dracut/dracut.conf.d/`.

* Have you installed the stratisd-dracut package and regenerated your initramfs?

**Comment by eashleyfl** [comment]
The last two bullets are what I was missing. I followed the blog post but it only discusses dracut regarding scopes of work to code the integration, not what dracut changes are required to actually use it. I'd insert it myself but I'm not sure where it would fit since the existing document is a quasi combination of a design and scope-of-work document with a few of the howto elements included.

**Comment by jbaublitz** [comment]
Did these steps resolve your issue? If so, I can update the documentation somewhere more appropriate (in an update at the end of the article for example) and close this out.

**Comment by eashleyfl** [comment]
Sorry, I must have chopped that part of my response out before my coffee was fully working. Yes, the dracut config and --force with editing the command line in the grub loader/entries/XXX-[kernel-rev].conf fixed it.

I'm working up a HOWTO to start with the F37 KVM disk image, enlarge it, create a virtio disk from it, create the stratis encrypted fs on the host machine then launch the vm, install stratis, transfer filesystems from vda to stratis disk, do all the required edits on stratis disk, install grub on the encrypted disk and move the stratis disk to root filesystem in the VM config. The unencrypted disk can be reused for each additional machine to get an encrypted root after that initial setup. I used a mid-point reboot with fstab loading of the encrypted disk as a second filesystem to test that the basic part was correct.

Thanks for all the excellent work on this project, et. al.

**Comment by jbaublitz** [comment]
@eashleyfl Our most recent blog post should address this concern. Closing.

**Comment by mulkieran** [comment]
Blog post link: https://stratis-storage.github.io/stratis-rootfs-fedora/ .
