### ISSUE TITLE
Stratis internal DM devices appear in lsblk, udisksctl etc. in 3.5.2-1.fc37

### ISSUE THREAD

**Issue by bmr-cymru** [stratis-storage/stratisd#3301]
As [reported by Katerina Koukiou](https://bugzilla.redhat.com/show_bug.cgi?id=2183084) stratis internal device-mapper devices now appear in the output of lsblk, udisksctl etc. in F37 with current updates:

stratisd-3.5.2-1.fc37.x86_64
udisks2-2.9.4-5.fc37.x86_64
device-mapper-1.02.175-9.fc37.x86_64
lvm2-2.03.11-9.fc37.x86_64

Previously these devices set DM Udev flags that suppress visibility for these devices:

E: DM_UDEV_DISABLE_SUBSYSTEM_RULES_FLAG=1
E: DM_UDEV_DISABLE_DISK_RULES_FLAG=1
E: DM_UDEV_DISABLE_OTHER_RULES_FLAG=1

It's not immediately clear what has caused this change.

**Comment by bmr-cymru** [comment]
This is due to a change in devicemapper-rs that is part of the work for udev synchronisation: previously, only the `ThinDev` device type (i.e. thin provisioned leaf devices) set the `DM_UDEV_PRIMARY_SOURCE` flag. This suppresses DM rule processing for all other device types which causes those devices to acquire the three `DM_UDEV_DISABLE_*` udev flags by default.

With the udev sync changes the primary source flag is set automatically for all ioctl commands that generate uevents. This causes normal DM udev rule processing to take place for all devices created by devicemapper-rs and leads to the visibility change described in this issue.

There are several ways that this could be addressed but in the short term it is probably best to restore the previous behaviour and have the devicemapper-rs library automatically set the `DM_UDEV_DISABLE_*` flags for non-ThinDev devices that it constructs.

**Comment by bmr-cymru** [comment]
I've filed stratis-storage/devicemapper-rs#845 to restore the former behaviour for internal devices.

**Comment by mulkieran** [comment]
devicemapper-rs 0.33.3 released: https://github.com/stratis-storage/project/issues/601
