### ISSUE TITLE
Pools with NBDE can never be unlocked with a passphrase during boot

### ISSUE THREAD

**Issue by mvollmer** [stratis-storage/stratisd#3349]
A encrypted pool that should be unlocked during boot can be bound to a Tang server so that the boot can be unattended. However, if the Tang server is not reachable during boot, the stratis-fstab-setup program will just fail and not allow entering a passphrase at all.

This is different from LUKS. With LUKS, you get the opportunity to enter a passphrase even when a device uses NBDE as well.

**Comment by jbaublitz** [comment]
Is the assumption that the user had decrypted the Clevis token passphrase and stored it in a password manager or something similar to use as a back up?

**Comment by mvollmer** [comment]
> Is the assumption that the user had decrypted the Clevis token passphrase and stored it in a password manager or something similar to use as a back up?

No, the idea is that a pool with both a clevis binding and a keyring binding can be unlocked during boot with either clevis or by typing in a passphrase.

Normally, the tang server is reachable during boot and booting will proceed unattended. But occasionally, the machine might be taken out of the network with the tang server, and then the pool can not be started during boot since there is no prompt for its passphrase.

This might be acceptable. The pool can be started manually and its filesystems can be mounted manually, and the applications that need these filesystems can be manually started. But just having the boot wait for the user to type in a passphrase might be more convenient. This is also the behavior for regular LUKS, so people might be expecting it.

Code wise, stratis-fstab-setup would just need to do the passphrase stuff after clevis has failed, I'd say, instead of skipping it completely as soon as there is a clevis binding.

**Comment by jbaublitz** [comment]
Okay, now I understand! I think we need to resolve this in both the rootfs case and in stratis-fstab-setup. I think this should be a relatively straightforward fix. I'll try to get this fixed in the next couple of days.
