### ISSUE TITLE
pool.GrowPhysicalDevice doesn't trigger change notification for blockdev.TotalPhysicalSize

### ISSUE THREAD

**Issue by mvollmer** [stratis-storage/stratisd#3371]
Subject says it all. :-)

**Comment by mvollmer** [comment]
See https://github.com/cockpit-project/cockpit/pull/19079 for my efforts to support growing of block devices in Cockpit.  It's working fine, except for the missing notification.

**Comment by mulkieran** [comment]
Could you give us version of stratisd and D-Bus revision that you're using?

**Comment by mvollmer** [comment]
> @mvollmer Could you give us version of stratisd and D-Bus revision that you're using? Err, revision is r3.

Upps, sorry. Yes, revision is "r3", with stratisd-3.5.7-1.fc38.x86_64.

**Comment by mulkieran** [comment]
Reproduced.
