### ISSUE TITLE
Use `$LIBEXECDIR` in determining location of internal stratisd commands in dracut modules provided

### ISSUE THREAD

**Issue by arnavyc** [stratis-storage/stratisd#3378]
[Makefile](Makefile) of this project defines a LIBEXECDIR variable to decide location of libexec directory when installing.

https://github.com/stratis-storage/stratisd/blob/3ed2e0e486c784000327449efa68dfb3e49b5761/Makefile#L12

However, the dracut module `stratis` and [`stratisd-min.service` in the dracut module](https://github.com/stratis-storage/stratisd/blob/3ed2e0e486c784000327449efa68dfb3e49b5761/dracut/90stratis/stratisd-min.service) checks only hardcoded `/usr/libexec/stratisd-min` in [`dracut/90stratis/module-setup.sh`](https://github.com/stratis-storage/stratisd/blob/3ed2e0e486c784000327449efa68dfb3e49b5761/dracut/90stratis/module-setup.sh), regardless of value of LIBEXECDIR.

In `check()` of [`dracut/90stratis/module-setup.sh`](https://github.com/stratis-storage/stratisd/blob/3ed2e0e486c784000327449efa68dfb3e49b5761/dracut/90stratis/module-setup.sh):
https://github.com/stratis-storage/stratisd/blob/3ed2e0e486c784000327449efa68dfb3e49b5761/dracut/90stratis/module-setup.sh#L6

In `install()` of [`dracut/90stratis/module-setup.sh`](https://github.com/stratis-storage/stratisd/blob/3ed2e0e486c784000327449efa68dfb3e49b5761/dracut/90stratis/module-setup.sh):
https://github.com/stratis-storage/stratisd/blob/3ed2e0e486c784000327449efa68dfb3e49b5761/dracut/90stratis/module-setup.sh#L37

In [`dracut/90stratis/stratisd-min.service`](https://github.com/stratis-storage/stratisd/blob/3ed2e0e486c784000327449efa68dfb3e49b5761/dracut/90stratis/stratisd-min.service):

https://github.com/stratis-storage/stratisd/blob/3ed2e0e486c784000327449efa68dfb3e49b5761/dracut/90stratis/stratisd-min.service#L11

**Comment by mulkieran** [comment]
@arnavyc Thanks for the report! How did you discover this? Are you interested in putting up a PR or would you like us to proceed with that?

**Comment by arnavyc** [comment]
How did you discover this?
I installed stratis for / in Arch linux in my new laptop. Refer to https://bugs.archlinux.org/task/79023.

    Are you interested in putting up a PR or would you like us to proceed with that?
I don't seem to have the time for fixing it by a PR. Also it could be temporarily mitigated by creating directory /usr/libexec and symlinking /usr/lib/stratisd-min (in Arch package [`stratisd`](https://archlinux.org/packages/extra/x86_64/stratisd/)) to /usr/libexec/stratisd-min.

**Comment by jbaublitz** [comment]
@arnavyc I'm pretty sure someone fixed this in our regularly installed systemd files but not for dracut. I think we could take the same approach for the other places we missed because both are installed my the `make install` target.

**Comment by mulkieran** [comment]
We should try to get this out for next release.
