### ISSUE TITLE
Tracking issue for Ubuntu bug in clevis build

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#3393]
https://bugs.launchpad.net/ubuntu/+source/clevis/+bug/2029149

**Comment by drckeefe** [comment]
@dannf One of the Clevis developers mentioned to me that you might be able to rebuild this package or know who could help out.   My apologizes if you are not involved with Clevis.  Thank you if you can provide some assistance.

**Comment by dannf** [comment]
Hi @drckeefe I'm not actively involved with clevis, but I did some work on clevis integration in Ubuntu in the past. I've provided some suggestions on how to proceed in that bug on LP.

**Comment by drckeefe** [comment]
@dannf Thank you very much for your response.  We'll see if we can tackle this with your advice.

**Comment by mulkieran** [comment]
I think we can close this as it matters little to us now, as we've proved we can use Packit/TMT to run the tests that were failing due to the Ubuntu packaging lag.
