### ISSUE TITLE
Translation concerns should be explictly postponed.

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#34]
Otherwise, we waste the time of the translators, among other things.

**Comment by agrover** [comment]
It seems to me like Linux is localized for user-facing programs, but admin-oriented tools are generally not. e.g. btrfs-tools is not. lvm2's is incomplete and disabled. Cockpit is localized. Right now I'd think Stratis falls into the category of tools where i18n is not expected.

**Comment by mulkieran** [comment]
Sounds good. Let us consider it postponed until it is either needed or customary, which may be never. I'll close this tomorrow unless there is an objection.

**Comment by mulkieran** [comment]
Ok, closing!
