### ISSUE TITLE
likely incorrect borrowing with nix+recvmsg

### ISSUE THREAD

**Issue by cgwalters** [stratis-storage/stratisd#3423]
See https://github.com/nix-rust/nix/issues/2083#issuecomment-1695862840

**Comment by mulkieran** [comment]
We see the error in nightly testing: https://github.com/stratis-storage/stratisd/actions/runs/5995213575/job/16257896837 .

**Comment by mulkieran** [comment]
We can reproduce in current branch thusly: ```cargo update --package=nix@0.26.2 --precise=0.26.3; make clippy```.

**Comment by cgwalters** [comment]
I think it does, there's a temporary slice created whose lifetime is just for the API call, but the return value points into it; that's the reason for the lifetime change.

**Comment by mulkieran** [comment]
If the lifetime of the slice was only that call, our code would have failed to compile before the change.

**Comment by cgwalters** [comment]
> otherwise the compiler would have rejected it.

I don't think so, because [recvmsg is using unsafe](https://docs.rs/nix/latest/src/nix/sys/socket/mod.rs.html#2099).  That's the point of the change.

**Comment by mulkieran** [comment]
In our case, I believe that the code in the ```unsafe``` block was behaving safely, due to the preconditions established by the way that ```recvmsg``` was invoked.

**Comment by mulkieran** [comment]
Err, the lifetime of the unique element of the slice extended to the end of the block, the lifetime of the slice itself is not so certain.

**Comment by mulkieran** [comment]
Next minor version of nix gets rid of the ```recvmsg``` method altogether.

**Comment by jbaublitz** [comment]
@cgwalters Thanks for the heads up! I put up a fix. Thankfully, it appears we never trigger the bug because we don't call the `.iovs()` method and instead use the locally bound vector, but now we can make sure it doesn't show up in the future if we decide to use that method.
