### ISSUE TITLE
Filesystem size limits

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#3431]
Related to #3030 

My current plan is to provide two mechanisms for filesystem growth limits.

The first (and default) option will be limiting filesystems from growing past a certain size. This will be stored in the MDV. This limit can be changed or removed but can never be smaller than the current filesystem size.

The second option will be implementing XFS filesystem quotas. This aspect is a bit more complicated which is why I would like to keep it as an advanced option. Root users can bypass the quota per the design of XFS filesystem quotas which may lead to unexpected behavior so we would like users to opt in so that they understand the limitations.

I anticipate restricting filesystem size limits and XFS quotas from being used together. This will require tracking whether the limit is quota-based or size limit-based in the metadata.

Expected CLI invocation:
```
$ stratis filesystem limit-size 10GiB
$ stratis filesystem limit-size --quota 10GiB
Error
$ stratis filesystem limit-size 20GiB
$ stratis filesystem limit-size remove
$ stratis filesystem limit-size --quota 20GiB
$ stratis filesystem limit-size --quota remove
```

**Comment by jbaublitz** [comment]
One additional restrictions that I should mention is that with quotas, I anticipate keeping a `projects` file for XFS project quotas in a namepsace-private directory (likely the MDV) to automatically handle projects without the user having to touch them. This will be a big usability improvement, but also requires us to inspect `/proc/mounts` to determine where a filesystem is mounted and also to ensure that `-o pquota` was provided in the mount command if the user wishes to use the quota based approach.

**Comment by MrPippin66** [comment]
Just to be clear, at this point, the only option to prevent a volume from autoextending until the pool is exhausted is quotas?

**Comment by jbaublitz** [comment]
Yes, but we intend to address that in the linked PR.
