### ISSUE TITLE
Compiling question on SLES15SP4

### ISSUE THREAD

**Issue by yxiang92128** [stratis-storage/stratisd#3445]
What is it looking for?  I have libclang.so.13 installed under /usr/lib and they are all ELF 32 bit.
Why does the "make build" still failing?
Any hint would be helpful as I am new at this.

Thanks,

Yang

error: failed to run custom build command for `devicemapper-sys v0.1.5`

Caused by:
  process didn't exit successfully: `/var/opt/teradata/jenkins/stratisd/target/release/build/devicemapper-sys-fccd46685b68c9ce/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [(/usr/lib/libclang.so: invalid ELF class (32-bit)), (/usr/lib/libclang.so.13: invalid ELF class (32-bit)), (/usr/lib/libclang.so.13.0.1: invalid ELF class (32-bit)), (/usr/lib/libclang.so: invalid ELF class (32-bit)), (/usr/lib/libclang.so.13: invalid ELF class (32-bit)), (/usr/lib/libclang.so.13.0.1: invalid ELF class (32-bit))])"', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.63.0/./lib.rs:2338:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:189: build] Error 101

**Comment by mulkieran** [comment]
It's not immediately obvious to me what's wrong. Are you cross-compiling?

**Comment by yxiang92128** [comment]
I am trying to compile for SLES15SP4 on a SLES15SP4 only.  Not sure what else I need in order to configure the build.
