### ISSUE TITLE
How do we construct flex_devs metadata?

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#346]
We need to be able to construct it, even to get the block allocator information for each block device correct.

**Comment by agrover** [comment]
See https://github.com/stratis-storage/devicemapper-rs/pull/43, with this LinearDev internally tracks its ranges. If we also then add a public method to get this, then we should have what we need to construct flex_devs metadata.

**Comment by mulkieran** [comment]
This was a general question, which has been addressed in various PRs in devicemapper-rs and in stratisd.
