### ISSUE TITLE
Increase syn dependency in stratisd_proc_macros if we can

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#3476]
It's 1.0.109 in stratisd_proc_macros, but everywhere else in stratisd it is 2.0.29.

**Comment by mulkieran** [comment]
Closed for #3650

**Comment by jbaublitz** [comment]
Whoops, sorry missed this. I recently got requests on my personal projects to increase to syn 2 so I just wanted to make a note that we should do it here too.
