### ISSUE TITLE
RAID1 of four disks  != RAID10

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#36]
https://github.com/stratis-storage/stratisd/blob/master/src/dbus_consts.rs#L159

A mirror across four disks is not the same as RAID10, which is a stripe of two pairs of mirrors, so we should decide and clarify exactly what we mean.

**Comment by mulkieran** [comment]
I'm putting in a vote for terseness. Four or fewer words, defer any attempt at precision to relevant docs.
