### ISSUE TITLE
Update to syn 2 in stratisd-proc-macros

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#3650]

**Comment by jbaublitz** [comment]
@mulkieran Would you be able to do this? I'm not going to be able to get around to this for a long time because of other priorities. I was mostly making a note in case we had missed this.

**Comment by mulkieran** [comment]
@jbaublitz I deferred addressing this because I'm unfamiliar with syn and then just forgot about it, so I'm not sure.
