### ISSUE TITLE
Need to add some sort of Incomplete engine error

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#378]
Result actually has a problem, because it only allows one sort of error value. Often we need two, the cause and the effect. For example, an IO error caused us to fail to clean up some blockdevs, now resulting in an imcomplete state.

**Comment by agrover** [comment]
error_chain?

**Comment by mulkieran** [comment]
We talked about this a while back, and this particular problem seemed like a candidate for our state machine.

**Comment by mulkieran** [comment]
To be using error_chain would be nice, but maybe not before 0.1.

**Comment by mulkieran** [comment]
I don't think there's anything useful left here, so closing.
