### ISSUE TITLE
Replace &[&Path] parameters with more organized structure

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#385]
~~Why can't we just do ```&[Path]```. They are kind of cumbersome to deal with, and I'm not sure that the internal reference is really helpful.~~

We would be better off with a purpose built data structure that enforced some invariants, for example, that all the paths are absolute, not duplicates, etc.

**Comment by agrover** [comment]
See https://doc.rust-lang.org/std/path/struct.Path.html

`Path` is an unsized type, like &str, so the alternative isn't `Path` it's `PathBuf`.

**Comment by mulkieran** [comment]
Right. But maybe ```&[PathBuf]``` is really the right thing.

**Comment by agrover** [comment]
`&[P] where P: AsRef<Path>`?

**Comment by Kintaro** [comment]
That would be way more in line with idiomatic Rust.

**Comment by mulkieran** [comment]
I think it is tricky.

**Comment by tasleson** [comment]
I took a stab at this and didn't get very far, I tried taking

```rust
fn add_blockdevs(&mut self, paths: &[&Path], force: bool) -> EngineResult<Vec<DevUuid>>;
```
changing it to:
```rust
fn add_blockdevs<P>(&mut self, paths: &[P], force: bool) -> EngineResult<Vec<DevUuid>>
        where P: AsRef<Path>;
```
Which results in a compile error:
```
error[E0038]: the trait `engine::engine::Pool` cannot be made into an object
   --> src/engine/strat_engine/engine.rs:122:5
    |
122 |     fn pools(&self) -> Vec<&Pool> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `engine::engine::Pool` cannot be made into an object
    |
    = note: method `add_blockdevs` has generic type parameters
```

I'm pretty new to rust, so I maybe I'm not taking the correct approach as suggested in the above comment by @agrover

**Comment by mulkieran** [comment]
Yeah, I removed the trivial label for a reason. I'm not sure how to do it.

**Comment by mulkieran** [comment]
We are gradually introducing these purpose built data structures, to address the invariants that we need to enfoce, so this one is obsolete.
