### ISSUE TITLE
In setting up an engine, what should we be doing about '/dev/stratis' directory?

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#390]
We could have a general policy of failing if it is missing.

**Comment by agrover** [comment]
We already do this, see `StratEngine::initialize`. If it doesn't exist and we can't create it, we fail.

**Comment by mulkieran** [comment]
```setup() != initialize()```.

**Comment by mulkieran** [comment]
The conclusion is that what ```setup()``` is doing now should be moved to initialize.
