### ISSUE TITLE
Initial data size may be too small for thin pool dev

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#405]
Currently defined as: 

const INITIAL_DATA_SIZE: Sectors = Sectors(512 * Mi / SECTOR_SIZE as u64);

This isn't enough for XFS to put a filesytem on a thindev with virtual space of 1T

**Comment by mulkieran** [comment]
The value was changed to 768 in b15efebe1cd80066319838b2fe04198741a80c8c.
