### ISSUE TITLE
style/consistency: Error strings should not end in "."

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#418]
Run
```
git grep "\.\"" `git rev-parse --show-toplevel`
```
in the repo to find spots to look at.

**Comment by ambaxter** [comment]
I'll take it

**Comment by mulkieran** [comment]
Ok, thanks!

**Comment by mulkieran** [comment]
Btw, why shouldn't error strings end in a full stop, and is there something in style doc about this?

**Comment by agrover** [comment]
Entirely for consistency, to align with the great majority of our error and expect messages, as well as those in the Rust stdlib itself.
