### ISSUE TITLE
determine best way to expand physical space backing a pool

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#433]
Currently when data consumption crosses the low water mark, we double the physical space.  Not sure this approach will scale well...

**Comment by mulkieran** [comment]
We also may want to, if allocation fails, try for a smaller number, and report the problem. It may be better to have a partial success in this case then to fail dramatically.

**Comment by trgill** [comment]
related to #494

**Comment by mulkieran** [comment]
it was noted that we should take into account the granularity of the allocation. For example, if allocating for data device in thinpool, anything less than a full data block is no use. There is plenty to do in this area.

**Comment by mulkieran** [comment]
I feel like I might as well close this in favor of more recent #693 and #697.
