### ISSUE TITLE
Pool rename should work

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#457]
It doesn't look like it is saving the new name to on-disk metadata.

**Comment by mulkieran** [comment]
The code looks like it is. But there is an easy test to write...

**Comment by mulkieran** [comment]
AFAICT, the solution is to write the pool metadata once the rename is accomplished, i.e., at the very end of ```StratEngine::rename_pool()```. @agrover @trgill, do you agree?

**Comment by mulkieran** [comment]
See #459.

**Comment by agrover** [comment]
agree.

**Comment by trgill** [comment]
👍
