### ISSUE TITLE
Listing pools should also show remaining capacity

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#458]
Right now we just show the name, but it would also be very useful to have a property that exposed either used/free (DataBlocks?) or a percentage of the total space used. This would need to include both space in the pool unallocated to a Flex Layer device, as well as the amount of free blocks remaining in the flex layer data device.

**Comment by mulkieran** [comment]
We should avoid percentages, and break whatever we want to show down into its useful components to expose on the D-Bus. It seems like you're saying we have several values:
1. total blocks on all devices belonging to pool
2. blocks allocated to pool from those devices
3. blocks currently being used by the pool?

Right now, none of this is exposed in the pool, and only one value is exposed in the BlockDevMgr, ```avail_space()```. It would be necessary to write methods on BlockDevMgr to aggregate the appropriate values from their blockdevs, and maybe add a few facade methods to StratPool. Once that stuff is added in, exposing the value on the D-Bus should be no challenge.

**Comment by agrover** [comment]
`total` and `used` make sense to me, but `allocated` doesn't seem like something the user needs to know about, since growing the data device is an implementation detail.

But yea sounds right. Shouldn't be too hard.

Another question: What units? Blocks? Bytes? Sectors?

**Comment by mulkieran** [comment]
All our methods should return a precise value, i.e., they shouldn't have to round. But they shouldn't go any smaller than they need to make this happen. I suspect that means that the largest type that works will be Sectors, but I'm not sure.

**Comment by agrover** [comment]
sounds reasonable.

**Comment by mulkieran** [comment]
We have a lot of sizes.

* Total number of Sectors on the blockdev (T)
* Total number of Sectors on the blockdev that can be used for user data, i.e., aren't being taken up by metadata  (A)
* Total number of Sectors on the blockdev that can be used for more user data, i.e., aren't being take up by metadata or existing user data (F)

These are all independent numbers, perhaps we should export them all?

Other interesting numbers are:
* Total number of Sectors used for metadata (M)
* Total number of Sectors used for user data (U)

We can export any subset of three from which it is possible to calculate the remaining two. @agrover @trgill which do you like best?

**Comment by mulkieran** [comment]
The only thing we know about the thin pool is the segments which have been allocated to its data device and its metadata device, i.e. have been allocated to it from the existing blockdevs.

**Comment by mulkieran** [comment]
Let's try again:

* Total number of Sectors on all the blockdevs (T)
* Total number of Sectors on all the blockdevs not used by Stratis metadata (A)
* Total number of Sectors on all the blockdevs used by Stratis metadata (M)

Invariant: A + M = T

* Total number of Sectors used by mdv (MDV).
* Total number of Sectors being held for thinpool spare segments (TS).
* Total number of Sectors allocated to thinpool metadata dev (TM).

T - (M + MDV + TS + TM) = number of sectors remaining for thinpool data dev

If the the thinpool data dev does not contain any lvm metadata, then that is the number of sectors remaining for the user to dispose of.

**Comment by agrover** [comment]
I'd prefer exposing as little as possible 😃 

`total` is just T, which is easy, I think you already wrote code to add up blockdev sizes.

`used` is M + MDV + TS + TM + (*used data blocks (UDB)* where UDB is thinpool used blocks * datablock size).

?
