### ISSUE TITLE
Need to properly sync filesysystems in StratPool::teardown()

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#471]
Whatever is necessary to make sure that the user data is where it needs to be before thin pools and metadata vols go away must be done here.

**Comment by agrover** [comment]
loop and call teardown on all filesystems' thindevs? We're already calling MDV::teardown, so that's good.

**Comment by mulkieran** [comment]
I think that's a good start. But, @tasleson did mention something about making sure all data was synced, which ought to require more.

**Comment by agrover** [comment]
teardown is going to require that all filesystems are unmounted (DM won't let us tear down in-use thindevs). If they are unmounted then the filesystem has synced everything already.

**Comment by mulkieran** [comment]
Ok. I'll reasses w/ that information.
