### ISSUE TITLE
need to track mount point with filesystem

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#481]
xfs_growfs doesn't work given the devnode.

statvfs() also requires the mount point of the filesystem.

**Comment by agrover** [comment]
Hmm, well we can parse /proc/mounts to link these up. The next piece would be knowing when one of our filesystems was mounted, and I'm not aware how to do that yet, other than reading /proc/mounts periodically. (yuck)

**Comment by agrover** [comment]
Maybe udev!

**Comment by mulkieran** [comment]
We now have a function. ```get_mount_point```, so I think we can close this.
