### ISSUE TITLE
Investigate improvements into mnt crate

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#491]
We are using the `mnt` crate to parse /proc/mounts to get information we need to link mount points up with the Stratis thin devices that they may be on. This library may not be handling all cases, e.g. if multiple filesystems mounted on the same mount point. We should make sure it can meet our needs, possibly by contributing improvements as needed.

**Comment by tasleson** [comment]
@agrover

> e.g. if multiple filesystems mounted on the same mount point.

Did you mean to say multiple mount points for the same filesystem?

**Comment by agrover** [comment]
I think both are possible!

**Comment by tasleson** [comment]
Yes both are possible, I guess I don't know of a use case for multiple FS mounted to the same mount point as only that last mounted FS is visible, but if it can be done it should be handled in the API :-)

**Comment by agrover** [comment]
https://en.wikipedia.org/wiki/Union_mount#Linux I think e.g. Docker uses UnionFS

**Comment by agrover** [comment]
BTW we're not actually even using `mnt` crate right now, we're parsing `df` output!!!

**Comment by tasleson** [comment]
Oh, yes.  I forgot about union and overlay FS et. al.

**Comment by tasleson** [comment]
Objective achieved with `mnt 0.3.1` and PR #625
