### ISSUE TITLE
Create symlinks to filesystems under /dev/stratis/<poolname>/<fsname>

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#498]
Create symlinks to filesystems when they are created in a pool. These symlinks should also be updated for pool and fs renames.

**Comment by agrover** [comment]
The problem this solves is that after creating a filesystem in a pool, there is no easy way for the user to mount it. The user needs to use the DM-named `/dev/dm-X`, but only after finding out which one corresponds with their newly-created filesystem

Furthermore, the dm-X for a given device can change across reboots for various reasons. We need more stable names, like what LVM provides.

**Comment by mulkieran** [comment]
We should be very careful how we do this, lest we end up in a situation that nobody knows how to fix. See, for example, https://bugzilla.redhat.com/show_bug.cgi?id=1263441.

**Comment by agrover** [comment]
I don't think that particular BZ is applicable to us. But, I've been looking at udev code to try and understand possible negative interactions between it, and us maintaining symlinks as described.

(Q: Why not leverage udev rules to create & maintain these symlinks for us? A: Wouldn't the need to set up symlinks for filesystems including root in the initrd preclude using udev for this?)

**Comment by trgill** [comment]
This PR will be helpful for automated testing.  Currently there is no way to script creating a filesystem and mounting it.   The "name" doesn't correspond to /dev/mapper/<> node.
