### ISSUE TITLE
Remove old .mdv-<uuid> dirs in /dev/stratis

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#499]
Remove old directories where no-longer-existing MDVs used to be mounted.

OR, it may make sense to just clear /dev/stratis on startup, and then repopulate it as needed? Not sure.

**Comment by mulkieran** [comment]
We only dare remove these if we are absolutely certain that the corresponding pool is gone, not just temporarily missing. We should defer this for a while.

**Comment by agrover** [comment]
The code that creates it initially should also recreate it if it's missing.

**Comment by agrover** [comment]
current code creates and destroys these on the fly, so it's much less important to clean them up. Closing.
