### ISSUE TITLE
dbus::Message has a method called error() for an error reply

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#50]
We should decide whether we should be using this or not for error message. Should we be restricting its use to a certain kind of error message, maybe non-Stratis ones?

**Comment by mulkieran** [comment]
My guess is that creating a message using ```error()``` gives the Message a message type of Error as opposed to MethodReturn, MethodCall, Invalid, or Signal. We should figure out what our rules are for these.

**Comment by mulkieran** [comment]
There is no function that creates a message with message type "invalid" that I can see. Maybe that's just for the library's use.

**Comment by agrover** [comment]
I believe the code calling our methods is here:

https://github.com/diwic/dbus-rs/blob/master/src/methoddisp.rs#L763

and my reading of it is that if our function returns `Err()` then `error()` is called for us. I think we *could* call `error()` ourselves and return Ok() and this would look pretty much identical to the client (but I haven't tried it).

**Comment by mulkieran** [comment]
I did some experiments with using ```error()``` instead of ```return_message()``` and it looks to me like ```error()``` is just a quick and dirty shorthand for constructing a "method_return()" with an error, as you say. Our code is already so stylized that we have no use for ```error()```, so I'm going to go ahead and close this issue.
