### ISSUE TITLE
Only mount MDV when reading or modifying contents

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#500]
Right now, we mount the MDV and keep it mounted. This means that it shows up in `df`, which is unsightly, and worse, somebody might get the idea to poke around in there and change things.

It would be better if we are reading or modifying the MDV's contents to mount beforehand, and then unmount afterwards.

**Comment by mulkieran** [comment]
I believe this is a duplicate of #358.

**Comment by agrover** [comment]
yes! closing.
