### ISSUE TITLE
List all mount points for a given filesystem as a DBus property

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#501]
We now know we can find out the mount points for a block device by looking at `/proc/self/mountinfo`, although we don't have parsing implemented yet 😃. Therefore it should be possible to expose this via DBus. This would let stratis-cli list this as part of `stratis filesystem list`, which would be pretty handy.

**Comment by agrover** [comment]
@tasleson thoughts on feasibility?

**Comment by tasleson** [comment]
@agrover With the changes I've proposed to `mnt-rs` we could leverage that too, but going directly at `/proc/self/mounts` would be better for large configs.  Do we want to make this a `0.5` milestone?

**Comment by agrover** [comment]
fixed by #1108, closing
