### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by Kintaro** [stratis-storage/stratisd#507]
The formatting seems out of date. If I do a fresh clone and then run `cargo fmt`, I get a lot of changes.
I made sure to have the latest version of `rustfmt` installed.

**Comment by Kintaro** [comment]
Nvm, my fault. rustup was set to default to nightly and that caused problems as it seems.

**Comment by mulkieran** [comment]
We've found we have to pin rustfmt to certain versions, to avoid troublesome bugs in subsequent versions. It may be time to experiment with the newest version and see if it's not too much trouble.

**Comment by Kintaro** [comment]
Newest version fails on an attribute in pool.rs
