### ISSUE TITLE
```Message::iter_init()``` apparently supercedes ```Message::get_items()``` and is also faster

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#51]
Does it give you the items in reverse order, just like ```get_items()```?

**Comment by mulkieran** [comment]
```get1```, ```get2```, etc. are probably really the best way.

**Comment by agrover** [comment]
I think this is pretty much done? The only remaining `get_items` is in `get_dev_types`, and that may not actually take any args.

**Comment by mulkieran** [comment]
Yes, let's get rid of that code and then close this issue.
