### ISSUE TITLE
Figure out what to do with check()

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#525]
The use of `check()` is meant to be a placeholder for an improved event-handling system, which may also involve the development of a per-pool state machine.

**Comment by mulkieran** [comment]
Check actions should probably be reified. Some are just housekeeping, others are vital to correctness.

**Comment by agrover** [comment]
This may be a dupe of #632.

**Comment by agrover** [comment]
Moving out, since state machine won't happen for 0.5.

**Comment by agrover** [comment]
This issue is too nebulus, I think other issues more explicitly address what we need to do.
