### ISSUE TITLE
tolerate disks that are not initialized

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#529]
I installed Stratis on a system with some SAN disks that had unknown data and stratisd failed to start with: 

MDA region header CRC

**Comment by mulkieran** [comment]
Could you give the full stack trace?

**Comment by mulkieran** [comment]
```MDAHeader::from_buf()``` may return that error.
It is called only by ```MDARegions::load()```.
```MDARegions::load()``` is called only by ```BDA::load()```.

But ```BDA::load()``` looks like this:

```
    /// Load a BDA on initial setup of a device.
    /// Returns None if no BDA appears to exist.
    pub fn load<F>(f: &mut F) -> EngineResult<Option<BDA>>
        where F: Read + Seek
    {
        let header = match StaticHeader::setup(f)? {
            Some(header) => header,
            None => return Ok(None),
        };

        let regions = mda::MDARegions::load(BDA_STATIC_HDR_SIZE, header.mda_size, f)?;

        Ok(Some(BDA {
                    header: header,
                    regions: regions,
                }))
    }
```

Which means the only way that code is reachable is for ```StaticHeader::setup(f)``` to actually return a static header. To return a StaticHeader, in one of two places it must succesfully read the Stratis magic number and verify the crc of the header.

**Comment by trgill** [comment]
sorry for the noise... my mistake.
