### ISSUE TITLE
time to create a filesystem is over 10 seconds on some systems

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#532]
Testing on rhel-storage-11 with 2 pools using:

pool1: 4 17GB disks
pool2 3 17GB disks

We should understand where the time is going.

**Comment by mulkieran** [comment]
Woah!

**Comment by mulkieran** [comment]
What precise commands did you use?

**Comment by trgill** [comment]
I ran this script:

```
#!/bin/bash
DEVS1="/dev/sdc /dev/sdd /dev/sde /dev/sdf /dev/sdg /dev/sdh /dev/sdi"
FS_COUNT=10

stratis pool create pool1 $DEVS1

for((fs=1;fs<=$FS_COUNT;fs++))
do
   echo "create pool1-fs-$fs"
   stratis filesystem create pool1 "poo1-fs-$fs" 
done 

for((fs=1;fs<=$FS_COUNT;fs++))
do
   echo "destroy pool1-fs-$fs"
   stratis filesystem destroy pool1 "poo1-fs-$fs" 
done 

stratis pool destroy pool1
```

**Comment by trgill** [comment]
I've got a system setup that you can use if you'd like... just let me know via IRC.

**Comment by mulkieran** [comment]
I'ld be interested to know if this is still true. W/ changes to devicemapper it might not be. Can you give times as well as test script?

**Comment by trgill** [comment]
I ran the script above with an added "date" command before and after fs create.  The system is available via VNC if you'd like to check it out:

create pool1-fs-1
Wed Sep 27 10:01:10 EDT 2017
Wed Sep 27 10:01:25 EDT 2017
create pool1-fs-2
Wed Sep 27 10:01:25 EDT 2017
Wed Sep 27 10:01:41 EDT 2017
create pool1-fs-3
Wed Sep 27 10:01:41 EDT 2017
Wed Sep 27 10:01:57 EDT 2017
create pool1-fs-4
Wed Sep 27 10:01:57 EDT 2017
Wed Sep 27 10:02:13 EDT 2017
create pool1-fs-5
Wed Sep 27 10:02:13 EDT 2017
Wed Sep 27 10:02:28 EDT 2017
create pool1-fs-6
Wed Sep 27 10:02:28 EDT 2017
Wed Sep 27 10:02:45 EDT 2017
create pool1-fs-7
Wed Sep 27 10:02:45 EDT 2017
Wed Sep 27 10:03:01 EDT 2017
create pool1-fs-8
Wed Sep 27 10:03:01 EDT 2017
Wed Sep 27 10:03:17 EDT 2017
create pool1-fs-9
Wed Sep 27 10:03:17 EDT 2017
Wed Sep 27 10:03:33 EDT 2017
create pool1-fs-10
Wed Sep 27 10:03:33 EDT 2017
Wed Sep 27 10:03:49 EDT 2017

**Comment by mulkieran** [comment]
Well, I think the CLI is eliminated as a candidate for this problem. At least that returns immediately on my machine against the sim engine.

**Comment by mulkieran** [comment]
Closing this in favor of #617.
