### ISSUE TITLE
thinpool status's total_data value should have a known relationship with thinpool data

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#547]
Perhaps the ```total_data``` value should equal the sum of the segment lengths in the data device.

**Comment by mulkieran** [comment]
Perhaps this relationship should be checked occasionally as some kind of a health check. ```total_data``` should never be greater than the sum of the segments available.

**Comment by agrover** [comment]
How could this ever happen besides a kernel bug?

**Comment by mulkieran** [comment]
It would happen if there was a logical error in our code.

**Comment by mulkieran** [comment]
This would be thinpool invariant. Backstore has no knowledge of where the segments it gave away went to.

**Comment by mulkieran** [comment]
Closed as just part of #578.
