### ISSUE TITLE
The problem with ThinPool::extend_data

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#550]
It works like this:

1. Call devicemapper methods to extend the underlying thinpool, actually the thin pool's data device with the given segments. The problem here is that it's not actually extension, the last data segment of the device is coalesced w/ the first data segment of the incoming devices if possible.
2. Run the identical algorithm as is used in ```devicemapper-rs::LinearDev::extend()``` in order to make the segments that the thinpool stores match the segments on the linear device.
3. Return.

Step (2) is really brittle, since it relies for correctness on algorithms in two distinct libraries to be identical.

Proposal 1: Do not coalesce in either place. This is simple, but it is also brittle. Someone might re-add cleverness to devicemapper, causing a breakage in stratisd.

Proposal 2: Calculate the segments, coalescing as desired, in stratisd. _Set_ all the segments in the underlying devicemapper linear device. This needs a new function in LinearDev.

I prefer proposal (2) because ultimately it is less brittle and it gives all clients of devicemapper greater flexibility in how they arrange their segments.

**Comment by agrover** [comment]
I prefer P2 as well.

BTW I'm also ok with non-coalesced segments in devicemapper, it's just slightly wasteful of memory. I really just don't want them in stratisd because they'll increase our on-disk metadata size for no good reason.
