### ISSUE TITLE
Is there anyway to make Jenkins CI always succeed, for now?

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#551]
That way we can look at the output, but ignore the result at the same time.

Or, if this seemed more useful, have Jenkins only fail if all the tests succeed?

**Comment by trgill** [comment]
Ok - I'll do that.

Currently the tests are failing for what I think is a real problem.  It is a bit ugly when the tests fail - they leave the DM entries around.

I tried returning success and then rebooting the system - but Jenkins assumes the job failed if the node goes off during the build (even the post build steps).  I think I'll install another node, but this time not have the boot device be an LVM volume so we can just "remove_all".

**Comment by mulkieran** [comment]
I was hoping that when Jenkins pushes its stuff back to GitHub, it would be possible to just negate some boolean that indicates success of the whole run. If it involves going too deep, it's not worth it.

**Comment by mulkieran** [comment]
AFAIU, we don't have to worry about this anymore, as Jenkins tests are typically passing.
