### ISSUE TITLE
consider multipath devices in tests

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#552]
An example of the problem is if we initialized 1 path via the mpath device, but there are 2 paths to the LUN - find_all() will return 2 pool entries.

**Comment by mulkieran** [comment]
Won't LVM do something similarly wrong? I'm hoping that SID will, somehow, help us out in these troubles.

**Comment by trgill** [comment]
I think so.

**Comment by agrover** [comment]
Will it return two, or three, since Stratis would also find /dev/mpath0?

Can we use dev from the variable-length blockdev info to figure out which one to use? Or how about using the one called "mpath*" if we find multiple? (bleh)

**Comment by agrover** [comment]
I think we are correct wrt this now, cool! @trgill please reopen if some uncertainty remains.
