### ISSUE TITLE
tests/loopback: Implement limit changes similar to #553

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#558]
The justifications for #553 are also applicable to the loopbacked testing infrastructure.

**Comment by mulkieran** [comment]
We should postpone this until we consider the larger refactoring into unit tests a bit more carefully. The similarities between loopbacked and real exist, but the difference is that there is theoretically no limit on the number of loopbacked devices that can be constructed. This means that it is necessary to choose exactly one amount or a sensible upper limit, and that will require more thought.
