### ISSUE TITLE
filesystem::get_mount_point() should return Option<PathBuf>

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#577]
It would be better if get_mount_point() returned None when the file system is not mounted.  Currently an error is returned.

**Comment by mulkieran** [comment]
```EngineResult<Option<PathBuf>>``` seems like the way to go, to distinguish between "we have no idea, because, e.g., df failed", and "we know there is none".

**Comment by trgill** [comment]
thanks.  I updated the title of the issue.

**Comment by mulkieran** [comment]
@trgill It's all yours.

**Comment by mulkieran** [comment]
Closed by #603.
