### ISSUE TITLE
should we set UUID on XFS filesystem?

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#582]
XFS allows a user to set the UUID for a filesystem.

PR #543 sets the UUID for XFS to the corresponding UUID used by stratis.  (both the Filesystem and MDV)

Will this be helpful or just another thing that can get out of sync?

**Comment by agrover** [comment]
I think setting it to match Stratis uuids makes sense. 

You said not having xfs uuids was a less attractive option because it would require "no-uuid" option to be given when mounting, is that right?

**Comment by trgill** [comment]
I think the current version of XFS always has a UUID for a filesystem.

The "no-uuid" parameter comes into play with snapshots.  If we take a snapshot and don't change the UUID - mounting the snapshot would require "no-uuid".

In PR #543 we pass the "no-uuid"  parameter to get XFS to clear the log when we mount/umount the filesystem.

**Comment by agrover** [comment]
Thanks for the explanation.

So, I think the answer is "yes"? I can't think of any case where having them be different would be advantageous. Anyone?

**Comment by trgill** [comment]
Ok.  I agree having them be the same won't hurt and could help.

How about on the MDV filesytem?  In PR #543 I setup the MDV filesystem to the pool UUID.   I was thinking it could be useful and wouldn't do any harm.

**Comment by mulkieran** [comment]
Closed by #543.
