### ISSUE TITLE
Need a rule for --force option, what methods should have it, and what it shoudl mean for these methods

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#6]
CreateVolume() would require --force to create a new volume of the same name when the old volume has some data on it.
AddDevs() should have a --force option just as CreatePool() has  a --force option.

**Comment by agrover** [comment]
> CreateVolume() would require --force to create a new volume of the same name when the old volume has some data on it.

Better just to fail with an error I think.

> AddDevs() should have a --force option just as CreatePool() has a --force option.

Agree.

**Comment by agrover** [comment]
BTW it would be easier for us if we don't have to differentiate between a volume and a volume with data on it. Each volume is going to have at least the data of the filesystem's mkfs on it. Examining a filesystem to see if it's empty is best avoided -- unlinked files make this nontrivial, for example.

**Comment by mulkieran** [comment]
I'm aiming for as much consistency as possible. We should either have --force wherever it is meaningful, or not have --force anywhere and let the user do all the adjustments necessary so they can take the action they want to take.

I favor --force because it seems to put less of a burden on the user to figure out stratis internals.

I had overlooked the fact that a volume will always have a filesystem on it. So, in a sense, it always has data on it. In that case, I still would favor --force for CreateVolume(), with the difference that it would be required whenever there was an existing volume of the same name.

**Comment by agrover** [comment]
CreateVolume --force can cause data loss by implicitly removing the old volume, which I think isn't what people would expect. That's why I think in this case the user should have to explicitly remove (or rename) the old volume, and then they can create the new one, and --force is not needed.

**Comment by mulkieran** [comment]
I don't see what other meaning users _could_ expect from force.

So, the argument seems to work equally well against force option on CreatePool() or AddDevs() (It could destroy data, and the users might not expect it.) The addtiional problem with force on CreatePool() and AddDevs() is that Stratis might not do the cleanup of metadata very well. I seem to recall blivet having some kinds of problems with that, and sometimes you have to work pretty hard with lvm to force it to admit that a device that formerly belonged to it does not any more. With CreateVolume() Stratis is working w/ its own internal structures, so should be able to get it right.

**Comment by agrover** [comment]
I'm not saying users would expect another meaning from force, but I think the reasons we have it for CreatePool and AddDevs don't necessarily apply to CreateVolume. The former, if there is data (nonzero bytes in first N sectors) without force we'd be stuck asking the user to use `dd` to wipe it themselves before we could accept it. Yuck. For CreateVolume, we already have a way for the user to resolve the issue easily, by removing or renaming the existing volume, and then CreateVolume will work. CreateVolume --force seems like the thing that an admin could accidentally do -- typo maybe?-- late at night and then instantly regret.

In terms of what the user expects, I think we can also look at what ZFS and LVM do. `zpool create` has an `-f`, `zfs create` does not. `pvcreate` has an `-f` (and even an `-ff`!) but `lvcreate` does not.

**Comment by mulkieran** [comment]
So, the plan is to reserve --force for truly exceptional circumstances, where there doesn't exist another path for the user to make the action possible in the normal way.

**Comment by mulkieran** [comment]
I think we arrived at a different conclusion in our meeting than comment #6 states. So I really think we need to revisit this.

**Comment by agrover** [comment]
Yep.. just to be clear, I think we should have --force for using blockdevs in a pool, but not have --force for creating a new filesystem that destroys an existing filesystem.

reasons for --force on using blockdevs
- it's what users will expect. other tools like lvm, mkfs.xfs, zfs allow blockdevs with existing data to be reinitialized with an option that indicates the user acknowledges what's going on
- alternate solutions -- "overwrite w/o checking", "require dd to clear before using" both aren't as good. first is too unsafe, second requires the use of another tool (`dd`) that many users aren't familiar with and is very easy to use incorrectly.

reasons for *not* having --force option when creating filesystems
- There's an existing in-Stratis way to resolve this - just remove/rename existing filesystem before creating new one
- it's what users will expect. Existing volume managers don't have --force for e.g. lvcreate

That said, where does the disagreement lie? You said:
> So, the plan is to reserve --force for truly exceptional circumstances, where there doesn't exist another path for the user to make the action possible in the normal way.

to which I agree if it becomes:
> So, the plan is to reserve --force for truly exceptional circumstances, where there doesn't exist another path **within Stratis** for the user to make the action possible in the normal way.

**Comment by agrover** [comment]
Have we reached a consensus on this issue?

**Comment by mulkieran** [comment]
I think we're more or less on the same page, but I think we should keep it open, as we'll have to keep addressing this problem.

**Comment by agrover** [comment]
This discussion seems suitable for the design doc, since it's like a policy, or usability guideline. I've opened a design doc issue.

**Comment by mulkieran** [comment]
I believe this can be closed! (as we will not have the --force option).
