### ISSUE TITLE
Would be nice to find a way to make xfs_growfs a bit more quiet

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#605]
It's a bit of an inconvenience in testing output and might be inconvenient in the real world. But I don't think it's really urgent.

**Comment by tasleson** [comment]
I believe I've addressed this with: https://github.com/stratis-storage/stratisd/pull/629

**Comment by mulkieran** [comment]
Yeah, you might as well put in a "Resolves #605" in #629.
