### ISSUE TITLE
Message loop needs to not live in dbus_api.rs

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#61]
It needs to be in `main()`, and then if the dbus socket becomes readable, then we need to call our dbus code to handle the incoming request.

This is because we will also be expecting non-DBus events, such as timers, netlink events, and who knows what else.

I'm going to set a not-very close milestone for this because I do know we're only worried about DBus near-term, but this will need to happen at some point.

**Comment by mulkieran** [comment]
@agrover Could you expand on this at some point? I don't actually follow.

**Comment by agrover** [comment]
Currently, the thread in stratisd blocks waiting for new DBus activity by calling `c.iter(10000)` in dbus_api.rs run(). The only time we wake up is when there's something on DBus to handle. However, while stratisd needs to handle DBus requests it also may need to wake up and do work in response to other events, or maybe periodically.

We can use the example at https://docs.rs/dbus/0.4.0/dbus/struct.Watch.html as a starting point. This will allow us to poll on dbus activity and also anything else we'd like, in one loop.

**Comment by mulkieran** [comment]
Resolved by #248.
