### ISSUE TITLE
Remove devnode from blockdevsave

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#611]
See: https://github.com/stratis-storage/stratis-docs/issues/64#issuecomment-337901344.

Basically, if a blockdev will always have a devnode, then it can always report the devnode, so both BlockDev and BlockDevSave should have non-optional devnode.

If a blockdev will not always have a devnode, then both BlockDev and BlockDevSave should have optional devnode.

If devnode is dropped from BlockDevSave struct, then the version of the variable length metadata can be updated accordingly.

**Comment by mulkieran** [comment]
This is still an issue, i.e, BlockDev contains a devnode, but serde struct has an optional devnode.

**Comment by mulkieran** [comment]
Continues same.

**Comment by agrover** [comment]
How about we remove devnode from BlockDevSave, any objections?

**Comment by mulkieran** [comment]
It seems like a harmless action.
