### ISSUE TITLE
Correct saving of on-disk metadata. Document.

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#614]
see also #583 and [this discussion](https://github.com/stratis-storage/stratis-docs/issues/64#issuecomment-337403753).

We need to determine when saving state to on-disk metadata is correct wrt power failures, for MDV state as well. It should be centralized in the engine or pool code rather than being invoked explicitly in e.g. the D-Bus API code.

This should be written up in the design doc too. Proper handling of this is something potential contributors and users will want to see has been considered and implemented correctly.

**Comment by mulkieran** [comment]
See also #618 for a concrete example of the symptoms.

**Comment by agrover** [comment]
I'm going to defer this 0.5 -> 1.0, since nothing is *horribly* broken at the moment, but this needs more thought. There are a lot of different state-changing operations that we do, e.g. adding a blockdev, changing a fs name, etc. I think we need to think about ALL of them and probably have a comprehensive chart where we make sure all operations are handled properly to avoid data loss.

**Comment by mulkieran** [comment]
I'll call this obsolete.
