### ISSUE TITLE
libxfs?

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#616]
Can we code to libxfs instead of using the CLI?  Looks like Ceph links to libxfs.

https://github.com/qoriq-open-source/linux-v4.1.8-sdk/tree/master/fs/xfs/libxfs

**Comment by agrover** [comment]
I'm confused, qorig-open-source is related to Ceph somehow?

**Comment by trgill** [comment]
XFS team doesn't want us using libxfs.
