### ISSUE TITLE
stratisd restart failure

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#618]
restarting stratisd with an existing filesystem has recently started failing.

I created a filesystem in a pool with 4 devices.  start/stop stratisd causes the following error (stratisd doesn't start):

Specified new table "[(Sectors(0), Sectors(1572864), "linear", "252:64 73728")]" does not match kernel table "[(Sectors(0), Sectors(1572864), "linear", "252:64 73728"), (Sectors(1572864), Sectors(1572864), "linear", "252:64 1679360")]"

**Comment by agrover** [comment]
This is because the flex data device was extended but this was not saved to on-disk metadata.
