### ISSUE TITLE
Blockdev DBus objectpaths not removed when pool is removed

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#626]
We should automatically remove these when the pool is removed. The hard part is determining their object paths from `destroy_pool`. We can get to the Pool's Blockdevs but they don't remember their objectpaths. If we could iterate the Tree then we could remove all Blockdevs whose Pool property refers to the pool being destroyed, but the tree is not iterable.

I'm currently thinking if we add a `children: Vec<ObjectPath>` (or whatever type) to the pool's context then that would let us do it.

**Comment by mulkieran** [comment]
Related: #644.

**Comment by mulkieran** [comment]
We believe that this was fixed by #660.
