### ISSUE TITLE
Support cache tier

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#631]
1. List cache blockdevs in a pool

2. Add cache blockdevs

3. Remove cache blockdevs

4. Write-through caching only

**Comment by mulkieran** [comment]
From #686 .

> @mulkieran: based upon [this article you found](https://access.redhat.com/articles/2106521) and our discussion, and [this thread](https://www.redhat.com/archives/linux-lvm/2014-August/msg00016.html), it sounds like the configuration being considered assumes caching the thinpool data device (as opposed to the thin devs directly, which is not supported.) This then presents two issues: 1) this leaves the thinpool meta dev -- which should be quite "hot" access-wise -- uncached. 2) Caching doesn't support the origin device (in this case the thinpool data dev) being resized underneath it. # 2 leads to the implication that we would need to wrap data dev extensions with tearing down and recreating the cache, hurting the cache's effectiveness, and that we would also suffer reduced performance because of # 1 unless we did something else (such as moving the thin meta dev to the cache device, as that thread suggests, but that has its own complexities).

> Nothing impossible with this, but it sounds less than ideal.

> Another thought I had that could resolve both these drawbacks is to cache the entire available space in the pool: create a linear dev that glues together the usable space in all the blockdevs and use that as the cache origin dev. Flex layer devs sit on top of the cache layer, and all of them including the thin meta dev benefit. Thin data dev extensions would no longer invalidate the cache, but adding (or removing) a blockdev would.

> Thoughts?

**Comment by mulkieran** [comment]
Even if cache is right above blockdevs, it's still necessary to write metadata directly to the individual blockdevs, i.e., not through cache.

**Comment by mulkieran** [comment]
But, when we allocate space, we need to make sure we're allocating space from the cache device, in some sense.
