### ISSUE TITLE
add Stratis signature to libblkid

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#645]
Doing this will allow us to cleanly filter blockdevs that are reported to us by udev.

**Comment by agrover** [comment]
I think Tony is looking into this, assigning to him.

**Comment by tasleson** [comment]
Initial attempt: https://github.com/tasleson/utils-linux/pull/1

**Comment by tasleson** [comment]
This has been merged upstream: https://github.com/karelzak/util-linux/commit/f82b085c31b505ca596b5808520f9c4356d099f1
