### ISSUE TITLE
Use a library to manage the event loop

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#656]
We're doing it ourselves right now. We should look into Mio (still lowish level) or Tokio (higher-level) if the event loop continues to grow more complex.

**Comment by mulkieran** [comment]
This is getting less optional all the time, so I took off the enhancement label.

**Comment by agrover** [comment]
This assumes an implementation that @tasleson may choose to pick an alternative solution, so may become invalid, we'll see.

**Comment by agrover** [comment]
I don't know about mio, but I think recent dbus versions have added tokio support, we could look into that.

**Comment by mulkieran** [comment]
There's a separate dbus-tokio crate, now, but I think it is still a work-in-progress.

**Comment by agrover** [comment]
Not sure this is worth doing any more, since we have done more work to improve our event loop code, and other solutions are really more network-focused than what we need. Closing.
