### ISSUE TITLE
How should dbus API's createpool() method get the object path of new pool?

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#66]
Previously the engine returned the object path. It looks to me like that now the dbus API has the job of synthesizing the object path. But, in that case, the engine's createpool method must still return something, and it is currently defined to return nothing. Should it be returning a pool object? Should it be returning a pool name? DBus API must maintain a mapping between object paths and some identifier for pools, so this is an important question.

**Comment by mulkieran** [comment]
Or, we could assume that the name of the pool is the name it was given, and map object paths to pool names w/out a return value.

**Comment by agrover** [comment]
because of #5 we may want to view pool name as a changeable property, and use an unchanging uuid or something similar internally.
