### ISSUE TITLE
Data device never extends past half

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#693]
If I create a pool on a 6GB blockdev, the code does not extend the thinpool data device past 3G, causing the thinpool to go into an error state before it's strictly necessary. I think this is because we try to double the size each time, and `blockdevmgr.alloc_space()` fails if it cannot fulfill the entire request. @trgill can you take a look?

**Comment by trgill** [comment]
@agrover the original implementation used an expansion of 20%.  The feedback I got was:

"We should not use a percent here. We should come up with a simple algorithm that acknowledges powers of 2."

"It's not the amount I object to, it's the use of percentages at all, and the use of floats to represent percentages."

If you'd like to read the exchange: https://github.com/stratis-storage/stratisd/pull/417

I can easily change .alloc_space() to return the remaining space (rather than fail) - but I don't think that is going to work well either.  I think doubling or the next power of 2 won't scale.  I still think using a percentage would be better.

@mulkieran @tasleson

**Comment by agrover** [comment]
Yes, there's the one issue of how much space to try to get, but a separate issue is what to do when the requested space is not available. I think the first issue is what was discussed previously, and have opened #697 to continue that discussion. In this issue let's just discuss what to do when the requested space is not available.

**Comment by agrover** [comment]
@trgill I'm not sure we want to change .alloc_space() to return partial results. I think the other caller really does expect to get what it asks for. We could add another method that returned partial results capped to what's available, or the calling code could achieve similar by asking blkdevmgr for how much space is available, and then capping its request to that much. What do you think?

**Comment by trgill** [comment]
@agrover ok - do you think it would be a good idea to leave enough space for the meta to double (or  increase by 1/2?)...  maybe the function that returns partial results would be aware of meta or data allocation - and if it was for the data device - leave enough for one more meta expansion?  or is that just over complicating it?

**Comment by agrover** [comment]
I think the fact that other flex devs may also need to extend is better handled by not being too greedy in calculating how much we want each time (#697 again), so once we get here it's fair to give the entire partial result to the requester.

**Comment by trgill** [comment]
This is related to this issue and #697.  I think we may need to account for rate of consumption to get this right.  Currently with a single disk in a pool (17G) if we use fio to run: 
```
[write-and-verify]
rw=randwrite
bs=4k
direct=0
ioengine=libaio
iodepth=16
verify=crc32c
size=16G
```

We don't keep up with the expansion and the pool queues IO:

```
[ 1264.666592] device-mapper: thin: 253:7: reached low water mark for data device: sending event.
[ 1265.036176] device-mapper: thin: 253:7: growing the data device from 1536 to 3072 blocks
[ 1266.476654] device-mapper: thin: 253:7: reached low water mark for data device: sending event.
[ 1267.288749] device-mapper: thin: 253:7: switching pool to out-of-data-space (queue IO) mode
[ 1267.473486] device-mapper: thin: 253:7: switching pool to write mode
[ 1267.480588] device-mapper: thin: 253:7: growing the data device from 3072 to 6144 blocks
[ 1273.661426] device-mapper: thin: 253:7: reached low water mark for data device: sending event.
[ 1275.213646] device-mapper: thin: 253:7: switching pool to out-of-data-space (queue IO) mode
[ 1276.043801] device-mapper: thin: 253:7: switching pool to write mode
[ 1276.050907] device-mapper: thin: 253:7: growing the data device from 6144 to 12288 blocks
[ 1291.448955] device-mapper: thin: 253:7: reached low water mark for data device: sending event.
[ 1293.934905] device-mapper: thin: 253:7: switching pool to out-of-data-space (queue IO) mode
[ 1294.450548] device-mapper: thin: 253:7: switching pool to write mode
[ 1294.457665] device-mapper: thin: 253:7: growing the data device from 12288 to 24576 blocks
```

**Comment by trgill** [comment]
If we write the device sequentially with this fio setup:

```
[sector-write]
rw=write
direct=1
name=sequential-write-direct
size=16G
```

The expansion easily keeps up.

**Comment by agrover** [comment]
That's a related but different issue, which we should open a tracking issue for if we don't have one already (I didn't see one).

**Comment by agrover** [comment]
#803 should have fixed this specific issue.
