### ISSUE TITLE
get_mount_point failing because devnode is not listed in /proc/mounts

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#695]
Instead of /proc/mounts showing "/dev/dm-9" as the device, it is showing "/dev/mapper/stratis-1-d13578ce75854ce59bb906a7f3fc31c2-thin-fs-fc6d2af9621d43f784c38ae32dcd5e0f". As a result, `get_mount_point` returns None, and the snapshot code doesn't think it has to do the mount/unmount trick to clear the log before setting a new uuid, causing mounting the snapshot to fail.

**Comment by mulkieran** [comment]
So, who's wrong?

**Comment by agrover** [comment]
I don't know. "/dev/mapper/stratis..." is a symlink to /dev/dm-9, so why it is being shown in /proc/mounts instead of dm-9 I have NO idea. So I'd really like to know why!!

But since it's existing behavior and in the kernel it's unlikely to change 😦 . We may need to extend `mnt` crate to look at /proc/self/mounts, which includes major:minor.

cc @tasleson

**Comment by agrover** [comment]
this requires updates to mnt-rs, which I have made in a PR here: https://github.com/stemjail/mnt-rs/pull/4 so we can use major/minor to correlate with a mount point.

**Comment by agrover** [comment]
fixed by #817 for now, and will address in next release with #820.
