### ISSUE TITLE
Better algorithm for determining amount to extend flex volumes

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#697]
This issue is broken off from #693 to discuss the calculation to determine how much we should try to extend the data and metadata device each time its current allocation approaches full. (See also #417.) This is related, but *separate* from handling if there isn't remaining room in the pool to handle the requested extension.

Some earlier discussion has mentioned growing by a percentage of the current allocated size, or doubling each time (equivalent to a 100% growth percentage), but I'm not sure this is quite right. Does this do the right thing when a pool is very small, or, very large?

We could also factor in the total pool size, as well as perhaps limiting the request to some size, to give us the behavior we want at all pool and flex volume size.

**Comment by mulkieran** [comment]
From #433:

"it was noted that we should take into account the granularity of the allocation. For example, if allocating for data device in thinpool, anything less than a full data block is no use. There is plenty to do in this area."

**Comment by mulkieran** [comment]
This was addressed by #1094 via the ```calculate_request``` method. So, future issues can address themselves to that method.
