### ISSUE TITLE
We need to formalize all possible ways of specifying a device

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#7]

**Comment by agrover** [comment]
More details? I'm not sure we do if stat() works on whatever the user gave us and indicates it's a block device.

**Comment by mulkieran** [comment]
We definitely need to translate the links when specifying a device, and we need to do this within stratisd everywhere, and we need to be explicit that that is what we are doing, and we need to abstract that action well.

If we do that, then we are flexible if we wish to add other ways of specifying devices, as we may discover that we do.

It is possible that the sysfs path of a device might start to seem like a good way to specify a device, or the kernel device name, which is very important in journal logs, or some such.

Right now, this issue is just about being precise and specific about what we're doing and making sure that we do it everywhere.
