### ISSUE TITLE
Put dbus stuff in its own subdirectory before it gets big.

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#70]
And export constants and so forth as appropriate.

I think we should do this sooner rather than later.

I think that the contents of dbus_api.rs could be split into multiple files, for manager, for pool, and so on and that in this way any problems with circular dependencies can be avoided.

**Comment by agrover** [comment]
I hear ya, but I think we can so slower. See https://doc.rust-lang.org/book/crates-and-modules.html#multiple-file-crates , it should be straightforward to put in a dir later with minimal disruption, if needed.

We may be in a better decisionmaking position once the initial DBus API implementation is code complete.

**Comment by mulkieran** [comment]
Pretty soon, I should have an idea about how to generalize packing and unpacking the data for placing on or reading from the dbus. But I would like to put that stuff in a separate file, along with other helper functions that may arise like ```internal_to_dbus_error()```.

**Comment by mulkieran** [comment]
We could split the subdirectory into just three files. consts, api, and misc.

**Comment by mulkieran** [comment]
By PR #212.
