### ISSUE TITLE
Stratisd should always run in system main phase if installed

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#712]
Stratisd should be started and running in either of two cases: 1) if the user is using stratis-cli or another API-user against the D-Bus API (possibly to create a pool) or 2) if there are existing Stratis blockdevs, possibly forming pools, so stratisd can monitor for additional Stratis blockdevs being added, and to monitor active Stratis pools.

#711 accomplishes the first case, but with that we still don't cover the case where the API has not been accessed but we still want stratisd to have been started.

**Comment by mulkieran** [comment]
Related: #345.

**Comment by agrover** [comment]
Since D-Bus activation isn't an option for us any more, we should just run all the time if installed. I'm not sure if this is an issue for here (because we ship a systemd service file) or for downstream packaging, but it sounds like this is the behavior we should have.

**Comment by tasleson** [comment]
https://fedoraproject.org/wiki/Packaging:DefaultServices?rd=Starting_services_by_default

**Comment by tasleson** [comment]
BZ opened: https://bugzilla.redhat.com/show_bug.cgi?id=1630514

**Comment by tasleson** [comment]
Closing and using upstream BZ for tracking
