### ISSUE TITLE
interface names should follow recommendations

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#74]
https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names-interface

They're supposed to be namespaced by reverse domain name, so we can't use org.storage (which is perfect but we'd need to buy it :smile: ). I'd recommend org.freedesktop over com.redhat -- it's less "corporate", and is also used by a great many other interfaces.

**Comment by mulkieran** [comment]
This is maybe a Springfield agenda item, I will try to propose it next meeting.

**Comment by mulkieran** [comment]
This is more of a legal decision than an implementation or design activity.

**Comment by agrover** [comment]
Based upon mtg discussion, let's not worry about this for now. Closing.
