### ISSUE TITLE
It would be good if engine could report oddities w/ its state

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#740]
In particular, PR #690 introduces the possibility of continuing execution in the presence of incomplete or otherwise unusable pools. An example of an otherwise unusable pool is a pool that has a name clash w/ an already existing pool. Rather than reporting an error at the time that the problem is encountered, it would be better to report everything iffy about the state of the running engine, both the existence of incomplete pools and the existence of pools that conflict w/ existing pools, as well as other issue that may eventually be discovered to be necessary to deal with.

**Comment by jbaublitz** [comment]
This seems to be obsolete. I think we do this now.

**Comment by mulkieran** [comment]
I'm willing to close it. I think we do the example, and the general idea is vague.
