### ISSUE TITLE
Simplify on-disk metadata by mapping flexdev ranges directly on blockdevs

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#762]
See #722, which will insert an intermediate mapping representation between flexdevs and blockdevs into our on-disk metadata. This isn't what we want to support long-term, but this is ok for now, and we can revisit this and work to eliminate it after 0.5 but before 1.0 release.

cc @mulkieran

**Comment by mulkieran** [comment]
We should have a clear justification for why the current mapping setup is not desirable before we get started on this work.

**Comment by agrover** [comment]
I'm supposed to give Mulhern a rationale why to change on-disk metadata format.

**Comment by agrover** [comment]
I no longer think we can map flexdev ranges directly to blockdevs. Closing this in favor of #1014 .
