### ISSUE TITLE
Stratisd rpm package missing dependencies

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#768]
Package dependencies need to include:
* `xfsprogs`
* `device-mapper-persistent-data`

**Comment by tasleson** [comment]
@ignatenkobrain Please update the spec file to include these, thank you!

**Comment by ignatenkobrain** [comment]
@tasleson mind sending Pull Request over src.fedoraproject.org/rpms/stratisd?

**Comment by tasleson** [comment]
@ignatenkobrain Looks like @agrover already did this! :-)
