### ISSUE TITLE
Missing /dev/stratis causes failure to bring up pool(s)

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#773]
If `/dev/stratis` is missing we will fail to read up the metadata.  I'm not sure what's changed, but I'm kind of surprised this hasn't shown up before.

**Comment by agrover** [comment]
setup_devlinks should be creating /dev/stratis if it doesn't exist. setup_devlinks is called by StratEngine::initialize, which is called by stratisd::run. So yeah, either /dev/stratis should be there or stratisd should fail to start, as far as I can see.

**Comment by tasleson** [comment]
> setup_devlinks should be creating /dev/stratis if it doesn't exist.

This is done **after** we try to assemble the pools which require `/dev/stratis` to exist.

**Comment by tasleson** [comment]
Unit test: https://github.com/stratis-storage/stratisd/pull/777

**Comment by tasleson** [comment]
Someone please push a PR which create the directory in the appropriate place.  I really don't care where or how, just that it's messing up my forward progress with other stuff.
