### ISSUE TITLE
Multiple device mapper devices have same FS UUID

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#775]
If I create a stratis pool using a single device and create a single file system on it and run `blkid` on each device mapper device I get multiple devices which show the same fs UUID 
`d8dfc2d7-5472-4dee-ba3a-89484377dc25`  as the one that should be used by the end user.

``` bash
[root@strat disk]# ls -l /dev/dm-*
brw-rw----. 1 root disk 253, 0 Feb 19 11:47 /dev/dm-0
brw-rw----. 1 root disk 253, 1 Feb 19 11:47 /dev/dm-1
brw-rw----. 1 root disk 253, 2 Feb 19 11:47 /dev/dm-2
brw-rw----. 1 root disk 253, 3 Feb 19 11:47 /dev/dm-3
brw-rw----. 1 root disk 253, 4 Feb 19 11:47 /dev/dm-4
[root@strat disk]# dmsetup ls
stratis-1-054df9cec7d14b91b050d6ea32776f74-thin-fs-d8dfc2d754724deeba3a89484377dc25	(253:4)
stratis-1-054df9cec7d14b91b050d6ea32776f74-flex-thindata	(253:1)
stratis-1-054df9cec7d14b91b050d6ea32776f74-flex-thinmeta	(253:0)
stratis-1-054df9cec7d14b91b050d6ea32776f74-flex-mdv	(253:3)
stratis-1-054df9cec7d14b91b050d6ea32776f74-thinpool-pool	(253:2)
[root@strat disk]# stratis pool list
Name         Total Physical Size  Total Physical Used
some_pool                 36 GiB              598 MiB
[root@strat disk]# stratis filesystem list some_pool
not_using_uuid
[root@strat disk]# 
[root@strat disk]# blkid /dev/dm-0 
[root@strat disk]# blkid /dev/dm-1
/dev/dm-1: UUID="d8dfc2d7-5472-4dee-ba3a-89484377dc25" TYPE="xfs"
[root@strat disk]# blkid /dev/dm-2
/dev/dm-2: UUID="d8dfc2d7-5472-4dee-ba3a-89484377dc25" TYPE="xfs"
[root@strat disk]# blkid /dev/dm-3
/dev/dm-3: UUID="054df9ce-c7d1-4b91-b050-d6ea32776f74" TYPE="xfs"
[root@strat disk]# blkid /dev/dm-4
/dev/dm-4: UUID="d8dfc2d7-5472-4dee-ba3a-89484377dc25" TYPE="xfs"
[root@strat disk]# ls -l /dev/stratis/some_pool/not_using_uuid 
lrwxrwxrwx. 1 root root 9 Feb 19 11:47 /dev/stratis/some_pool/not_using_uuid -> /dev/dm-4
[root@strat disk]# 
```

Additionally I would expect that when this is working we have a single entry in `/dev/disk/by-uuid` which represents `/dev/stratis/some_pool/not_using_uuid`

``` text
/dev/disk/by-uuid
├── 565c8028-1774-42c5-b275-c1673f55b8b4 -> ../../sda3
├── 70f45ac9-1be5-4a75-ab21-f165cd96f759 -> ../../sda2
└── cc97b2a8-1f9e-490b-883b-e53da92116b3 -> ../../sda1
```

This bug is preventing us from having the ability to use a FS UUID in `/etc/fstab` and mount a stratis backed FS at boot time.

**Comment by trgill** [comment]
# blkid /dev/mapper/*stratis*
# stratis pool create p /dev/sdc /dev/sdd /dev/sde /dev/sdf
# blkid /dev/mapper/*stratis*
stratis-1-9e5a2bc4572b4aa4803347f913e98a20-flex-mdv: UUID="9e5a2bc4-572b-4aa4-8033-47f913e98a20" TYPE="xfs"
stratis-1-9e5a2bc4572b4aa4803347f913e98a20-flex-thindata: UUID="342cf265-98eb-4d6a-96e5-940bb8b56109" TYPE="xfs"
stratis-1-9e5a2bc4572b4aa4803347f913e98a20-thinpool-pool: UUID="342cf265-98eb-4d6a-96e5-940bb8b56109" TYPE="xfs"

### The thin data and thinpool devices have the same block ID.

# stratis filesystem create p fs1

# blkid /dev/mapper/*stratis*
stratis-1-9e5a2bc4572b4aa4803347f913e98a20-flex-mdv: UUID="9e5a2bc4-572b-4aa4-8033-47f913e98a20" TYPE="xfs"
stratis-1-9e5a2bc4572b4aa4803347f913e98a20-flex-thindata: UUID="342cf265-98eb-4d6a-96e5-940bb8b56109" TYPE="xfs"
stratis-1-9e5a2bc4572b4aa4803347f913e98a20-thin-fs-84856e63bea94fcb8b6eefe2ee26ff6c: UUID="84856e63-bea9-4fcb-8b6e-efe2ee26ff6c" TYPE="xfs"
stratis-1-9e5a2bc4572b4aa4803347f913e98a20-thinpool-pool: UUID="84856e63-bea9-4fcb-8b6e-efe2ee26ff6c" TYPE="xfs"

### After creating a filesystem the thinpool UUID changes and matches the filesystem.

**Comment by tasleson** [comment]
Simple LVM configuration with a single thinly provisioned LV on a single PV.

```
# tree /dev/mapper/
/dev/mapper/
├── control
├── testing-thin_lv -> ../dm-4
├── testing-thin_pool_lv -> ../dm-3
├── testing-thin_pool_lv_tdata -> ../dm-1
├── testing-thin_pool_lv_tmeta -> ../dm-0
└── testing-thin_pool_lv-tpool -> ../dm-2
```

``` bash
blkid /dev/mapper/*
/dev/mapper/testing-thin_lv: UUID="e21c5465-d4b0-41bf-8ef2-11a1cc44012e" TYPE="xfs"
```
I'm starting to wonder if I did the correct changes to `libblkid` which make it possible for this selective type of output.

**Comment by trgill** [comment]
If I bypass Stratis and just make the calls to dmsetup directly - the thin-pool and thin-dev report the same blkid:

```
/dev/mapper/xfs-test-pool: UUID="6aa6a70a-ac2a-4e3f-97b1-ba71224384dd" TYPE="xfs"
/dev/mapper/xfs-thin-dev: UUID="6aa6a70a-ac2a-4e3f-97b1-ba71224384dd" TYPE="xfs"
```

**Comment by tasleson** [comment]
`blkid` has a function called `sysfs_devno_is_lvm_private`.  This function opens up the file: `/sys/dev/block/*/dm/uuid` and checks to see if the UUID has the form:

```C
/* Private LVM devices use "LVM-<uuid>-<name>" uuid format (important
 * is the "LVM" prefix and "-<name>" postfix).
 */
```
Example lvm configuration from above:
```
cat /sys/dev/block/253\:*/dm/uuid
LVM-SfS2rQDvwkPdWuIVxkcSmsWTttkNAgNjS0smd7I6Aifq7wYLzdXAejWTP6gOpLAQ-tmeta
LVM-SfS2rQDvwkPdWuIVxkcSmsWTttkNAgNjGLDyaJHcbbTdAFN74ckycOHlhU3BBsYl-tdata
LVM-SfS2rQDvwkPdWuIVxkcSmsWTttkNAgNjcan3PzQd5ywJAkLDb0dxVJERta7v2wZA-tpool
LVM-SfS2rQDvwkPdWuIVxkcSmsWTttkNAgNjcan3PzQd5ywJAkLDb0dxVJERta7v2wZA-pool
LVM-SfS2rQDvwkPdWuIVxkcSmsWTttkNAgNjGa5JaKxrA0UvosbnpY1EMBiQi1kAFmz2
```

On a stratis configuration we get:
```
cat /sys/dev/block/253\:*/dm/uuid





```

Specifically:
```
xxd 253:1/dm/uuid
00000000: 0a
```

So it appears we aren't setting up a value for `/sys/dev/block/*/dm/uuid`, but even if we were we would have to mimic lvm to get blkid to work as expected.

My initial thought is this function should be renamed `sysfs_devno_is_dm_private` and have checks for both lvm and stratis, but I need to discuss with whoever came up with this check.

**Comment by agrover** [comment]
Veryyyyyy interesting!!

**Comment by agrover** [comment]
@tasleson I think this is completed? close?
