### ISSUE TITLE
Should set UUID on DM devices

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#782]
Right now we set DM name, but haven't set DM uuid, since uuid is kind of less a differentiated uuid field and more like a "second name" field. It sounds like for expectations of other code such as blkid, it would be good to set uuid. Setting uuid to be the same as what we're setting DM name may be the easiest thing to do.

cc @tasleson @mulkieran

**Comment by mulkieran** [comment]
I don't think it would be terribly difficult on the stratisd side. As far as I can tell, the difference between names and uuids for DM is that uuids are optional and can never be changed once set, while names are mandatory and can be changed. There's a bunch of tests in devicemapper-rs/src/dm.rs which appear to support this, and probably some docs somewhere also. You might want to consider if there's any situation where name and uuid might diverge, with nasty consequences, but I can't come up w/ one.

I think that @trgill is more familiar with the whole story of the problem being addressed here than I am.

**Comment by agrover** [comment]
Yeah I'm working on this. So far so good. dm interfaces are mostly ok but it looks like we will need to make a modification to `snapshot` to also take `Option<&DmUuid>`.
