### ISSUE TITLE
Handle DM events without polling

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#79]
See https://bugzilla.redhat.com/show_bug.cgi?id=817854

Devicemapper's mechanism for receiving events currently requires a thread to sleep in an `ioctl` call for each device in question. I'm working with the LVM team to add a new mechanism that will achieve this goal in a non-blocking, single-threaded fashion. Alasdair and I have a preliminary agreement on how to proceed, so I need to:
1. Write a doc describing the proposed solution and its implementation details
2. Get initial internal signoff from lvm-team
3. Write the code
4. Submit upstream, get it merged
5. Wait until a kernel is released that includes the new feature
6. Implement support in devicemapper-rs
7. Implement support in stratisd event loop

Until this happens, stratisd may need to poll -- read status from dm devices periodically to make sure everything is fine.

**Comment by agrover** [comment]
This is queued up in the DM maintainer's git repo. If everything goes as planned it should be in kernel 4.13. So we're currently in step 5.

**Comment by agrover** [comment]
deferring to a later milestone since kernel support is still unreleased (coming in 4.13)

**Comment by mulkieran** [comment]
I think this could be said to be resolved, as much as possible at this time, by #598.
