### ISSUE TITLE
Get explicit user permission to use extra space on a blockdev

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#792]
If a blockdev has grown, don't use beyond the previously seen capacity until the user has explicitly said we may.

**Comment by agrover** [comment]
This could be something like a method off blockdev, named "extend" or something. No arguments (beyond implicit specified blockdev) needed. Engine code would then get the current actual size of the blockdev, and if larger than recorded size, update the recorded size. It might get a little tricky because of the linear origin dev, and other things that might not like blockdev size changing underneath.

**Comment by mulkieran** [comment]
What would be the purpose of this change.

**Comment by agrover** [comment]
Allowing Stratis to use the extra space on a blockdev if somehow it was enlarged underneath us.

**Comment by mulkieran** [comment]
Hmmm, I will come up with some more specific questions next week.

**Comment by agrover** [comment]
This is very much a stretch goal for 1.0.

**Comment by mulkieran** [comment]
Closed in favor of #1578.
