### ISSUE TITLE
I can't move stuff around in the project view anymore

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#80]
Even if I'm in Stratis CLI where I'm the administrator, but also here.

**Comment by agrover** [comment]
did it used to work?? According to how I read it, all members of stratis-storage org should have default admin privs for all repos. There's no higher setting. Maybe this is a bug? Projects are a new feature, is the only thing I can think of.

**Comment by mulkieran** [comment]
I believe it used to work. I can't add new issues to the Project, I can't move ones added to the project view to different categories.

**Comment by agrover** [comment]
I've submitted a question about this to github help.

**Comment by agrover** [comment]
Got a response (actually on Friday, sorry for delay):

> Hi Andy!
> 
> Thanks for writing in!
> 
> Unless I am missing something, I don't see a permissions related problem. If mulkieran is the only person having a problem, it could be a browser related issue? I am not sure though. Could mulkieran write us or participate here in this thread? Are they using any extensions that may interfere?
> 
> If they are referring to stratis-cli, the team they are in only gives read only access, which would explain this. But if it's happening to stratisd too, then it must be something else.
> 
> Cheers,
> Petros
>

**Comment by mulkieran** [comment]
As a Stratis Storage team member I have admin permissions to all our repos. So, this ought to apply:

```


The Stratis Storage organization has their default repository permission set to admin. This means that every member of this organization has admin access to this repository, regardless of the team and collaborator access specified below.

To change or remove this organization's default repository permission, contact one of the organization's owners.
```

I tried changing the permissions anyway in Stratis CLI and it had no effect.

I don't use a whole lot of browser extensions and I haven't added any that I can remember recently, so that is not the issue. Are you able to move stuff around in the project view?

**Comment by agrover** [comment]
yes, I still can. @trgill can you try and see if you have the same issue?

**Comment by mulkieran** [comment]
It was a GNOME thing, rebooting fixed the problem.
