### ISSUE TITLE
Need test(s) to ensure meta data backwards compatibility

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#808]
After release 1.0 it will be imperative that Stratis works with older meta data.  We need to devise a test to ensure that from release to release we can successfully read in and process meta data as it changes over time.

**Comment by agrover** [comment]
see https://github.com/stratis-storage/stratisd/issues/1014#issuecomment-414145026

**Comment by mulkieran** [comment]
We can wait to worry about the tests when we do change our metadata.
