### ISSUE TITLE
Many fewer methods should return StratisResult type.

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#81]
At least, we need to separate the external view by clients of the dbus API from the internal view of the engine. Right now StratisResult is for both.

Probably, it would make sense to make a new return type for the engine, something like EngineResult, which will have its own internal error type as well.

**Comment by agrover** [comment]
yup. You're currently working on this, I assume?

**Comment by mulkieran** [comment]
Ok! I'm glad we're agreed.

**Comment by mulkieran** [comment]
Closed by #65.
