### ISSUE TITLE
Stratis block device cleared with wipefs is unable to be used as stratis device

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#822]
With the latest changes to `libblkid` we can identify and seemingly clear a device, eg.

```
# ./blkid
/dev/sda1: UUID="cc97b2a8-1f9e-490b-883b-e53da92116b3" TYPE="ext4" PARTUUID="9c220e1f-01"
/dev/sda2: UUID="70f45ac9-1be5-4a75-ab21-f165cd96f759" TYPE="swap" PARTUUID="9c220e1f-02"
/dev/sda3: UUID="565c8028-1774-42c5-b275-c1673f55b8b4" TYPE="ext4" PARTUUID="9c220e1f-03"
/dev/sdb: UUID="a30ef7337e1945498fc9cdafcd0d4b7e" POOL_UUID="ff2a2962d27c489491aa016db808886d" BLOCKDEV_SECTORS="75497472" BLOCKDEV_INITTIME="1520269046" TYPE="stratis"
```

```
# ./wipefs -a /dev/sdb
/dev/sdb: 16 bytes were erased at offset 0x00000204 (stratis): 21 53 74 72 61 30 74 69 73 86 ff 02 5e 41 72 68
```

```
# ./blkid
/dev/sda1: UUID="cc97b2a8-1f9e-490b-883b-e53da92116b3" TYPE="ext4" PARTUUID="9c220e1f-01"
/dev/sda2: UUID="70f45ac9-1be5-4a75-ab21-f165cd96f759" TYPE="swap" PARTUUID="9c220e1f-02"
/dev/sda3: UUID="565c8028-1774-42c5-b275-c1673f55b8b4" TYPE="ext4" PARTUUID="9c220e1f-03"
```

Yet when I try to create a pool using the cleared device I get

```
# stratis pool create some_pool /dev/sdb
Execution failed: 1: Device /dev/sdb appears to belong to another application
```

The output message from `wipefs` indicates that we cleared one copy, maybe not the second.  However, `blkid` fails to recognize the device as a Stratis device even though `blkid` should check both copies.  This could be an issue with `libblkid` failing to recognize second copy as wipefs failed to clear second copy or it actually did clear both copies and Stratis is being very careful to not step on the device.

**Comment by tasleson** [comment]
This was actually a Stratis bug, see: https://github.com/stratis-storage/stratisd/pull/825

**Comment by tasleson** [comment]
With the layout corrected:
```
# ./wipefs -a /dev/sdb
/dev/sdb: 16 bytes were erased at offset 0x00000204 (stratis): 21 53 74 72 61 30 74 69 73 86 ff 02 5e 41 72 68
/dev/sdb: 16 bytes were erased at offset 0x00001204 (stratis): 21 53 74 72 61 30 74 69 73 86 ff 02 5e 41 72 68
```

**Comment by tasleson** [comment]
Stratis still refuses to use the block device though.

**Comment by agrover** [comment]
iirc Stratis won't use a blockdev if first 4 or 8K of bytes are not completely zeroed.

If we wanted to loosen this by explicitly checking for other signatures, I think we'd need a way to call libblkid to have it check, I think?

**Comment by tasleson** [comment]
Switching gears on this one to leverage the udev db instead of calling into libblkid.  The reason for this is that blkid will already have been called to figure out what a device is before we get the udev event, thus we don't need to call into libblkid again to figure out what's on the disk.
