### ISSUE TITLE
use libmount instead of mnt-rs

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#824]
https://github.com/tailhook/libmount

libmount has support for parsing mountinfo, as well as possibly being a nicer-to-deal-with API than Nix for calling mount() and umount(). We also might find remount-ro capability handy for handling out-of-space.

**Comment by tasleson** [comment]
libmount doesn't support umount or umount2

**Comment by agrover** [comment]
So, better to stick with mnt-rs?

**Comment by mulkieran** [comment]
A while back we agreed to have issue be "in progress" if being worked on. Only the PRs go "in review".

**Comment by tasleson** [comment]
Fixed with https://github.com/stratis-storage/stratisd/pull/1007
