### ISSUE TITLE
BDA unit test: Corrupt & zero all combinations of disk layout and copies and test for expected outcome(s)

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#826]
We discovered fairly late in the development process that the BDA layout was incorrect.  This was found when integrating with the external tool `libblkid` where we were not locating the stratis signature for the second copy.  After code inspection the issue was found and corrected: https://github.com/stratis-storage/stratisd/pull/825

The existing Stratis code is correctly reading the location of the second copy, the issue was that the second copy wasn't in the correct location.  Thus, if the first copy didn't pass all the checks the second copy would have offered no additional value.

To ensure that the on disk layout is correct and working as designed it would be good to test the following scenarios:

1. Both BDA copies good => Result in good BDA retrieval
2. Corrupt only primary copy (incorrect checksum) => Result in good BDA retrieval
3. Zero only primary copy => Result in good BDA retrieval
4. Corrupt only secondary copy  (incorrect checksum) => Result in good BDA retrieval
5. Zero only secondary copy => Result in good BDA retrieval
6. Corrupt both copies => Failure to retrieve BDA
7. Zero both copies => Failure to retrieve BDA
8. Corrupt Primary, Zero secondary => Failure to retrieve BDA (And vice versa)

It would also be good to validate that the reserved areas are zero.

Additionally we should have the [discussion](https://github.com/stratis-storage/stratisd/issues/210) on whether or not we want to correct corrupt or missing BDA when we discover it, to avoid the cases where we only have one copy and no backup.

**Comment by tasleson** [comment]
Related to https://github.com/stratis-storage/stratisd/issues/210

**Comment by mulkieran** [comment]
We agreed a while back that issues should be in "in progress" (unless we're being asked to review the issue, I guess), so I'm moving this to "in progress" column.
