### ISSUE TITLE
xfs corruption with pool on NVMe device

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#831]
use: dell-r730-011

stratis pool create p1 /dev/nvme0n1
stratis filesystem create p1 fs1 
mount /dev/stratis/p1/fs1 /tmp/mp

fio --filename=/tmp/mp/fio-test-file ~/fio-tests/seq_write.fio

The fio test writes 50G - the NVMe device is 3TB.  Space isn't the issue.  XFS gets corrupted after:

thin: 253:4: growing the data device from 12288 to 24576 blocks

**Comment by tasleson** [comment]
This looks like the problem I ran into and wrote off as a out of space event, which it may not have been

https://github.com/stratis-storage/stratisd/issues/812

**Comment by tasleson** [comment]
I've tried the following twice:

* Create a Stratis pool and FS on a physical disk of 36G
* mount the Stratis device, eg. `/mnt/dupe`
* Rsync some data to it: 
`rsync -avP --exclude='/dev' --exclude='/proc' --exclude='/sys' --exclude='/boot' --exclude='/mnt' / /mnt/dupe`
* umount `/mnt/dupe`

Then I try to re-mount and I get
`mount /dev/stratis/some_pool/some_fs /mnt/dupe/
mount: /mnt/dupe: wrong fs type, bad option, bad superblock on /dev/mapper/stratis-1-5f821662b94040029cad1cc8a81af944-thin-fs-e6ed324d51d446e5811081b6442bb1bf, missing codepage or helper program, or other error.`

The journal is showing:
```
Mar 12 10:46:22 strat kernel: device-mapper: thin: 253:3: reached low water mark for data device: sending event.
Mar 12 10:46:24 strat kernel: device-mapper: thin: Data device (dm-2) discard unsupported: Disabling discard passdown.
Mar 12 10:46:26 strat kernel: device-mapper: thin: 253:3: growing the data device from 1536 to 3072 blocks
Mar 12 10:47:25 strat kernel: XFS (dm-5): Unmounting Filesystem
Mar 12 10:47:38 strat kernel: XFS (dm-5): Mounting V5 Filesystem
Mar 12 10:47:42 strat kernel: XFS (dm-5): Log inconsistent or not a log (last==0, first!=1)
Mar 12 10:47:42 strat kernel: XFS (dm-5): empty log check failed
Mar 12 10:47:42 strat kernel: XFS (dm-5): log mount/recovery failed: error -22
Mar 12 10:47:43 strat kernel: XFS (dm-5): log mount failed
```

This is gating https://github.com/stratis-storage/stratisd/issues/635

**Comment by trgill** [comment]
@tasleson ok if I close this issue?

**Comment by tasleson** [comment]
@trgill It appears to be working for me, thanks!
