### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#839]
Investigate supporting Stratis pools in Kubernetes. Does this make sense to do, and if so, how?

**Comment by mskarbek** [comment]
CSI - https://github.com/container-storage-interface/spec

**Comment by agrover** [comment]
https://github.com/kubernetes-incubator/external-storage

**Comment by agrover** [comment]
Not release critical for Stratis 1.0.

**Comment by mulkieran** [comment]
Too speculative to retain...
