### ISSUE TITLE
Stratisd: Sequencing issue @ boot

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#846]
Stratisd when started will assemble block devices and provide a dbus API for user space.  We want to assemble the block devices before the system starts mounting file systems, so that Stratis block devices in the `fstab` are mounted.  The existing service [file](https://github.com/stratis-storage/stratisd/blob/master/stratisd.service) is constructed with both requirements in place, but they are incompatible.  In it's current form when we boot we get 1 or more errors in the journal that look like:

```
Mar 15 16:45:35 strat systemd[1]: ldconfig.service: Found ordering cycle on local-fs.target/start
Mar 15 16:45:35 strat systemd[1]: ldconfig.service: Found dependency on local-fs-pre.target/start
Mar 15 16:45:35 strat systemd[1]: ldconfig.service: Found dependency on stratisd.service/start
Mar 15 16:45:35 strat systemd[1]: ldconfig.service: Found dependency on dbus.socket/start
Mar 15 16:45:35 strat systemd[1]: ldconfig.service: Found dependency on sysinit.target/start
Mar 15 16:45:35 strat systemd[1]: ldconfig.service: Found dependency on systemd-update-done.service/start
Mar 15 16:45:35 strat systemd[1]: ldconfig.service: Found dependency on ldconfig.service/start
Mar 15 16:45:35 strat systemd[1]: ldconfig.service: Job local-fs.target/start deleted to break ordering cycle starting with ldconfig.ser
vice/start
```

If I edit the service file and remove the dbus requirement, then the daemon will start up before the file systems get mounted and exit with:

```
Mar 15 16:56:25 strat stratisd[341]: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Mar 15 16:56:27 strat systemd[1]: stratisd.service: Main process exited, code=exited, status=1/FAILURE
Mar 15 16:56:27 strat systemd[1]: stratisd.service: Failed with result 'exit-code'.
```
Apparently because dbus services are not yet started.

Possible solutions:
1. We add an option to stratisd to assemble and exit after setting up the dm devices.  We create a `oneshot` service file to run it before file systems get mounted.  We also have the service file that will start the service as a dbus service daemon at the appropriate time.

2. We modify the daemon to periodically check if it's able to bring up the dbus interface and do so when it is available.  This would require us to slow poll in the event loop until it was available.

Other solutions...?  Maybe there is a different target that will get us where we need to be...

**Comment by agrover** [comment]
Maybe this is a dumb question, but is there anything preventing dbus from being started earlier? Or just has nobody ever needed it so early?

> 1. We add an option to stratisd to assemble and exit after setting up the dm devices. We create a oneshot service file to run it before file systems get mounted. We also have the service file that will start the service as a dbus service daemon at the appropriate time.

what would the oneshot service do that stratisd-init hadn't already done?

I'd be fine with either 1 or 2, fwiw.

**Comment by tasleson** [comment]
> Maybe this is a dumb question, but is there anything preventing dbus from being started earlier? Or just has nobody ever needed it so early?

Dunno, good question.

**Comment by tasleson** [comment]
Note: option 2 would offer the ability to handle dm events which would likely be preferred.
