### ISSUE TITLE
Explicitly fail to run if not root

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#853]
As suggested by @tasleson,

Currently, if one runs stratisd without root permissions, something will undoubtedly fail and return an error instead of running successfully. But that error message could be something nonintuitive, like a DBus or DM error message.

Maybe we should explicitly check and fail with an appropriate error message instead.

**Comment by agrover** [comment]
Wow, I tested this manually... Looks like I should've finished the job properly and added an actual test.

This and the --help thing, should they be opened as new bugs?

**Comment by mulkieran** [comment]
Regarding the original issue...perhaps it is part of something that could be solved just as well by generic error-handling.
