### ISSUE TITLE
Add ability to distinguish setup_pool failures

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#854]
Today `setup_pool` can fail for a number of different reasons:

* Binaries missing
* Incompatible metadata
* Pool with same name (or same UUID?)
* One or more devices which are missing from the pool
* Others ...

Many of these errors aren't really expected or recoverable and we should be able to distinguish between them and ones that are more likely or expected, so that the code that is calling `setup_pool` can make decisions on them and take the appropriate action(s).

**Comment by mulkieran** [comment]
This was resolved by #1779, closing.
