### ISSUE TITLE
Record stack trace when a dbus method fails due to EngineError

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#855]
This is a little tricky because dbus methods fail only for dbus reasons. If there is an engine err, the dbus method succeeds, but with an error value. These error values are not always quite enough to go on for us developers to fix the cause. A stack trace from engine errors would be really helpful.

One way we could do this is by putting it in `engine_to_dbus_err_tuple`. We could use the "backtrace" crate, which we already include as a dependency of a dependency, to log the original error location.

In the future, we may be able to use error_chain or Failure crates to do this for us automatically and more featurefully, but for the moment I think we could get a lot of the benefit by directly using "backtrace" ourselves.

**Comment by mulkieran** [comment]
It looks like I'm currently working on this.

**Comment by mulkieran** [comment]
I'll call this obsolete.
