### ISSUE TITLE
making dbus calls doesn't appear to require root permissions

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#861]
Invoking the cli as a normal user to e.g. create a pool is working, when it should not work due to insufficient permissions.

**Comment by tasleson** [comment]
We need something like: https://sourceware.org/git/?p=lvm2.git;a=blob_plain;f=scripts/com.redhat.lvmdbus1.conf;hb=refs/heads/master

**Comment by tasleson** [comment]
Correction merged
