### ISSUE TITLE
Supporting a Python lib that wraps D-Bus

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#862]
Even with the use of D-Bus as our language-neutral API, we may wish to make it *even easier* for other programs to control Stratis, with specific language libraries that do the work of converting the D-Bus Stratis API into a more language-idiomatic API. Probably the best language to initially support this way would be Python, since we both already have done some of the work in the course of implementing stratis-cli, and because potential early users of the Stratis API, such as Anaconda, are also written in Python.

The work here would be to pull out the interface definition from stratis-cli (leaving just command parsing and info display), put them into a library provided by stratisd, and then change stratis-cli to use the new library. This new library would be supported, and would allow Python projects to integrate Stratis support without the D-Bus learning curve.

**Comment by mulkieran** [comment]
You could pull out the interface definitions from the Python src used for the tests in the ```client-dbus``` tests as well.

**Comment by junland** [comment]
Would integrating a Unix socket on the daemon side and having a arbitrary command API be a bit simpler? It would be another API that would have to be documented (Thou it would be the same case as a Python lib), however you are able to target most if not all languages since Unix sockets are common in stdlibs. The only thing I see a problem with going this way is that you will have to add some extra logic to prevent conflicts if both DBus and the Unix socket are sending commands at the same time (Which is highly unlikely but it is a possibility).

**Comment by agrover** [comment]
D-Bus is basically a fancy way of having a standardized form of a Unix socket API. Since we already have that, as well as Python code that acts as a D-Bus client, I continue to believe it would be easier to turn that into a standalone Python lib than starting from scratch. (If you're interested in alternative socket APIs, https://varlink.org/ may also be of interest.)

That said, I don't believe adding another socket API would cause conflicts. `stratisd` has a single-threaded event loop, so separate API's calls would be handled sequentially. If you want to use `stratisd` as a testbed for new API ideas, you can look at `run()` in daemon src/stratisd.rs. That's where it opens a bunch of fds and monitors them for activity. You could open another socket there fairly easily and dispatch to a handler function that parses messages and makes `engine` calls.

**Comment by mulkieran** [comment]
We have all the libraries for D-Bus support that we are going to have, the top-level ones being dbus-python-client-gen and dbus-client-gen, and we use them in a lot of testing contexts and we plan to use them for our ansible module. We can close this.
