### ISSUE TITLE
Use newly-stable rustfmt version

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#876]
Instead of being pinned to the old 0.8.3 version of rustfmt, use the new version that is included in rust 1.24 (and packaged in Fedora as rustfmt-preview (still only available in F27 updates-testing repo)).

This will get us back on a supported version, and also alphabetizes use statements for us, yay! Bad news is there will be a lot of whitespace changes, so we'll need to watch out for that.

Also, update README to remove reference to rustfmt 0.8.3.

**Comment by mulkieran** [comment]
Please refer to #515 for previous history of the effort to move away from current pinned version.

**Comment by mulkieran** [comment]
I don't think we should do this until we can be sure that everybody is able to run rustfmt on their own machine. That is, we don't want to be in a situation where we have to wait for Travis to tell us that our code isn't formatted properly and then hand-copy the relevant changes into our own code from Travis.

**Comment by mulkieran** [comment]
#880 shows the effect of running rustfmt-nightly with the new defaults. It compiles on nightly, but that's not really a guarantee that it would compile on stable.

**Comment by mulkieran** [comment]
The new defaults are fine w/ me.

**Comment by agrover** [comment]
done
