### ISSUE TITLE
Need to ensure data that we write is actually flushed

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#892]
We were using ```flush()``` to ensure that, but it turns out that ```flush()``` only flushes in app buffering.

This is going to cause problems in the metdata module, because, in order to make testing easier, metadata functions generally take a generic F which implements ```Seek + Write```.

**Comment by agrover** [comment]
We could add a new trait with a fsync method, and implement for File (calls File::sync_all()) and Cursor (a no-op).
