### ISSUE TITLE
Use an API for XFS

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#899]
We'd like to not use cmdline tools to manipulate XFS, we'd like an API. Eric Sandeen seemed open to it but wanted guidance on what the API should look like.

**Comment by bl33pbl0p** [comment]
Perhaps something filesystem based? /sys/fs/xfs already exists, I don't know if transactional stuff is easy that way (commit these various things now, perhaps having a commit file in the same dir where you plug values in different files)? Just a suggestion.

**Comment by mulkieran** [comment]
Too future to keep.
