### ISSUE TITLE
Move work off the event loop

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#904]
long-running tasks return a job id. task takes as long as it wants and then sets the job as completed with a status
2nd level problem: task with subprocesses have a timeout on subprocessesm b/c crappy subprocesses might hang?

**Comment by tasleson** [comment]
@trgill Makes a good point that the underlying C library that dbus-rs uses isn't thread safe.  Thus all work pertaining to dbus-rs needs to occur in the same thread of execution.

**Comment by mulkieran** [comment]
Obsoleted by https://github.com/stratis-storage/project/issues/86.
