### ISSUE TITLE
Having trouble running tests from a separate tests directory.

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#91]
See #90.

**Comment by agrover** [comment]
You might want to clone and take a look at how https://github.com/rust-lang/cargo does it, esp. tests/cargotest and tests/* overall. They appear to build their app as a library, and then use that for testing.

**Comment by mulkieran** [comment]
Currently, putting unit tests in modules seems to be quite adequate and fit with the plan of making the D-Bus API _the_ API. The problem can be revisited later if necessary. I don't know of a way to generate docs for non-public parts of the API, which would be handy for us developers. On the other hand, not generating docs for non-public parts does kind of make sense.
