### ISSUE TITLE
Write a test that exhausts data space for a pool 

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#918]
Use test to validate/test XFS settings over dm-thinp.

**Comment by mulkieran** [comment]
Now that test infrastructure changes are in, I think it makes sense to put up the actual test, which I believe is in previous commit https://github.com/stratis-storage/stratisd/pull/920/commits/d43b5c915666fe247a0705d877fa74bacdc5035a.

**Comment by trgill** [comment]
@mulkieran I'll open a PR with that commit?

**Comment by mulkieran** [comment]
I think this is closed by #966.
