### ISSUE TITLE
dm logging - thin: Couldn't  open thin internal device

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#980]
When test run - the following is logged by DM (but the test passes):

[  +0.060330] device-mapper: table: 253:5: thin: Couldn't open thin internal device
[  +0.000149] device-mapper: ioctl: error adding target to table
[  +0.104472] device-mapper: thin: Data device (dm-2) discard unsupported: Disabling discard passdown.

We should understand why this is being logged.

**Comment by mulkieran** [comment]
We don't know anything more about what test is causing it?

**Comment by trgill** [comment]
These log messages are triggered by real_test_thindev_destroy.

**Comment by trgill** [comment]
The log message is no longer triggered by our test suite.  Jenkins test server hasn't logged it since Aug 24th.  Closing until we see it again.
