### ISSUE TITLE
Not all binaries needed in initrd binary

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#987]
With the merge of #986, stratisd will fail to run if all binaries aren't found. However, it only uses a subset of binaries from initrd, so it should only check for those if compiled for that use.

**Comment by mulkieran** [comment]
My concern is that this issue about exiting if some binaries that stratisd usually requires, but which aren't available in the initramfs, is just the tip of the iceberg of the problem.

We have a mechanism, conditional compilation, which is supposed to prevent D-Bus actions from being executed at boot. But how do we know that xfs-dependent actions won't be executed at boot, causing stratisd to fail one way or the other? AFAIK, the answer is that we do not.

If we already had a mechanism to deal with that problem; then handling problems around ```verify_binaries()``` would be easy, as we could make alternate version of ```BINARIES``` and ```verify_binaries``` and switch between them based on whether the desired stratisd was the initramfs or the full one. But we do not have that.

**Comment by agrover** [comment]
Since #986 went in, we just will fail to come up in initrd because xfs binaries are absent, so that's not a good state of affairs.

I was thinking we'd just config out XFS binaries being searched-for in BINARIES if building for initrd. Then calling them would return an error. We could also go further and cfg-out the callsites as well. Thoughts?

We also could punt and require xfs binaries in initrd, even though we never(?) will need them! Not saying we should, but this puts in perspective that this is really an optimization to keep our initrd footprint down.

Another tangential thought: right now we have a default feature of "dbus_enabled". Since that isn't the entirety of the changes we're now looking at for stratis-init, we may need to rename it, or add a second default feature.

**Comment by tasleson** [comment]
Should we just edit the dracut plugin to require all of the binaries?  I'm not sure if this will be OK due to space constraints, but it would make this issue go away.

**Comment by agrover** [comment]
Sure, let's just do that for now, and we can refine later if needed.

**Comment by tasleson** [comment]
PR posted upstream, see: https://github.com/dracutdevs/dracut/pull/452

**Comment by tasleson** [comment]
Upstream merged
